app/Http/Controllers/Bible/Study/CommentaryController.php, app/Http/Controllers/Bible/Study/LexiconController.php, app/Http/Controllers/User/SwaggerDocsController.php
- Updated API documentation on StudyBible endpoints
- /commentaries
- /commentaries/{commentary_id}/chapters
- Added book_id, chapter query parameters
- /commentaries/{commentary_id}/{book_id}/{chapter}
- Fixed query path
- Fixed query operationId
- Added book_id, chapter path parameters
- /lexicons
- Added limit parameter 
- Updated `SwaggerDocsController.php ` in order to add the missed components to the open-api documentation that are being used on v2 and v4.
- As a user, I’d like the API documentation and interactive Swagger to function with all options available to the StudyBible endpoints.
[FCBH-290](https://fullstacklabs.atlassian.net/browse/FCBH-290) …
=> FCBH-290 API Completeness: StudyBible

app/Http/Controllers/Bible/TextController.php, app/Http/Controllers/User/SwaggerDocsController.php
- Updated API documentation on Text endpoints
- /bibles/filesets/{id}/{book}/{chapter}
- Fixed endpoint path
- Added verse_start, verse_end query parameters
- /search
- Fixed ambiguous column name when filtering by books
- Updated `SwaggerDocsController.php ` in order to add the missed components to the open-api documentation that are being used on v2 and v4.
- As a user, I’d like the API documentation and interactive Swagger to function with all options available to the Text endpoints.
[FCBH-291](https://fullstacklabs.atlassian.net/browse/FCBH-291) 
- Navigate in your local environment to …
=> FCBH-291 API Completeness: Text

app/Http/Controllers/User/SwaggerDocsController.php, app/Http/Controllers/Wiki/CountriesController.php
- Updated API documentation on Languages endpoints
- /countries
- Changed has_filesets type to boolean
- /countries/{id}
- Removed unused parameters
- Updated SwaggerDocsController.php in order to add the missed components to the open-api documentation that are being used on v2 and v4.
- As a user, I’d like the API documentation and interactive Swagger to function with all options available to the Countries endpoints.
[FCBH-295](https://fullstacklabs.atlassian.net/browse/FCBH-295) 
- Navigate in your local environment to `http://dbp.test/docs/swagger/v4` or in the `swagger-editor` import …
=> FCBH-295 API Completeness: Countries

app/Http/Controllers/User/SwaggerDocsController.php, app/Http/Controllers/Wiki/AlphabetsController.php, app/Http/Controllers/Wiki/LanguagesController.php, app/Http/Controllers/Wiki/NumbersController.php, routes/api.php
- Updated API documentation on Languages endpoints
- /alphabets
- /alphabets​/{id}
- /languages​
- Changed language_name type to string
- Remove unused parameters has_bibles, has_filesets
- /languages​/{id}
- /numbers​/range
- Added API route
- Changed start default value to `0`
- /numbers
- /numbers​/{id}
-  Changed id type to NumeralSystem
- Updated SwaggerDocsController.php in order to add the missed components to the open-api documentation that are being used on v2 and v4.
- As a user, I’d like the API documentation and interactive Swagger to function with all options available to the Languages endpoints. …
=> FCBH-294 API Completeness: Languages

app/Http/Controllers/Bible/AudioController.php, app/Http/Controllers/Bible/BibleFileSetsController.php, app/Http/Controllers/Bible/LibraryController.php, app/Http/Controllers/Wiki/LanguageControllerV2.php
- This was fixed on https://github.com/faithcomesbyhearing/dbp/commit/bf16c426f4be081a3dfa3ef8fecae9af7ee03c48
- Previous book query was:
`$book_id = optional(Book::selectByID('id', $book_id)->select('id')->first())->id;`
instead of:
`$book_id = optional(Book::where('id_osis', $book_id)->first())->id;`
- Added important fixes to v2 documentation
- Added a missed comma on v4_bible_filesets.download
- Fixed operationId name on:
- v2_audio_location
- v2_library_volumeLanguage
- Added schema to limit parameter on v2_volume_history
- v2 `audio/path` endpoint wasn't filtering by the book id parameter
[FCBH-296](https://fullstacklabs.atlassian.net/browse/FCBH-296) 
- Navigate in your local environment to `https://api.dbp.test/open-api-v2.json` and …
=> FCBH-296 v2 No Getting Audio Properly

app/Http/Controllers/Bible/LibraryController.php, app/Models/Bible/BibleFileset.php, app/Transformers/FileSetTransformer.php
- Updated /library/volume documentation
- Fixed wrong query column names (updated_at)
- Reverted `f9b9cce0c3a115becae9b228ab54251469079a64 ` commit
- Added artwork_url to podcast endpoint
- v2 Artwork Routes: Android & iOS are not available
- podcast endpoint is not retrieving the new artwork URL 
- text access is unavailable
[FCBH-297](https://fullstacklabs.atlassian.net/browse/FCBH-297) 
[FCBH-298](https://fullstacklabs.atlassian.net/browse/FCBH-298) 
- On your local environment access to `https://api.dbp.test/library/volume?delivery=mobile&rich=1&key=809db3bd83c66f3bc41be0cbd6bd1e3f&v=3&language_code=ENG&updated=2018-09-06` and verify that the endpoint retrieves  the `artwork_url `
- On your local environmental  access to …
=> FCBH-297/298 v2 Artwork Routes

app/Http/Controllers/Bible/LibraryController.php, app/Http/Controllers/Connections/ArclightController.php
- On `/library/volume` endpoint fixed the filters:
- dam_id/fcbh_id
- language
- organization_id
- version_code
- `library/volume?dam_id` doesn’t filter
[FCBH-403](https://fullstacklabs.atlassian.net/browse/FCBH-403) 
- On your local environment run `https://api.dbp.test/library/volume?dam_id=HBRHMTN1DA&key={key}&v=3` also run `http://dbt.io/library/volume?dam_id=HBRHMTN1DA&key={key}&v=3`. The result must match
- Please repeat the procedure with the filters version_code (eg `M95`), organization_id (eg `82`) and language (eg `Hebrew`)
=> FCBH-403 v2 Languages Endpoints

app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/Playlist.php, database/migrations/2019_03_18_144021_create_changelog_table.php, database/migrations/2019_07_02_050029_create_playlists_table.php, routes/api.php
- Added CRUD Endpoints for playlists
- Added Playlist Database Migration
- Added Playlist Model
- As a user, I’d like the ability to create, update, delete, and get playlists of bible audio and/or video.
[FCBH-404](https://fullstacklabs.atlassian.net/browse/FCBH-404) 
[FCBH-405](https://fullstacklabs.atlassian.net/browse/FCBH-405) 
- On your local environment run `php artisan migrate --database="dbp_users"` to generate the database table
- On your local environment run `http://dbp.test/open-api-v4.json` and verify that now create, read and update endpoints are documented
- Test that now you can create, read and update a playlist
- Playlist items will be addressed on FCBH-454
=> FCBH-404/405 Backend: Playlists Support

routes/api.php
- Removed unused API routes from `routes/api.php `
- As a developer, I don’t want to have API route that doesn't have the correspondent controller function
[FCBH-379](https://fullstacklabs.atlassian.net/browse/FCBH-379) 
- Verify the code and check there is no mistakes
=> FCBH-379 Remove unused API routes

app/Http/Controllers/APIController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Http/Controllers/User/UsersController.php, app/Http/Controllers/User/UsersControllerV2.php, app/Http/Kernel.php, app/Http/Middleware/APIToken.php, app/Models/Playlist/Playlist.php, app/Transformers/UserTransformer.php, config/auth.php, database/migrations/2019_07_14_154139_add_user_api_token.php, routes/api.php
- Added `api_token` column to the users table
- When the user register/ login an `api_token` will be retrieved, this token will be stored hashed `hash('sha256', $token)`
- Added `api_token` to documentation as a SecurityScheme
- Updated Playlist CRUD endpoints to use api_token instead of `user_id`
- Created APIToken middleware in order to handle the `api_token` on the requests
- `middleware('APIToken:check')` will force to have a valid token
- `middleware('APIToken')` will allow an authenticated user to access data (for the logged-out experience)
[FCBH-377](https://fullstacklabs.atlassian.net/browse/FCBH-377) 
- Test that now you receive an `api_token` on login and registration
- This PR is …
=>  FCBH-377 Add user_token to login endpoint

app/Http/Controllers/APIController.php, app/Http/Controllers/ApiMetadataController.php, app/Http/Controllers/Bible/AudioController.php, app/Http/Controllers/Bible/BooksControllerV2.php, app/Http/Controllers/Bible/LibraryController.php, app/Http/Controllers/Bible/TextController.php, app/Http/Controllers/Organization/FilmsController.php, app/Http/Controllers/Organization/OrganizationsController.php, app/Http/Controllers/Organization/ResourcesController.php, app/Http/Controllers/User/SwaggerDocsController.php, app/Http/Controllers/Wiki/LanguageControllerV2.php
- Updated API documentation on Languages endpoints
- /library/asset
- Added asset_id, asset_type parameters
- /audio/versestart
- Added asset_id parameters
- /library/bookorder/
- Added documentation
- /library/metadata
- Added dam_id, asset_id
- /bibles/filesets/{id}/{book}/{chapter}
- Added asset_id
- /text/font
- Removed unused platform parameter
- /text/searchgroup
- Added asset_id
- /library/verseinfo
- Added asset_id
- /library/jesusfilm
- Added documentation
- /library/volumelanguagefamily/
- Added organization_id
- Removed  delivery, full_word, status, resolution unused parameters
- As a user, I’d like the v2 API documentation and interactive Swagger …
=> FCBH-374 API Completeness: v2 endpoints

app/Http/Controllers/Playlist/PlaylistsController.php, app/Http/Controllers/User/SwaggerDocsController.php
- Added the ability to handle an array of items on `/playlists/{playlist_id}/item` POST endpoint
- Removed `https` from the API_URL_DOCS
Original Story: [FCBH-662](https://fullstacklabs.atlassian.net/browse/FCBH-662) 
Review Story: [FCBH-705](https://fullstacklabs.atlassian.net/browse/FCBH-705) 
- On your `.env` file add to the `API_URL` var the scheme in order to be a complete url (`eg: https://api.dbp.test`)
- Test `/playlists/{playlist_id}/item` POST endpoint and check that now you can send a request with an array of playlist items
=> FCBH-662 Add Multiple Playlist items

app/Models/Plan/Plan.php, app/Models/Playlist/Playlist.php
- Changed Plan and Playlist models in order to return booleans instead of 1/0
Original Story: [FCBH-656](https://fullstacklabs.atlassian.net/browse/FCBH-656) 
Review Story: [FCBH-724](https://fullstacklabs.atlassian.net/browse/FCBH-724) 
- Test `/plans` GET endpoint and check that now you get booleans instead of numbers
- Test `/playlists` GET endpoint and check that now you get booleans instead of numbers
Plans reponse: 
Playlist response:
=> FCBH-656 Set true/false instead of 0/1 on playlists response

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php
- Added full object response on create plan endpoint
- Added full object response on create/edit/follow playlist endpoints
Original Story: [FCBH-657](https://fullstacklabs.atlassian.net/browse/FCBH-657) 
Original Story: [FCBH-658](https://fullstacklabs.atlassian.net/browse/FCBH-658) 
Review Story: [FCBH-725](https://fullstacklabs.atlassian.net/browse/FCBH-725)
Review Story: [FCBH-726](https://fullstacklabs.atlassian.net/browse/FCBH-726) 
- Test `/plans` POST endpoint and check that now you get a full object response
- Test `/playlists` POST endpoint and check that now you get a full object response
- Test `/playlists/{playlist_id}` PUT endpoint and check that now you get a full object response
- Test `/playlists/{playlist_id}/follow` POST endpoint and check that now you get a full object …
=> FCBH-657/658 Full playlist object on create/edit a Playlist/Plan

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php
- Added sort_by and sort_dir parameters to `/playlist` and  `/plans` GET endpoints
- sort_by default value is now `name`
- sort_dir default value is now `asc`
- Added new parameters to the documentation
- Added full object response on create plan endpoint
- Added full object response on create/edit/follow playlist endpoints
Original Story: [FCBH-667](https://fullstacklabs.atlassian.net/browse/FCBH-667) 
Review Story: [FCBH-727](https://fullstacklabs.atlassian.net/browse/FCBH-727) 
- Test `/plans` GET endpoint and check that now are ordered by name 
- Test `/playlists` GET endpoint and check that now are ordered by name 
- Change `sort_dir` parameter to `desc` and verify that the order changed
- …
=> FCBH-667 Plan/Playlist order

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Plan/PlanDay.php, app/Models/Plan/PlanDayComplete.php, app/Models/Plan/UserPlan.php, app/Models/Playlist/PlaylistItems.php, app/Models/Playlist/PlaylistItemsComplete.php, routes/api.php
- Added `complete` POST endpoint to plan days and playlist items controllers
- Added `completed` attribute to `PlanDay` and `PlaylistItems` models
- Added `complete` and `unComplete` methods  to `PlanDay` and `PlaylistItems` models
- Added `verifyCompleted` method to `PlanDay` model
- Created `PlanDayComplete` and `PlaylistItemsComplete` models
- Added `calculatePercentageComplete` to `UserPlan` model
Original Story: [FCBH-666](https://fullstacklabs.atlassian.net/browse/FCBH-666) 
Review Story: [FCBH-734](https://fullstacklabs.atlassian.net/browse/FCBH-734) 
- Test `/playlists/item/{item_id}/complete` POST endpoint and check that now you can complete an item, also check …
=> FCBH-666 Add completed to plans/playlists

app/Models/Playlist/Playlist.php, app/Models/Playlist/PlaylistItems.php
- Added `getVersesAttribute` function to Playlist Model
- Added `getVersesAttribute` function to PlaylistItems Model
Original Story: [FCBH-659](https://fullstacklabs.atlassian.net/browse/FCBH-659) 
Review Story: [FCBH-735](https://fullstacklabs.atlassian.net/browse/FCBH-735) 
- Test `/playlists` GET  endpoint and check that now the total number of verses appears
- Test `/playlists/{playlist_id}`  GET  endpoint and check that now the number of verses per item appears
=> FCBH-659 Calculate the number of verses on an Item and the total playlists

app/Http/Controllers/Plan/PlansController.php, app/Models/Bible/BibleFileset.php
- Fixed BibleFileset Scope filter by changing the query when the version of the api is `2`
- Tested by mitmproxy the backwards compatibility
Original Story: [FCBH-717](https://fullstacklabs.atlassian.net/browse/FCBH-717) 
Original Story: [FCBH-744](https://fullstacklabs.atlassian.net/browse/FCBH-744) 
Review Story: [FCBH-745](https://fullstacklabs.atlassian.net/browse/FCBH-745) 
Review Story: [FCBH-752](https://fullstacklabs.atlassian.net/browse/FCBH-752) 
**FCBH-744** 
- On your local environment run `http://api.dbp.test/bibles/filesets/ENGNIV/GEN/1?v=4&key={API_KEY}` and verify that the endpoint retrieves the verses
- Run `http://api.dbp.test/text/verse?dam_id=SPNBDAO2ET&book_id=Gen&chapter_id=2&key={API_KEY}&v=2` and that the endpoint retrieves the verses (backwards compatibility) …
=> FCBH-717/744 Incorrect fileset paths / Bible text retrieving wrong results

app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php
- Added `calculateDuration` function to `PlaylistItem` model in order to calculate the duration of a PlayListItem based on the `bible_file_timestamps` table
- If `bible_file_timestamps` doesn't have timestamps information for the query the duration value will be 0
Original Story: [FCBH-660](https://fullstacklabs.atlassian.net/browse/FCBH-660) 
Review Story: [FCBH-754](https://fullstacklabs.atlassian.net/browse/FCBH-754) 
- On your local environment call `/playlists/{playlist_id}/item` and verify that now the duration is calculated and saved (Not all the filesets have timestamps)
**Body request example:** 
```javascript
[
{
"fileset_id": "ENGESVO2DA",
"book_id": "GEN",
"chapter_start": 1,
"chapter_end": 3,
"verse_start": 10,
"verse_end": 1
},
{
"fileset_id": "ENGESVO2DA",
"book_id": "GEN", …
```
=> FCBH-660 Calculate playlist item length

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/User/UsersController.php, app/Models/Plan/UserPlan.php, routes/api.php
- Added `logout` endpoint in order to revoke the access of the api_token if the user logs out.
- Added documentation to endpoint
- Fixed bugs on reset plan endpoint
Original Story: [FCBH-669](https://fullstacklabs.atlassian.net/browse/FCBH-669) 
Review Story: [FCBH-761](https://fullstacklabs.atlassian.net/browse/FCBH-761) 
- `login` with a valid user to get an `api_token`
- Call `/logout` and verify that the `api_token` now don't have access
=> FCBH-669 Add log out endpoint that eliminates token access

app/Models/Bible/BibleFileset.php
- Production app is calling the highlights with `v=1` parameter
```javascript
GET http://api.bible.is/annotations/highlight?dbt_data=1&dbt_version=2&hash={GENERATED_HASH}&key={API_KEY}&limit=1000&offset=0&reply=json&u
ser_id=1149374&v=1
```
- Added `v1` support to scopeUniqueFileset function on BibleFileset model
Original Story: [FCBH-511](https://fullstacklabs.atlassian.net/browse/FCBH-511) 
Review Story: [FCBH-767](https://fullstacklabs.atlassian.net/browse/FCBH-767) 
- Run `http://api.dbp.local/annotations/highlight?dbt_data=1&dbt_version=2&hash={GENERATED_HASH}&key={API_KEY}&limit=1000&offset=0&reply=json&u
ser_id=1149374&v=1` and verify that you get highlights results
=> FCBH-511 Backwards Compatibility (iOS) - New User Accessing Highlights Crashes App

.env.example, config/app.php, resources/views/welcome.blade.php
- Added `get_started_url` to the app config file to allow an easy change or update of the getting started URL
- Now `https://github.com/faithcomesbyhearing/dbp/blob/master/doc/STARTING.md` is the link by default
Original Story: [FCBH-684](https://fullstacklabs.atlassian.net/browse/FCBH-684) 
Review Story: [FCBH-768](https://fullstacklabs.atlassian.net/browse/FCBH-768) 
- Run `http://dbp.test/`, click on `Get Started` and verify that the app navigates to `https://github.com/faithcomesbyhearing/dbp/blob/master/doc/STARTING.md`
=> FCBH-684 Add INSTALL.md to the frontend

app/Exceptions/Handler.php, app/Http/Controllers/APIController.php, routes/api.php
- Added friendly message for each error type
- Added type error to the response
- Removed all SQL error from the response
Original Story: [FCBH-682](https://fullstacklabs.atlassian.net/browse/FCBH-682) 
Review Story: [FCBH-798](https://fullstacklabs.atlassian.net/browse/FCBH-798) 
1) Change your `.env` file
```javascript
APP_ENV=production
APP_DEBUG=false
```
2) Run `https://api.dbp.test/test_test` to get a `404` error because the route doesn't exist
3) For testing purposes change the name of one table for example (user_notes to user_notess): 
Now run `https://api.dbp.test/users/1118817/notes?page=1&key={API_KEY}&v=4` and verify you get a 500 error without SQL text, we just get a code that will help us to find the issue
=> FCBH-682 Error messaging

.env.example, app/Exceptions/Handler.php, composer.json, composer.lock, config/app.php, config/sentry.php
- Installed and configured Sentry.io PHP SDK to report errors
Original Story: [FCBH-681](https://fullstacklabs.atlassian.net/browse/FCBH-681) 
Review Story: [FCBH-821](https://fullstacklabs.atlassian.net/browse/FCBH-821) 
- Run `composer install`
- Add to the `.env` file the `SENTRY_DSN=` key. (This key is on the Jira Story)
- On the `.env` file change `APP_ENV=local` to `APP_ENV=production`
- Open `http://dbp.test/wiki/bibles/undefined` to trigger an error
- Verify on `Sentry.io` that the error was reported
=> FCBH-681 Backend Error Reporting sentry.io

app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Wiki/LanguagesController.php, app/Models/Language/Language.php
- Verified that the languages, bibles and volumes content is being filtered by permissions
- Added permissions filter to detail endpoints `blibes/{id}`, `languages/{id}`
- Added `show_all` parameter to `languages` and `bibles`
Original Story: [FCBH-550](https://fullstacklabs.atlassian.net/browse/FCBH-550) 
Review Story: [FCBH-822](https://fullstacklabs.atlassian.net/browse/FCBH-822) 
- Add `show_all` parameter to `/languages` and `/bibles` endpoint and verify that all the content is being retrieved
- Run `/languages/{id}` and `/bibles/{id}` on a restricted bible or language and verify that now is not retrieved
=> FCBH-550 Filter all endpoints for permissions

app/Http/Controllers/Wiki/LanguagesController.php, app/Models/Language/Language.php, app/Transformers/LanguageTransformer.php
Added language ordering by country if the country param is sent in.  Jon thought this was already done, but languages were always returned ordered by their id.  Now they are either returned alphabetically if all languages are gotten or they are returned in country language population order if the country code is specified.
=> FCBH-694 Language Ordering

app/Http/Controllers/Bible/VideoStreamController.php, app/Traits/ArclightConnection.php, routes/api.php
- Updated `arclight/jesus-film/chapters` endpoint:
- Added metadata (thumbs, descriptions, file url)
- Added `iso` parameter
- Added cache
Original Story: [FCBH-806](https://fullstacklabs.atlassian.net/browse/FCBH-654) 
Review Story: [FCBH-847](https://fullstacklabs.atlassian.net/browse/FCBH-847) 
- On your local environment run `https://api.dbp.test/arclight/jesus-film/chapters?v=4&key={API_KEY}&iso=spa` and verify that now you get the chapter metadata sending the `iso` parameter
- Run `https://api.dbp.test/arclight/jesus-film/chapters?v=4&key={API_KEY}&arclight_id=21046` and verify that the endpoint also works with `arclight_id` language parameter
=> FCBH-806 Jesus Film API Additions

app/Http/Controllers/User/UsersController.php, app/Http/Middleware/APIToken.php, app/Models/User/ApiToken.php, app/Providers/AuthServiceProvider.php, app/Services/Auth/ApiTokenGuard.php, config/auth.php, database/migrations/2019_09_21_212431_create_user_api_tokens_table.php
- Created the migration to add a new table `user_api_tokens` in order to allow the user to log in on different devices
- Created new APIToken Guard and Model
- Updated APIToken middleware to use the new Guard
- Updated UsersController to use the new APIToken model on `login/register/logout` endpoints
Original Story: [FCBH-668](https://fullstacklabs.atlassian.net/browse/FCBH-668) 
Review Story: [FCBH-857](https://fullstacklabs.atlassian.net/browse/FCBH-857) 
- Test that now you receive an `api_token` on login and registration as usual
- Try to get `plans`, `playlists`
- Try to `logout`
=> FCBH-668 Multiple login tokens per Users

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Http/Controllers/Bible/StreamController.php, app/Http/Controllers/Bible/VideoStreamController.php, app/Models/Bible/BibleFile.php, app/Models/Bible/StreamBandwidth.php, app/Models/Bible/StreamSegment.php, database/migrations/2019_09_27_144323_hls_audio.php, database/seeds/RealDataSeeder.php, routes/api.php, tests/Integration/VideoRoutesTest.php
- Added an HLS migration in order to do:
- Renamed `bible_file_video_resolutions` to `bible_file_stream_bandwidths`
- Renamed `bible_file_video_transport_stream` to `bible_file_stream_segments`
- Made nullable `resolution_width` and `resolution_height` on `bible_file_stream_bandwidths` table
- Changed `video_resolution_id` column name to `stream_bandwidth_id`
- Renamed `VideoResolution` Model to `StreamBandwidth`
- Renamed `VideoTransportStream` Model to `StreamSegment`
- Created StreamController file to handle the `HLS` api requests
- Updated BibleFileSetsController to support `video_stream` and `audio_stream`
Original Story: [FCBH-528](https://fullstacklabs.atlassian.net/browse/FCBH-528) 
Review Story: [FCBH-859](https://fullstacklabs.atlassian.net/browse/FCBH-859) 
- On your local …
=> FCBH-528 HLS Audio Support and Serving

app/Console/Commands/showEnvironment.php, app/Console/Kernel.php, app/Providers/RouteServiceProvider.php
- Added `php artisan showEnvironment` command in order to show the ENV vairables
- Removed domain check on API routes.
- Run `php artisan showEnvironment` and verify you get the environment vars
- Set a wrong `API_URL` and verify that the API still works
=> Add artisan command to show environment

app/Http/Controllers/User/UsersControllerV2.php, app/Models/User/Study/Highlight.php
- Fixed wrong book names filtering by bible id
- Fixed v2 Highlights endpoint by adding missing book_id
Original Story: [FCBH-856](https://fullstacklabs.atlassian.net/browse/FCBH-856) 
Review Story: [FCBH-943](https://fullstacklabs.atlassian.net/browse/FCBH-943) 
- Run `https://api.dbp.test/users/{USER_ID}/highlights?page=1&v=4&key={API_KEY}` and verify you get the correct book names
=> FCBH-856 Book Names are incorrect on created Annotations

app/Http/Controllers/APIController.php, app/Models/Plan/UserPlan.php, app/Providers/RouteServiceProvider.php
- Removed API subdomain and moved to the path
- Fixed error on complete plan endpoint when a day is empty
- Run `valet unlink api.dbp`
- Run `valet link dbp`
- Run `valet secure`
- Change the `API_URL` on the `.env` file to be `https://dbp.test/api` instead of `https://api.dbp.test`
- Test that the endpoints are working
=> FCBH-948 Change API subdomain to Path

app/Models/Bible/BibleFileset.php, app/Models/User/Study/Highlight.php, app/Transformers/V2/Annotations/HighlightTransformer.php
- Fixed wrong fileset query when the `version` is sent on the header
- Added verse_text to the highlight POST action
Original Story: [FCBH-960](https://fullstacklabs.atlassian.net/browse/FCBH-960) 
Review Story: [FCBH-981](https://fullstacklabs.atlassian.net/browse/FCBH-981) 
- Run `http://dbp.test/api/bibles/filesets/ENGNIV/GEN/1?asset_id=dbp-prod` sending the `v` and `key` on the header and verify that the response retrieves data
- Create a highlight and verify that now the response retrieves the verse_text
=> FCBH-960 No Bible Text on ENGNIV

app/Http/Controllers/User/UsersController.php, app/Models/User/Study/Highlight.php, app/Services/Auth/ApiTokenGuard.php, routes/api.php
- Added 1 year expiration time to the user api_tokens
- Added `/token/validate` endpoint to validate, renew and get user details
Original Story: [FCBH-861](https://fullstacklabs.atlassian.net/browse/FCBH-861) 
Review Story: [FCBH-980](https://fullstacklabs.atlassian.net/browse/FCBH-980) 
- Test that the `/token/validate` endpoint validates the user `api_token`
- Test that `user_details` param retrieves the user on the response
- Test that `renew_token` param deletes the `old_token` and generates a new one
**(*)Note:** If you want to reverse the migration run `php artisan migrate:rollback --database="dbp_users"`
=> FCBH-861 Token Validator Endpoint

app/Http/Controllers/Bible/StreamController.php, app/Models/Bible/StreamSegment.php, app/Models/Bible/Timestamp.php, database/migrations/2019_10_22_183925_add_byterange_support.php
- Added byte-range support migration
- Added Timestamp Model
- Added timestamp relation to the StreamSegment model
- Modified StreamController to support byte-range segments
Original Story: [FCBH-949](https://fullstacklabs.atlassian.net/browse/FCBH-949) 
Review Story: [FCBH-1042](https://fullstacklabs.atlassian.net/browse/FCBH-1042) 
- Run the SQL dump query to seed the database
- Run `https://dbp.test/api/bibles/filesets/ENGESVN2SA?type=audio_stream&size=NTP&asset_id=dbp-prod&v=4&key={API_KEY}` and verify you get 2 chapters (JHN 1 is with ts segments, JHN 2 is with byte-range)
- Run `http://dbp.test/api/bible/filesets/ENGESVN2SA/1912079/playlist.m3u8?asset_id=dbp-prod&v=4&key={API_KEY}` on …
=> FCBH-949 Implement HLS Byte Range

app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/User/PasswordsController.php, app/Models/Bible/BibleDefault.php, app/Models/Plan/Plan.php, app/Models/User/Study/Highlight.php, database/migrations/2019_10_17_122023_add_bibles_defaults_table.php, database/migrations/2019_10_17_154139_add_plan_image.php, routes/api.php
- Added support for api_token and old_password on `/users/password/reset` endpoint
- Added `bibles/defaults/types` endpoint
- Added bibles_defaults table migration
- Added image field for plans
- Added support to filter bible filesets by input asset_id prop on `bible/{bible_id}` endpoint
- Added documentation
Original Story: [FCBH-962](https://fullstacklabs.atlassian.net/browse/FCBH-962) 
Review Story: [FCBH-1054](https://fullstacklabs.atlassian.net/browse/FCBH-1054) 
- Test that the `old_password` field on `/users/password/reset` is working
- Test `bibles/defaults/types`
- Add an `image_url` to a featured plan and verify …
=> FCBH-962 Backend  Small Task Bucket

app/Http/Controllers/User/UsersController.php, app/Models/User/Profile.php, app/Transformers/UserTransformer.php, database/migrations/2019_10_28_133905_users_name_column_nullable.php
Removed requirements around names for registration and user validation in general. This required a migration to make the name field of the user nullable. Also, generated a profile on registration for the new user and altered the Profile model to be able to do such.
[FCBH-1045(https://fullstacklabs.atlassian.net/browse/FCBH-1045)
- On your local environment run `php artisan migrate --database="dbp_users"` to run the migration to make name a nullable field on User
- Register a user with no name and observe that this functions with no error from the backend and also returns the newly created profile object as part of the response.
=> FCBH-1045 Edit account broken with brand new account

app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Bible/VideoStreamController.php
Allow for an array of filesets when getting a bible's version detail.
**Also:** Jesus films have duplicate language ids solely based on iso code. We are now taking the one with the most number of speakers. The ones were were previously getting listed no speakers and threw an error for the specified ID.
=> FCBH-1078 Fileset issue edge cases

app/Http/Controllers/User/NotesController.php, app/Models/User/Study/Note.php
- On the `POST/PUT` notes endpoints added logic to avoid null values on the notes
- Retrieving an empty string instead of a 500 error when the notes decryption is not successful
- This was affecting all the notes if just one note has an issue with decryption the user could not get the other ones.
Original Story: [FCBH-1086](https://fullstacklabs.atlassian.net/browse/FCBH-1086) 
Review Story: [FCBH-1116](https://fullstacklabs.atlassian.net/browse/FCBH-1116) 
- On your local environment change the value of one of the notes to `NULL`
- Call `https://dbp.test/api/users/{USER_ID}/notes?chapter_id=4&limit=25&page=1&sort_by=updated_at&sort_dir=desc&key={API_KEY}&v=4` and verify you don't get an error
=> FCBH-1086 Backend Small Bucket

app/Models/User/User.php, app/Transformers/UserTransformer.php, database/migrations/2019_10_24_174251_add_freshchat_restore_id_to_user.php
The avatar column does not exist in the user table and was causing an error when trying to update the user.  It can be added back in when an implementation of the avatar is done.  Also added the `freshchat_restore_id` to the fillable.
=> FCBH-833 Remove avatar from User fillable

app/Http/Controllers/Bible/StreamController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Bible/StreamBandwidth.php, app/Models/Bible/StreamBytes.php, app/Models/Bible/StreamTS.php, database/migrations/2019_11_09_175918_create_bible_files_stream_bytes_table.php, database/seeds/RealDataSeeder.php
- Added migration to create `bible_file_stream_bytes` table
- Removed `bytes, offset and timestamp_id` from `bible_file_stream_segments` table
- Renamed `bible_file_stream_segments` to `bible_file_stream_ts`
- Updated StreamController and PlaylistController to work with the new tables schema
Original Story: [FCBH-1114](https://fullstacklabs.atlassian.net/browse/FCBH-1114) 
Review Story: [FCBH-1142](https://fullstacklabs.atlassian.net/browse/FCBH-1142) 
- Test `playlists/{id}/`, `/playlists?showDetails=true` endpoints and verify that now you get the path parameter with the hls file of the playlist 
- Test `ENGESV` chapters are working
**(*)Note:** If you want to reverse the migration run `php …
=> FCBH-1114 Create separate byterate/segments tables

app/Exceptions/Handler.php, app/Http/Middleware/APIToken.php
- Added a `401` api_response when the api_token is required and is not valid
Original Story: [FCBH-1093](https://fullstacklabs.atlassian.net/browse/FCBH-1093) 
Review Story: [FCBH-1145](https://fullstacklabs.atlassian.net/browse/FCBH-1145) 
- On your local environment test `https://dbp.test/api/push_notifications?key={API_KEY}&v=4&api_token=wrong_api_token` GET endpoint and verify you get a 401 error
=> FCBH-1093 Return a 401 error instead of 500 when the api_token is required and is not valid

app/Models/Plan/UserPlan.php
When a plan is reset, the day items need to also be reset.  This quick enumeration of each plan day and playlist item accomplishes that.
=> FCBH-1123 Delete completed day items

app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php, database/migrations/2019_11_21_084934_add_verses_to_playlist_items_table.php
- Added `verses` row to PlayListItem to avoid multiple calculations when the query of the playlist items, now the calculation is being done when the item is created
- Added migration that also fills the new verses row
Original Story: [FCBH-1173](https://fullstacklabs.atlassian.net/browse/FCBH-1173) 
- Test `playlists` GET and verify that is working correctly
**(*)Note:** If you want to reverse the migration run `php artisan migrate:rollback --database="dbp_users"`
=> FCBH-1173 Long loads on Playlists

app/Http/Controllers/Bible/BibleFileSetsController.php, routes/api.php
- Added `bibles/filesets/check/types` in order to validate Bible locations
- Now we can validate if the objects have audio and video
Original Story: [FCBH-1191](https://fullstacklabs.atlassian.net/browse/FCBH-1191) 
- Test the body example on `bibles/filesets/check/types` POST endpoint and verify that you get a `has_audio`, `has_video` response
**Body:**
```javascript
[
{
"fileset_id": "ENGESV",
"book_id": "MAT",
"chapter_start": 1,
"chapter_end": 1,
"verse_start": 1,
"verse_end": 2
},
{
"fileset_id": "ENGESV",
"book_id": "GEN",
"chapter_start": 1,
"chapter_end": 1,
"verse_start": 1,
"verse_end": 2
}
]
```
**Result:**
```javascript 
[
{
"fileset_id": "ENGESV",
"book_id": "MAT",
"chapter_start": 1,
"chapter_end": 1, …
```
=> FCBH-1191 Fileset "has audio" endpoint

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Bible/BooksController.php, app/Transformers/BooksTransformer.php
- Added `verify_content` and `asset_id` parameters to `/bibles/{id}/book` endpoint in order to return only the books with content.
- Now the returned books have a `content_types` array with the the types of filests availables
Original Story: [FCBH-1171](https://fullstacklabs.atlassian.net/browse/FCBH-1171) 
- Test the body example on `https://dbp.test/api/bibles/TGKIBT/book?v=4&{API_KEY}&verify_content=true&asset_id=dbp-prod,dbp-vid` and verify that the books returned are only the ones with content
**Result:**
```javascript
[
{
"book_id": "RUT",
"book_id_usfx": "RT",
"book_id_osis": "Ruth",
"name": "Рут",
"testament": "OT",
"testament_order": 8,
"book_order": 8,
"book_group": "Historical Books",
"chapters": [
1,
2,
3, …
```
=> FCBH-1171 Chapters returned without Content

app/Models/Bible/BibleFileset.php
instead of relying on a bible id match, all connected filesets are gotten. If the connections are available, then we'll use the same old method of trying to match up by id.
=> FCBH-1206 Looking for unique filesets should include connections

app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/Playlist.php
- Now sending Bible Id for Playlist items so that we can display that properly and not just do the slice on the fileset string.
- Also fixed a tiny issue where the items weren't getting sent in when creating HLS for mp3 audio and thus the durations of the items were not being read by the client.
- Do a get pull to get playlists with items and observe that the items have bible ids: `/playlists/{PLAYLIST_ID}?asset_id=dbp-prod&api_token={API_TOKEN}&v=4&key={API_KEY}`
- Get HLS for a playlist that has mp3 audio and ensure that each item has durations: `/playlists/{PLAYLIST_ID}/hls?v=4&key={API_KEY}`
=> FCBH-1208 Small fixes to support miniplayer/playlists

app/Models/Bible/BibleFileset.php
- Added database prefix name to `DB::table` connection in order to be sure that the correct table is always called
=> Add database name to fileset query

app/Helpers/Helpers.php, app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Http/Controllers/User/UsersController.php, app/Http/Controllers/Wiki/LanguagesController.php, app/Transformers/LanguageTransformer.php
- Added `checkBoolean` helper function to validate boolean parameters
- Added `show_bibles` parameter to `/languages` endpoint to retrieve the content of the bibles
- The `filesets` and `bibles` on `/languages` endpoint are now filtered by the `asset_id` parameter
Original Story: [FCBH-1268](https://fullstacklabs.atlassian.net/browse/FCBH-1268) 
- Test `http://dbp.test/api/languages?key={API_KEY}&v=4&show_bibles=true&asset_id=dbp-vid`GET` endpoint and verify that you get only the bibles with videos and also you get the content of the bibles.
=> FCBH-1268 Fix empty languages for Gospel Films

app/Http/Controllers/Playlist/PlaylistsController.php
- Fixed the way we collected the duration from the items to get the highest one.
Original Story: [FCBH-1292](https://fullstacklabs.atlassian.net/browse/FCBH-1292) 
- Test `http://dbp.test/api/playlists/{PLAYLIST_ID}/hls?v=4&key={API_KEY}` GET endpoint and verify that the `#EXT-X-TARGETDURATION` value is the highest value of the `#EXTINF` values
=> FCBH-1292 Sending in verse start/end breaks whole chapter playlist items

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Http/Controllers/Bible/StreamController.php, app/Http/Controllers/Playlist/PlaylistsController.php, database/migrations/2019_12_17_143936_udpate_type_code_length_to_fileset_types_table.php
- Added `audio_drama_stream` bible_fileset_types support
- Added migration to support 18 characters length of set_type_code
Original Story: [FCBH-1302](https://fullstacklabs.atlassian.net/browse/FCBH-1302) 
- Verify that you can add `audio_drama_stream` type
```sql
INSERT INTO `bible_fileset_types` ( `set_type_code`, `name`)
VALUES ( 'audio_drama_stream', 'HLS Audio Drama Stream ');
```
- For testing purposes change `ENGESVN2SA` fileset type to `audio_drama_stream`
- Run `https://dbp.test/api/bibles/filesets/ENGESVN2SA?type=audio_drama_stream&size=NTP&asset_id=dbp-prod&v=4&key={API_KEY}` and verify is working 
**(*)Note:** If you want to reverse the migration run `php artisan …
=> FCBH-1302 Add Streaming Drama audio type

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Bible/Study/CommentaryController.php
- GET and POST Swagger Annotations was uppercase and the server is case sensitive. Now all the annotations are capitalized.
- Run `http://dev.v4.dbt.io/open-api-v4.json` to get the new documentation
- Run `http://4.dbt.io/open-api-v4.json` to get the new documentation
=> Documentation Annotations fix

app/Http/Controllers/User/HighlightsController.php
- Fixed rgb to hex conversion on `HighlightsController`, the length of the hex color must be 6
Original Story - [FCBH-1202](https://fullstacklabs.atlassian.net/browse/FCBH-1202) 
Review Story - [FCBH-1363](https://fullstacklabs.atlassian.net/browse/FCBH-1363) 
- Test `/users/{USER_ID}/highlights?v=4&key={API_KEY}` `POST` endpoint with the following body and verify on the database that the color is created correctly
```json
{
"book_id": "GEN",
"book_name": "Genesis",
"chapter": 1,
"verse_start": 1,
"verse_end": 1,
"bible_id": "EN1ESV",
"highlighted_color": "#fce600",
"highlight_start": 1,
"highlighted_words": 10,
"user_id": {USER_ID}
}
```
=> FCBH-1202 Newly created yellow highlights returning green

resources/views/docs/sdk.blade.php
The current url in the documentation is the HTML pages allowing users to interact with the documentation.  The route `swagger_docs_gen` is the correct route for generating the Open API JSON.
=> Use the correct route for the open-api JSON generation

app/Http/Controllers/Bible/TextController.php
- Fixed a SQL injection vulnerability
- Improved the speed on the search results by using `like` instead of `MATCH AGAINST`, this also fixes missing results when searching words like `the`, `i am`
Original Story: [FCBH-1322](https://fullstacklabs.atlassian.net/browse/FCBH-1322) 
Review Story: [FCBH-1367](https://fullstacklabs.atlassian.net/browse/FCBH-1367) 
- Test `/search?relevance_order=true&fileset_id=ENGNIV&page=1&v=4&key={API_KEY}&query={QUERY}` `GET` endpoint
- Search for `QUERY=god` and verify that all the results are in book/chapter/verse order and the response time is improved
- Search for a SQL character like `QUERY=god";SHOW DATABASES;` and verify that the SQL injection is fixed
=> FCBH-1322 Bible search results should appear in bible book/chapter/verse order

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php
- Added `delete_days` and `delete_items` to update Plans/Playlists endpoints'
Original Story: [FCBH-1091](https://fullstacklabs.atlassian.net/browse/FCBH-1091) 
Review Story: [FCBH-1370](https://fullstacklabs.atlassian.net/browse/FCBH-1370) 
- Test `/playlists/{playlist_id}?v=4&key={API_KEY}&delete_items=true` `Put` endpoint and verify that all the items are deleted
- Test `/plans/{plan_id}?v=4&key={API_KEY}&delete_days=true` `Put` endpoint and verify that all the days are deleted
=> FCBH-1091 Pl/an item reset improvement

app/Http/Controllers/Wiki/LanguagesController.php
Languages were only being ordered by their name in the languages table.  This did not accurately reflect how these languages were eventually presented with their name either being that value or the value of the name in language_translations.  Therefore the order was flawed.  Using a raw `orderBy` and an `ifnull` statement, the same procedure for the transformer was applied to the ordering.
=> FCBH-1337 Fix language ordering

app/Http/Controllers/User/UsersController.php
This PR changes the auth priority to favor social id over email. Basically, if a social provider id is passed into the service, the assumption is that we should use that ID to auth instead of a potential email address.
[FCBH-1347](https://fullstacklabs.atlassian.net/browse/FCBH-1347)
=> FCBH-1347 Social login issues

app/Console/Commands/syncV2Users.php, app/Http/Controllers/User/AccountsController.php, config/settings.php, resources/lang/eng/api.php
- Added the v2 users that don't have a project assigned to the default project after the user's sync finalizes
- Added missing translation for `project_users_404`
=> Hotfix - Assign v2 to v4 new users to a project

app/Console/Commands/syncV2Database.php, app/Console/Kernel.php, app/Models/Notifications/NotifyToSlack.php, app/Notifications/SyncNotification.php, composer.json, composer.lock
- Installed "laravel/slack-notification-channel" in order to notify the slack channel when an error is present
- Created syncV2Database in order to:
- Catch an error
- Do the sync in order, if an error in users exists won't continue the sync
[FCBH-1397](https://fullstacklabs.atlassian.net/browse/FCBH-1397) 
- On your local environment run `composer install` to install the notification library
- Add to your `.env` file the `LOG_SLACK_WEBHOOK_URL` env variable
- Add this cron job to your environment
`* * * * * cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1`
=> FCBH-1397 Improve v2->v4 sync scheduling and reporting

app/Models/Playlist/PlaylistItems.php
- If the current playlist item doesn't have the verses information the API now ads verses count info from BibleVerse if available
=> FCBH-1399 Verse count on playlist is incorrect

app/Console/Commands/syncPlaylistDuration.php, app/Console/Kernel.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php, routes/api.php
- If there are no timestamps available try to get the duration from the bible files
- Added an artisan command `php artisan  sync:playlistDuration` to sync the duration of the currently created playlists
- Added individual hls path to playlist items
- This PR won't affect the previous behavior of this endpoint, we still have a path for the full playlists
Story: [FCBH-1520](https://fullstacklabs.atlassian.net/browse/FCBH-1520)  
- On your local environment run `php artisan  sync:playlistDuration` to update the duration of the playlist items, new playlist item will calculate the duration when are created
- Run `/api/playlists/{playlist_id}?v=4&key={API_KEY}` to get the detail of a playlists
- Verify that now the items have a path of the hls file
- Open the global path and the path of the …
=> FCBH-1520 Improve Playlists by separating items

app/Http/Controllers/User/BookmarksController.php, app/Http/Controllers/User/HighlightsController.php, app/Http/Controllers/User/NotesController.php
- Added book name search on Highlights
- Added book name search on Bookmarks
- Added book name search on Notes
Story: [FCBH-1509](https://fullstacklabs.atlassian.net/browse/FCBH-1509)  
- Run `/api//users/{user_id}/highlights?query={QUERY}&v=4&key={API_KEY}` and verify that the highlights are being filtered by the book name
- Run `/api//users/{user_id}/notes?query={QUERY}&v=4&key={API_KEY}` and verify that the notes are being filtered by the book name
- Run `/api//users/{user_id}/bookmarks?query={QUERY}&v=4&key={API_KEY}` and verify that the bookmarks are being filtered by the book name
=> FCBH-1509 Highlights Task - Broaden search ability

app/Http/Controllers/Plan/PlansController.php, app/Models/Plan/UserPlan.php
- Fixed reset plan day function, now will only reset the plan for the user who is doing the request.
- Fixed when a user stops a plan that also hides the plan for the plans GET endpoint. 
Story: [FCBH-1607](https://fullstacklabs.atlassian.net/browse/FCBH-1607)  
- Run `/api/plans/{PLAN_ID}/stop?bible_id={BIBLE_ID}&v=4&key={API_KEY}& api_token={USER_API_TOKEN}` and verify that the plan is removed from the user_plan table
=> FCBH-1607 Share plan

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, routes/api.php
- Added plan and playlist `/translate` endpoints.
- The endpoints have a `bible_id` parameter to verify if the playlist items have a translation on the bible filesets. If an item doesn't have translation it will have a `has_translation=false` parameter
Original Story: [FCBH-1488](https://fullstacklabs.atlassian.net/browse/FCBH-1488)  
Review Story: [FCBH-1634](https://fullstacklabs.atlassian.net/browse/FCBH-1634)  
- Run `/api/plans/{PLAN_ID}/translate?bible_id={BIBLE_ID}&v=4&key={API_KEY}& api_token={USER_API_TOKEN}` and verify that the list of days with the list of translated items
- Run `/api/playlists/{PLAYLISTS_ID}/translate?bible_id={BIBLE_ID}&v=4&key={API_KEY}& api_token={USER_API_TOKEN}` and verify that the list of translated items
=> FCBH-1488 Get playlist/plan translations from server

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php
- Added `show_text` param to the plan/playlist index endpoint
Story: [FCBH-1575](https://fullstacklabs.atlassian.net/browse/FCBH-1575)  
- Run `http://dbp.test/api/playlists?api_token={API_TOKEN}&v=4&key={API_KEY}&show_text=true`
- Verify the verse_text are retrieved
=> FCBH-1575 Pl/an Reader: Mechanism for getting Pl/an item Bible text

app/Http/Controllers/ApiMetadataController.php, config/cache.php
this is intended to make the /status endpoint more accurate by actually verifying cache behavior and returning 500 instead of 417 (client error)
=> Improve status

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php
- Added 365 size limit to plan days
- Added 100 size limit to playlists items
- [Link](https://sentry.io/organizations/fullstack-labs/issues/1585049464/?project=1728656&query=is%3Aunresolved+v4_plans.store&statsPeriod=14d)
- Run POST `https://dbp.test/api/plans?api_token={API_TOKEN}&v=4&key={KEY}` and verify that you can only create 365 days of a plan
- Run POST `https://dbp.test/api/plans/{plan_id}/day?api_token={API_TOKEN}&v=4&key={KEY}` and verify that you can not add more than 365 total days
- Run POST `https://dbp.test/api/playlists/{playlist_id}/item?api_token={API_TOKEN}&v=4&key={KEY}` and verify that you can not add more than 100 total playlist items
=> Add limit to plan days / playlists items [sentry]

app/Http/Controllers/User/BookmarksController.php
- Fixed bookmark delete() on null by adding a 404 response when a bookmark is not present
- [Link](https://sentry.io/organizations/fullstack-labs/issues/1559570330)
- Run DELETE `https://dbp.test/api/users/{USER_ID}/bookmarks/{BOOKMARK_ID}?api_token={API_TOKEN}&v=4&key={KEY}` and verify you get a 404 instead of a 500
=> Fix bookmark delete() on null [sentry]

app/Http/Controllers/Bible/VideoStreamController.php
- Added default value to `$iso` parameter on jesusFilmChapters function
- [Link](https://sentry.io/organizations/fullstack-labs/issues/1586199917)
- Run GET `http://dbp.test/api/arclight/jesus-film/chapters?v=4&key={KEY}&iso=cfm` and verify you get a correct response instead of a 500
=> Fix missing parameters on jesusFilmChapters [sentry]

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php
- Added cache for featured plans and playlists
- Run `https://dbp.test/api/plans?featured=true&api_token={API_TOKEN}&v=4&key={KEY}` and verify that the featured plans are being cached
- Run `https://dbp.test/api/playlists?featured=true&api_token={API_TOKEN}&v=4&key={KEY}` and verify that the featured playlists are being cached
- Run `https://dbp.test/api/plans?featured=false&api_token={API_TOKEN}&v=4&key={KEY}` and verify that the user plans are not being cached
- Run `https://dbp.test/api/playlists?featured=false&api_token={API_TOKEN}&v=4&key={KEY}` and verify that the user playlists are not being cached
=> Add cache for featured plans and playlists

app/Http/Controllers/User/NotesController.php
- Fixed note delete() on null by adding the missing 404 response when a note is not present
- [Link](https://sentry.io/organizations/fullstack-labs/issues/1586387591/?project=1728656&query=is%3Aunresolved)
- Run DELETE `https://dbp.test/api/users/{USER_ID}/notes/{NOTE_ID}?api_token={API_TOKEN}&v=4&key={KEY}` and verify you get a 404 instead of a 500
=> Fix note delete() on null [sentry]

app/Http/Controllers/Bible/VideoStreamController.php, app/Traits/ArclightConnection.php
- Added a 404 response instead of a 500 when a Jesus film component is not found
- [Link](https://sentry.io/organizations/fullstack-labs/issues/1537582457)
- Run GET `http://dbp.test/api/arclight/jesus-film/chapters?arclight_id=23179&v=4&key={KEY}` and verify retrieves content
- Run GET `http://dbp.test/api/arclight/jesus-film/chapters?arclight_id=4823&v=4&key={KEY}` and verify retrieves a 404 instead of a 500
=> Catch 404 response on Jesus Film Query [sentry]

app/Http/Controllers/Bible/StreamController.php, app/Http/Controllers/Playlist/PlaylistsController.php
- Fixed resume from pause by changing the #EXT-X-TARGETDURATION to the duration of the audio
- Removed EXTINF extra metadata
Story: [FCBH-1690](https://fullstacklabs.atlassian.net/browse/FCBH-1690)  
- Run the app on iOS
- Select an HLS chapter
- Verify that you can pause and resume after more than 2 minutes
=> FCBH-1690 HLS byterange truncated audio and resume from pause

app/Console/Commands/DeleteDraftPlaylistsPlans.php, app/Console/Kernel.php, app/Helpers/Helpers.php, app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Plan/Plan.php, app/Models/Playlist/Playlist.php, database/migrations/2020_03_11_173257_add_draft_playlists_plans.php, routes/api.php
- Added migration in order to add a draft column to plans and playlists
- Added plans and playlists /draft `POST` endpoint in order to change the draft status
- Remove draft plans and playlist from the `GET` all endpoints
- Added `DeleteDraftPlaylistsPlans` command in order to delete all the draft plans and playlists of more than 1 day old
- Added items and draft to `POST`  playlist endpoint
- Fixed wrong boolean validation on checkBoolean helper function
Story: [FCBH-1561](https://fullstacklabs.atlassian.net/browse/FCBH-1561)  
**Requirements:**
- Select the `FCBH-1561` client branch
**Search temporary playlist:**
- Navigate to `My Bible -> Search`
- Search for any word `Jesus`
- Click on …
=> FCBH-1561 Enable play button for temp playlists

app/Http/Controllers/Bible/BiblesController.php
- Casting `text_plain` fileset as object to avoid non-object errors
=> Mauricio 3.1.0 Hotfixes

app/Http/Controllers/Bible/BiblesController.php
- When the user is trying to download a chapter and a non-drama or drama option is selected to retrieve the available option.
- Added 404 response when a book is not found
Story: [FCBH-1770](https://fullstacklabs.atlassian.net/browse/FCBH-1770) 
- Run `http://dbp.test/api/bibles/EN1ESV/chapter?asset_id=dbp-prod&book_id=GEN&chapter=13&key={API_KEY}&v=4&zip=true&drama=true` and verify that the non_drama content is retrieved.
=> FCBH-1770 Downloads still not working in background on iOS

app/Http/Controllers/Bible/AudioController.php, app/Http/Controllers/Bible/BiblesController.php, app/Transformers/AudioTransformer.php
- Added timestamps from `transportStreamBytes` if are not available on the timestamps.bible_file_id table
- Updated `/timestamps/{fileset_id}/{book}/{chapter}` endpoint
- Updated `/bibles/{bible_id}/chapter` endpoint
[FCBH-1771](https://fullstacklabs.atlassian.net/browse/FCBH-1771) 
- Run `http://dbp.test/api/timestamps/ENGESVN2SA/MRK/1?asset_id=dbp-prod&v=4&key={API_KEY}` and verify you get timestamps results
- Run` http://dbp.test/api/bibles/ENGESV/chapter?asset_id=dbp-prod&v=4&key={API_KEY}&chapter=1&book_id=MRK` and verify you get timestamps results
=> FCBH-1771 Get Timestamps for streaming audio

app/Console/Commands/reSyncV2Notes.php, app/Console/Kernel.php
- Added `php artisan reSyncV2:notes {note_id?}` command in order to resync existing notes if the note exists on both v2 & v4, and has not changed on v4.
- Syncing a note takes 1 to 3 seconds on average so we are doing chunks of 25 notes to avoid overlapping with users interaction
- The script validates if the notes have not been changed before doing the resync
- There is a `bookmark` column that is not being used, so I used it as a flag to mark the resynced notes. So if for some reason we stop the script we don't lose the progress
[FCBH-1845](https://fullstacklabs.atlassian.net/browse/FCBH-1845) 
- Run `php artisan reSyncV2:notes {note_id}` to resync only 1 note
- Run `php artisan reSyncV2:notes` to resync all notes
=> FCBH-1845 Resync Script for Notes

app/Console/Commands/encryptNote.php, app/Console/Commands/reSyncV2Notes.php, app/Console/Kernel.php, config/database.php
- Added comparison to the notes with the v2_utf8 note to avoid resyncing notes
- Added `encryptNote` command in order to run the asynchronous encryption and improve the speed
- Implemented 1 single mysql query to update the chunk of notes and improve the speed
=> FCBH-1845 Filter Resync Script Notes and improve speed

app/Http/Controllers/Bible/TextController.php, app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/Playlist.php, app/Models/Playlist/PlaylistItems.php, database/migrations/2020_05_15_172217_add_plan_to_playlist_table.php
- Improved playlists endpoint by using a left join with `plan_days `
- Improved plan creation
- Improved plan days creation
- Added cache where is missed
[FCBH-1714](https://fullstacklabs.atlassian.net/browse/FCBH-1714) 
- Change your .env file to `CACHE_DRIVER=array` to remove the cache (just for testing)
- On your local environment run php artisan migrate --database="dbp_users" to run the migrations
- Run `http://dbp.test/api/playlists?v=4&key={KEY}` and verify that now the query takes less than a second
- Try to create a plan with 1095 days and verify that now takes a couple of seconds
=> FCBH-1830 Improve pl/ans endpoints

app/Helpers/Helpers.php, app/Http/Controllers/Wiki/LanguagesController.php, app/Models/Language/Language.php
- Improved `v4_languages.one` and `v4_languages.all` endpoints by processing the hash access control codes only one time
- Added random parameter to the `v4_languages.all` endpoint
[FCBH-1836](https://fullstacklabs.atlassian.net/browse/FCBH-1836) 
- Run `http://dbp.test/api/languages?v=4&key={API_KEY}` and verify that the query is faster than the develop branch
Before: 
After:
=> FCBH-1836 Improve languages endpoints

.ebextensions/cloudwatch-memory.config
This PR updates the .ebextension configuration for pumping custom Cloudwatch metrics to use root instead of ec2-user. User "ec2-user" did not have permission to write to /var/log/cwpump. In addition, the frequency was changed from 5 minutes to 1 minute. This allows more time to adjust if an ec2 instance is nearing max memory
=> update Cloudwatch config for custom metrics (memory and disk)

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Http/Controllers/Bible/StreamController.php, app/Http/Controllers/Playlist/PlaylistsController.php, routes/api.php
- Added v0=0 argument when there is no verse 0 only when there is no v0 segment
- Removed EXT-X-ALLOW-CACHE:YES
- Added `Book-Chapter-VerseStart-VerseEnd` instead of the file id on the `media_stream` url
[FCBH-1996](https://fullstacklabs.atlassian.net/browse/FCBH-1996) 
- Run `http://dbp.test/api/bible/filesets/ENGESVN1SA/MAT-13-1-/playlist.m3u8?v=4&key={KEY}` and verify is working
- Run `http://dbp.test/api/bible/filesets/ENGESVN1SA/2186122/playlist.m3u8?v=4&key={KEY}` and verify that is also working
- Run the app with the `develop` backend branch selected, then run the app with the `FCBH-1996` backend branch selected and verify that the audio and video are playing correctly
=> FCBH-1996 bad behavior when verse e0 data

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php
- Updated `playlists/{playlist_id}/translate` endpoint to create a draft playlist
- Updated `plans/{plan_id}/translate` endpoint to create a draft plan
[FCBH-1714](https://fullstacklabs.atlassian.net/browse/FCBH-1714) 
- Run `/api/plans/{PLAN_ID}/translate?bible_id={BIBLE_ID}&v=4&key={API_KEY}& api_token={USER_API_TOKEN}` and verify you get the draft translated plan
- Run `/api/playlists/{PLAYLISTS_ID}/translate?bible_id={BIBLE_ID}&v=4&key={API_KEY}& api_token={USER_API_TOKEN}` and verify you get the draft translated playlist
=> FCBH-1714 Finalize Pl/an Translations

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php
- Added metadata information about the translation to the pl/ans translate endpoint. This way we avoid the user making multiple calls to the server
[FCBH-2000](https://fullstacklabs.atlassian.net/browse/FCBH-2000) 
- Run `http://dbp.test/api/plans/{PLAN_ID}/translate?api_token={API_TOKEN}&v=4&key=52e62d4c-f7c8-4a8b-9008-8634d0fbddb0&show_details=true&bible_id={BIBLE_ID}` and verify you get `translation_data` and `translated_percentage`
- Run `http://dbp.test/api/playlists/{PLAYLIST_ID}/translate?api_token={API_TOKEN}&v=4&key=52e62d4c-f7c8-4a8b-9008-8634d0fbddb0&show_details=true&bible_id={BIBLE_ID}` and verify you get `translation_data` and `translated_percentage`
=> FCBH-2000 Translation plan/playlist

app/Http/Controllers/Bible/BiblesController.php, routes/api.php
- Created `/bibles/{bible_id}/chapter/annotations` endpoint
- The new enpoint only retrives to a logged user the annotations of a chapter/book/bible
Original Story: [FCBH-2210](https://fullstacklabs.atlassian.net/browse/FCBH-2210) 
Review Story: [FCBH-2224](https://fullstacklabs.atlassian.net/browse/FCBH-2224) 
- Run `http://dbp.test/api/bibles/{BIBLE_ID}/chapter/annotations?chapter={CHAPTER}&book_id={BOOK_ID}&api_token={API_TOKEN}&key={KEY}&v=4`
=> FCBH-2210 Add annotations endpoint

app/Http/Controllers/Bible/BiblesController.php
- Fixed wrong query when looking for a size of testament that is complete with another that is partial
- We now look for the presence of the size of the testament on the set_size_code of the fileset. For example for this size code `NTOTP` we look if `NT` is present, we were looking for `NTP`. 
Original Story: [FCBH-2135](https://fullstacklabs.atlassian.net/browse/FCBH-2135) 
- Navigate to `http://dbp.test/api/bibles/HATBIV/chapter?asset_id=dbp-prod&chapter=8&book_id=2CO&key={KEY}&v=4` and verify the text content is displayed
=> FCBH-2135 Text not showing up for several languages

app/Http/Controllers/User/BookmarksController.php, app/Http/Controllers/User/NotesController.php, app/Transformers/V2/Annotations/BookmarkTransformer.php
- Fixed bookmarks and notes creation timestamps response
Original Story: [FCBH-2132](https://fullstacklabs.atlassian.net/browse/FCBH-2132) 
- Open the app targeting the local API
- Create a note and verify that the response has the `created_at` and `updated_at` fields
- Create a bookmark and verify that the response has the `created_at`, `updated_at` fields and `book_id` fields
=> FCBH-2132 Creation note is not returning timestamps

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Plan/Plan.php, app/Models/Playlist/Playlist.php, database/migrations/2020_08_01_020137_add_language_plans_playlists.php
- Added `iso` parameter to plans and playlists index endpoints
- Added migration to support language_id column on user_playlists and plans tables
Original Story: [FCBH-2207](https://fullstacklabs.atlassian.net/browse/FCBH-2207) 
- Set the language_id code `6414` to the featured plans and playlists you want on `dbp_users` database
- Navigate to `http://dbp.test/api/plans?asset_id=dbp-prod&featured=true&iso=eng&v=4&key={KEY}` and verify that the plans are being filtered by the iso code
- Navigate to `http://dbp.test/api/playlists?asset_id=dbp-prod&featured=true&iso=eng&v=4&key={KEY}` and verify that the playlists are being filtered by the iso code
- Do not send the iso …
=> FCBH-2207 Discoverable pl/plans in languages other than English

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, routes/api.php
- Added SHOW_TEXT flag to `playlist/{playlist_id}` endpoint
- Fixed SHOW_TEXT flag on `plans/{plan_id}` endpoint
- Created `playlist/{playlist_id}/text` endpoint that retrieves the text from the playlists items
Original Story: [FCBH-2213](https://fullstacklabs.atlassian.net/browse/FCBH-2213) 
- Navigate to `http://dbp.test/api/playlists/{PLAYLIST_ID}/text?key={KEY}&v=4` and verify you get only the text of the playlist items
- Navigate to `http://dbp.test/api/playlists/{PLAYLIST_ID}?key={KEY}&v=4&show_text=true` and verify you get the playlist items text
- Navigate to `http://dbp.test/api/playlists?key={KEY}&v=4&show_text=true` and verify you get the playlist items text
- Navigate to `http://dbp.test/api/playlists/{PLAN_ID}?key={KEY}&v=4&show_text=true` and verify you get the playlist …
=> FCBH-2213 Provide Verse Text for Playlists & Plans

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Http/Controllers/Bible/BiblesController.php
- Improved chapter detail endpoint by adding cache where is possible
- Added 24 hours cache to the bible, book and copyrights queries
- Added 12 hours cache to chapter filesets content
Original Story: [FCBH-2106](https://fullstacklabs.atlassian.net/browse/FCBH-2106) 
- Navigate to `http://dbp.test/api/bibles/{BIBLE_ID}/chapter?v=4&key={KEY}&book_id={BOOK_ID}&chapter={CHAPTER}&copyrights=true` and verify you get the same content that the `develop` branch but faster after the endpoint is memcached
=> FCBH-2106 Improve chapter detail API endpoint

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php
- Added cache to the translation of the pl/ans to speed up the process
- Translated all the playlist items in group instead than one per one 
Original Story: [FCBH-2253](https://fullstacklabs.atlassian.net/browse/FCBH-2253) 
- Run `/plans/{plan_id}/translate` API endpoint on a large plan and very that you don't get a 504 error and the response is faster than develop
=> FCBH-2253 Timeout error when translating a very large plan

app/Http/Controllers/Bible/BiblesController.php, app/Models/User/UserDownload.php, database/migrations/2020_09_10_215230_add_user_downloads_table.php
* Create a migration for userDownloads with id, user_id, fileset_id, and created_at 
* Create model for userDownloads with foreign keys for user, fileset and book
* Add userDownloads on bible controller, creating the model when there's a user and there's a drama/non_drama fileset
* use cache to save user  downloads
[FCBH-2384](https://fullstacklabs.atlassian.net/browse/FCBH-2384) 
- Run migrations and check the user_download table was created
- Test `/bibles/{bible_id}` `GET` endpoint (You must have an api_token, use zip true, add chapter and book id, and assign drama keys)
- Check the if the user_download row was created with the correct data
- [] I have updated the documentation accordingly.
=> FCBH-2384 Add user data to downloads

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Http/Controllers/User/UsersController.php
- Fix order by adding the 'order_column' while the pl/an is being translated, without this the order of the items is not being inserted correctly causing conflicts on the translated view.
[FCBH-2435](https://fullstacklabs.atlassian.net/browse/FCBH-2435) 
- Open the app with the FCBH-2435 backend branch seletec.
- Navigate to the ONE 2021 plan
- Click on translate -> English -> NIV
- Verify you get the correct conent
=> FCBH-2435 Plan translation (ONE>NIV, maybe others)

app/Http/Controllers/Bible/StreamController.php
- Add check (for null and 0) on streamController for verseEnd in bible files
- there are files with chapter end on 0 (not sure if that's intentional)
- the problem was in the db bible_files table, there are different approaches on the chapter_end sometimes “NULL” is used and sometimes 0, we did an extra check to pass either of those.
Original Story: [FCBH-2430](https://fullstacklabs.atlassian.net/browse/FCBH-2430) 
- Call `https://dev.dbt.io/api/bible/filesets/ENGKJVP2DV/MAT-1-1-0/playlist.m3u8?v=4&key=52e62d4c-f7c8-4a8b-9008-8634d0fbddb0&api_token=cXxyvWdW1rjzChIjKcaQpdmGmMgMMLnN7OSO2Cv3ifSX1A7HyaaLGIIQA9nS
=> FCBH-2430 check verseEnd for bible files

app/Http/Controllers/Bible/BiblesController.php
- Added fileset metadata to the gospel_films object on the CD endpoint in order to notify the client the video's fileset
Original Story: [FCBH-2425](https://fullstacklabs.atlassian.net/browse/FCBH-2425) 
- Call `http://dbp.test/api/bibles/OZMTBL/chapter?asset_id=dbp-prod&chapter=1&book_id=MRK&key={API_KEY}&v=4` and verify you get the fileset metadata values on the gospel_film section
=> FCBH-2425 Properly set filesetId in GOSPEL_FILMS videoStart and videoStop analytics event_types

.ebextensions/artisan.config
We are unable to deploy to develop due to an artisan update of geoip, which fails when https://geolite.maxmind.com/ is down (as it is now), thus causing the health check to fail
=> remove geoip update temporarily

.ebextensions/artisan.config, app/Http/Kernel.php
The intent is to configure DBP Rate limiting to match AWS WAF, so that clients can get better feedback when being rate-limited. With this change, the WAF and DBP will both Rate Limit to 150 requests in 5 minutes. We can adjust the rates once we confirm the client is responding to DBP response headers
=> Modify DBP Rate Limit to match WAF

app/Console/Commands/translatePlan.php, app/Console/Kernel.php, app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php
- Added an artisan php command to translate a plan to multiple bibles
Original Story: [FCBH-2311](https://fullstacklabs.atlassian.net/browse/FCBH-2311) 
- On your local environment run `php artisan translate:plan {PLAN_ID} {COMMA_SEPARATED_BIBLES_IDS}` to run the translation
- Verify that the plans are being translated
=> FCBH-2311 Create script for plan translation

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php
- Added get timestamps functionality to the playlists and plans endpoints
Original Story: [FCBH-2535](https://fullstacklabs.atlassian.net/browse/FCBH-2535) 
- Call `http://dbp.test/api/playlists/{PLAYLIST_ID}?v=4&key={APP_KEY}show_details=true&show_text=true` and verify you get the texts and the timestamps
=> FCBH-2535 Update playlist endpoint to retrieve timestamps so Pl/an reader auto-scrolls properly

app/Console/Commands/syncPlaylistDuration.php
- Added get timestamps functionality to the playlists and plans endpoints
Original Story: [FCBH-2032](https://fullstacklabs.atlassian.net/browse/FCBH-2032) 
- Create playlist or plan and add playlist_items
- run console command: php artisan sync:playlistDuration
- Check that the duration and verses of the related playlist_items is updated on the db
=> FCBH-2032 Create script to sync pl/ans verses and duration

.ebextensions/artisan.config, app/Http/Kernel.php, app/Http/Middleware/ApiVersion.php
This PR enforces a sharper distinction between versions. For example, a v2 route will not be found if the request parameter v is not equal to 2
=> add Middleware to require version match

app/Http/Controllers/Playlist/PlaylistsController.php
* Check show_details param
* Add verse_text to playlist items
* Add swagger documentation
[FCBH-2704](https://fullstacklabs.atlassian.net/browse/FCBH-2704)
* Translate a playlist with http://dbp.test/api/playlists/{playlist_id}/translate
* you'll have to use show_details: true, and bible_id as params
* Check that the response gets the verses text
=> FCBH-2704 show text of translated playlists

app/Http/Controllers/Bible/AudioController.php
This PR fixed the broken results of timestamps
=> (Hot Fix) Revert FCBH-2826 backward compatibility with DBP2 - $book change

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/Playlist.php
- Added the plan_id to the translated playlists from a plan
Original Story: [FCBH-2804](https://fullstacklabs.atlassian.net/browse/FCBH-2804) 
- Please translate a plan, then verify you do not get the translated playlists of the plan into the playlists screen.
=> FCBH-2804 Every plan that is created/translated, also creating a playlist for every day.

app/Http/Controllers/Bible/BiblesController.php, app/Transformers/BooksTransformer.php
- Added `verse_count` parameter to the bible->book endpoint in order to have the verse_count of the chapters
- If there are no verses the object won't be retrieved
- Run the following query and verify that you get now the verse count of the chapters
- `http://dbp.test/api/bibles/{BIBLE_ID}/book?asset_id=dbp-prod,dbp-vid&verify_content=true&key={KEY}&v=4&verse_count=true`
=> [Gideons branch] Add verse_count parameter to books endpoint

app/Transformers/UserTransformer.php
This PR fixes the naming of the API endpoints on the user transformer.
At this moment we are not getting the api_token breaking the app functionality after registration
=> Fix user transformer

app/Http/Controllers/Bible/BiblesController.php
* return empty array on metadata for jesus film if empty
[FCBH-3127](https://fullstacklabs.atlassian.net/browse/FCBH-3127)
* Check that calling this endpoints don't return an error
* {dbp_url}/api/bibles/FIN38CB/chapter?asset_id=dbp-prod&chapter=26&book_id=MAT&api_token=LVgoHpP8AEKDVanN4weBvQSndO4YqAuDqlKP0BYQY9GY8KbDco0ZitmQDUFu
and
{dbp_url}/api/bibles/NORNBV/chapter?asset_id=dbp-prod&chapter=6&book_id=MAT&api_token=null
=> FCBH-3127 fix jesus film error returning 500

app/Models/User/Study/Bookmark.php
* Check if the bible was returned before calling its properties
[FCBH-3132](https://fullstacklabs.atlassian.net/browse/FCBH-3132)
* Go to basePath/users/711732/bookmarks?asset_id=dbp-prod&sort_by=updated_at&sort_dir=desc&page=1
* set v = 4 and key = 52e62d4c-f7c8-4a8b-9008-8634d0fbddb0 params
* call should not return a 500 error, but a 200 with data 
=> FCBH-3132 fix error on bible undefined with bookmarks

app/Models/User/Study/Highlight.php
* Check if the bible was returned before calling its properties
* Check fileset exist before calling properties
* If data was not set correctly, return empty testament book
[FCBH-3133](https://fullstacklabs.atlassian.net/browse/FCBH-3133)
* basePath/users/1314767/highlights?asset_id=dbp-prod&prefer_color=hex&sort_by=id&sort_dir=desc&page=1&query=&color=fd2e2e%2C%23fd2e2e
* set v = 4 and key = 52e62d4c-f7c8-4a8b-9008-8634d0fbddb0 params
* call should not return a 500 error, but a 200 with data 
=> FCBH-3133 add defensive code on highligh filesets data

app/Models/User/Study/Note.php
* Check if the bible on notes exists before calling the bibles queries on name and verseText
[FCBH-3134](https://fullstacklabs.atlassian.net/browse/FCBH-3134)
* Go to /users/923214/notes?asset_id=dbp-prod&sort_by=updated_at&sort_dir=desc&page=1
* set v = 4 and key = 52e62d4c-f7c8-4a8b-9008-8634d0fbddb0 params
* call should not return a 500 error, but a 200 with data, or, if it throws an error it has to be either a 404 or a 401
=> FCBH-3134 add defensive code on notes model

app/Http/Controllers/Playlist/PlaylistsController.php
* Check if the getPlaylist does not return an error or a null
* Check the playlist->items exists before running an action on them
[FCBH-3131](https://fullstacklabs.atlassian.net/browse/FCBH-3131)
* Go to basePath/playlists/3640818?asset_id=dbp-prod&api_token=EtoLIhKGzm9cdAObDpSYVzvLCDC1lqumXPbLx4RfKLvNIMPsZZy6EWLqmtZP&show_text=true
* set v = 4 and key = 52e62d4c-f7c8-4a8b-9008-8634d0fbddb0 params
* call should not return a 500 error, but a 200 with data or a 404 “playlist not found“ 
=> FCBH-3131 add defensive code on playlists not found or without items

app/Http/Controllers/User/UsersController.php
=> FCBH-3126 avoid checking null email on social providers

app/Models/User/RoleUser.php
in FCBH-2781, the database (dbp_users) was removed from the RoleUser Model table. This change only exists in earlyaccess, and apparently causes a failure during user creation. This PR adds the database name back in
=> add dbp_users database to role_user to disambiguate

app/Http/Controllers/Bible/VideoStreamController.php
* Remove cache from media-components calls, which return the hls ulrs
[FCBH-2309](https://fullstacklabs.atlassian.net/browse/FCBH-2309)
* Go to jesus films
* Play some videos
* Re-visit the videos after 5 hours
* VIdeos should work as expected
=> FCBH-2309 Remove caching from jesus film media calls

app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php
* check if there exists an invalid fileset for each playlist item (data issue)
* Add validations in PlaylistItems model and playlist controller
[FCBHDBP-29](https://fullstacklabs.atlassian.net/browse/FCBHDBP-29)
* to reproduce this issue there has to be an incorrect fileset_id on an item of the playlist in the playlist_items table
* this will be tested with postman with: https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-8c588e98-de29-48fe-b338-cfc36aaf724a
=> FCBHDBP-29 fix invalid fileset for each playlist item (data issue)

app/Http/Controllers/Bible/VideoStreamController.php, config/settings.php
* use env variable: FORBIDDEN_ARCLIGHT_ISO=hun (can have a list like: hun,spa)
* default to english if the iso of the call is included in the list FORBIDDEN_ARCLIGHT_ISO
[FCBHDBP-43](https://fullstacklabs.atlassian.net/browse/FCBHDBP-43)
* go to {base_api}/arclight/jesus-film/chapters?asset_id=dbp-prod&iso=hun&arclight_id=1107&key=52e62d4c-f7c8-4a8b-9008-8634d0fbddb0&v=4
* text data should be in english, not on hungarian
=> FCBHDBP-43 use eng as default for hugarian jesus films

app/Http/Controllers/Bible/BooksController.php, routes/api.php
Restore implementation of bibles/filesets/<id>/books. This is deprecated, but still used by bible.is 3.0.x and older. This was found from NewRelic analysis
No Jira ticket created. 
ensure this Postman test produces good results, and not a 500 error
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-a16a0c41-1a36-4d2a-a2b7-2f228721b9e6
=> restore bibles/filesets/books implementation

app/Http/Controllers/Bible/BooksController.php
* Add 404 error response if fileset and fileset_type combination doesn't exist
Go to https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-a16a0c41-1a36-4d2a-a2b7-2f228721b9e6
* The original response should return the correct book data
* If you remove the "fileset_type" param, or the filesetId does not exist, the endpoint will return a 404 instead of 500 error
=> Book fileset backward compatibility (deprecated)

app/Helpers/Helpers.php, app/Http/Controllers/Bible/BiblesController.php, config/settings.php
This will need a bit of discussion, it. does nont look like user agent is retrieving the data we want, this is easily achievable on bibleis side headers.
* add helper to deprecate endpoints/functions for all users, except old bibleis/gid app users
* Deprecate chapter endpoint 
* Deprecate non-pagination for bibleis/gideons newest
* format app version from user agent and compare with formatted deprecation version
MISSING:
* confirm ios and android versions (configurable on .env)
* Get correct data from user agent
[FCBHDBP-133](https://fullstacklabs.atlassian.net/browse/FCBHDBP-133)
[FCBHDBP-137](https://fullstacklabs.atlassian.net/browse/FCBHDBP-137)
[FCBHDBP-139](https://fullstacklabs.atlassian.net/browse/FCBHDBP-139)
=> FCBHDBP-137 deprecate endpoints/functionalities

app/Http/Controllers/Wiki/LanguagesController.php, app/Models/Language/Language.php
Remove filter by fileset asset id on languages controllers due to new access control returning languages ids
=> Fix languageController filters by languages instead of filesets

app/Exceptions/Handler.php, app/Exceptions/ResponseException.php
It has replaced the array_flip method because the `getConstants` method is returning for the Response Class some constants with boolean values. The above generates an error when the array_flip is invoked with an array with boolean values.
it has created a custom Response class (`app/Exceptions/ResponseException.php`) to index the HTTP status names with the HTTP codes. The above because `sonarsource` doesn't recommend to use the `getConstants` method of `ReflectionClass` class to get HTTP status names the  because it could lead to run-time errors.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-167
You can use the next endpoint and you should see the correct message error.
http://dbp-phpupdate-beanstalk.eba-3j8mmhad.us-west-2.elasticbeanstalk.com/api/bibles/filesets/ENGESVN1SA/MAT/1?v=4& …
=> FCBHDBP-167 php8 upgrade - array_flip exception

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Models/Plan/PlanDayComplete.php, app/Models/Plan/UserPlan.php, app/Models/Playlist/PlaylistFollower.php, app/Models/Playlist/PlaylistItemsComplete.php, app/Models/Traits/ModelBase.php
- it has added a trait to support composite primary keys for the model class.
- It has added a fix to the `checkTypes` endpoint. We need to add the pluck method because the `video_filesets_hashes` parameter was storing the query instance before and the results was not being fetching.
- Removed the type constraint for the method `setKeysForSaveQuery` for the query input parameter. The above because the last version of laravel has also removed it.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-170
I can run the bible.is mobile request on postman for the current branch.
=> FCBHDBP-170 Incompatible method signature - UserPlan::setKeysForSaveQuery

app/Http/Controllers/Bible/BibleFileSetsController.php, routes/api.php
It has update the v4_media_stream route to allow verse_end and verse_start as optional parameters.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-168
Use the next endpoint ->
- Active Development / new in php upgrade / bibles-filesets-id-id-id (SA)
- basePath/bibles/filesets/:filesetid/:bookid/:chapterid?v=4
=> FCBHDBP-168 php8 upgrade - bibles-filesets-id-id-id fails on php8, php74, but works on current php72

app/Models/Bible/BibleFileset.php
The `starts_with` method has been replaced by `Illuminate\Support\Str::startsWith()`
https://fullstacklabs.atlassian.net/browse/FCBHDBP-173
You can test the endpoint (library-volume Copy) on postman:
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-19e5ad74-c223-4959-b781-13cf6778c35b
=> FCBHDBP-173 Fix the endpoint library-volume Copy for php8 env

app/Http/Controllers/Bible/TextController.php
It has fixed the text verse endpoint. For now on, DBP4 returns only one verse if verse_end parameter is not provided and verse_end will be equal to verse_start if verse_end is empty.
I have tested for the version 2 and 3.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-166
You can test it with postman using the next URL:
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-1459d5d9-a970-4bc8-9dd6-d1af9007e75d
And used the value `ENGESV` for the `dam_id` parameter
=> FCBHDBP-166 v2 backward compatibility - text verse with verse start should return one verse

app/Http/Controllers/Bible/LibraryController.php
It added the feature to respect the media filter.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-165
You can use the next test and you should filter by media=audio and it should return only media results.
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-c37a4e7b-4c0c-4fea-8360-1f8a3007195d
=> FCBHDBP-165 v2 backward compatibility - library volume does not respect media = audio

renovate.json
It has added the renovatebot file config. It will only keep the composer.json as dependency source and the minors upgrading will be group into a only PR by dependency.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-161
When we enable the renovatebot we should see only PRs for composer dependencies.
=> FCBHDBP-161 configure renovate to update minor versions

app/Http/Controllers/ApiKey/DashboardController.php, app/Http/Controllers/ApiKey/KeysController.php, app/Models/User/KeyRequest.php, database/migrations/2021_09_10_171217_add_application_name_and_application_url_to_user_key_requests_table.php, resources/views/api_key/dashboard.blade.php, resources/views/api_key/request_key.blade.php
It has added the two new parameters: application_name and application_url for the user_key_requests table. It has updated the Key Management view to add the two new columns.
Created two new columns for the table `user_key_requests` to store the `application_name` and `application_url` and when the method to approve the key is called (approveApiKey)  the application_name will be stored into user_keys.name, the current `name` will be stored into users.name and the application_url will be appended to `user_keys.description` .
https://fullstacklabs.atlassian.net/browse/FCBHDBP-159
1. Go to the URL /api_key/request
2. Fill the form
3. Got the URL api_key/dashboard and approve the api_key request.
4. See into the database that the new `user_keys` record has: `name` = application_name and the …
=> FCBHDBP-159 on DBP Key request screen, capture app name and app url

app/Console/Commands/S3LogBackup.php, app/Http/Controllers/APIController.php, app/Http/Controllers/Bible/AudioControllerV2.php, app/Jobs/SendApiLogs.php, app/Logs/CloudfrontApiKeyFormatter.php, app/Logs/EmptyLineFormatter.php, app/Traits/CallsBucketsTrait.php, config/logging.php
it has created a feature to store into new file log a relationship between a `Cloudfront signed url` and the `API key`. Then, it has created a new log channel to handle the entries into the new log file. The new log file is called: `cloudfront_api_key.log` and it is located into the floder `storate/logs`.
The entries stored into the `cloudfront_api_key.log` has the pattern `{time} {key} {signature}` e.g.
```log
2021-09-16 17:09:28 API_KEY_XXXX-YYYY SIGNATURE_HhiS9lUT1ohR11
```
`Signature` value is extract from the query parameters from signed URL, if the Signature doesn't exist, the entire signed URL will be stored. The `Key` is the API Key that user uses to do the request.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-164
1. Execute e.g. /library/volume
2. You should see into the …
=> FCBHDBP-164 implement mapping between DBP API keys and Cloudfront access

app/Http/Controllers/Bible/BiblesController.php, app/Models/Bible/Bible.php
It has improved the endpoint to pull the bibles with the `filesets` relationship. It has update the query to pull the `filesets` and it has used the operator EXISTS to improve the performance.
We should execute the next endpoint just after when the cache has been cleaned.
- List All Bibles/Filesets in a language
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-1bd358a1-24c0-4a7a-b1dd-0a835862b2f9
- List All Bibles/Filesets in a language that have Dramatized Audio
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-394cf2be-8e03-466a-a8b4-fab1a88960c2
- List All Bibles/Filesets in a language that have Streaming …
=> FCBHDBP-174 Hardening - Example Workflow endpoints should return in less than one second (for non-cached requests)

app/Http/Middleware/APIVersion.php
for the version 2, if the version query parameter has more than 1 digit it will strip everything after the first digit.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-183
You can execute the next endpoint and you should not see any error:
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-a9ea88da-b047-4c66-85f8-990ec3677a02
=> FCBHDBP-183 error on v2 backward compat - v=2.12.1

app/Http/Controllers/Wiki/LanguageControllerV2.php, app/Models/Language/Language.php
it has fixed the `library/volumelanguagefamily` endpoint. It has added the join related with `bible_filesets` because Language entity has only registered the relation with `bible_fileset_connections` entity.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-181
You should execute the next endpoint it should return error:
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-f527e2af-aee7-47e5-93ae-e626f895b305
=> FCBHDBP-181 500 error in v2 backward compat - volumelanguagefamily with media=audio

app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Wiki/CountriesController.php, app/Http/Controllers/Wiki/LanguagesController.php, app/Models/Language/Language.php, database/migrations/2021_09_22_173446_add_fulltext_index_countries_languages_bibles.php
it has added the `FULLTEXT` index for the entities: languages, countries, language_translations and bible_translations. The goal is to expand the searching related with the above entities.
We must run the migration before to call the endpoints:
```bash
php artisan migrate --path=/database/migrations/2021_09_22_173446_add_fulltext_index_countries_languages_bibles.php
```
- Contries: you can test with `faso` word. It should return a record about Burkina Faso country
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-1c473cb7-c83a-425c-81ee-fb53045ca27f
- Bibles: It should continue working correclty.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-46fe99f1 …
=> FCBHDBP it has added the FULLTEXT index bibles languages and countries

app/Http/Controllers/Bible/AudioController.php, app/Models/Bible/BibleFile.php
It has improved the query to pull the bible files that have a `bible_file_timestamps` record attached. The query to fetch the has_id from bible_files entities has been refactored.
The next query was taking into a local environment around 3 seconds:
```sql
select distinct `hash_id`
from `bible_files` 
where exists (
select * from `bible_file_timestamps` where `bible_files`.`id` = `bible_file_timestamps`.`bible_file_id`
);
```
The above sql query was replaced by the next query and it takes around 600ms to fetch the hash_ids bible_files entities into a local environment.
```sql
SELECT `bible_files`.`hash_id` FROM `bible_files`
INNER JOIN (
SELECT distint_timestamps.bible_file_id
FROM (
SELECT DISTINCT bible_file_timestamps.bible_file_id
FROM bible_file_timestamps
) AS distint_timestamps …
```
=> FCBHDBP-187 hardening: optimize slow query bible_file_timestamps

app/Models/Bible/BibleFile.php
It has fixed the next spell error 'distint_timestamps' has been renamed to 'distinct_timestamps'
=> FCBHDBP fixed the next spell error

app/Http/Controllers/Bible/BiblesController.php
Avoid that dbp crashes when it tries to download the content from `content.cdn.dbp` and the content does not exist or cdn returns access denied.
The current case is related with the bible ARBVDV and the bible_filesets attached. I saw that on my local database I have two filesets with set_size_code `OT`:
```sql
ARZVDVO1DA	42510b5d7dfe dbp-prod audio	        OT	0	2018-02-13 10:27:06	2018-09-07 17:39:24	ARBVDV
ARZVDVO2DA	6db7b153c52e dbp-prod audio_drama	OT	0	2018-02-13 10:27:03	2018-09-07 17:39:24	ARBVDV
```
So, dbp tries to download the ARZVDVO1DA audios using the next path but it path is not correct.
- `https://content.cdn.dbp-prod.dbp4.org/audio/ARBVDV/ARZVDVO1DA`
You should execute the next postman test - VDV CDN - exact request that causes 500 error:
- …
=> FCBHDBP-197 ARBVDV - 500 error

app/Http/Controllers/Bible/BiblesController.php
It has added a null-checking conditional to make sure the fileset object is not null before to post-process.  It should be related with a specific fileset for ARBVDV bible.
```json
{
"id": "ARZVDVO2DA",
"type": "audio_drama",
"size": "OT"
}
```
https://fullstacklabs.atlassian.net/browse/FCBHDBP-208
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-2e7ea5c3-26e4-4f09-8f7f-9073925dbed9
=> FCBHDBP-208 500 error in Production - chapter detail related to ARBVDV

app/Http/Controllers/Bible/LibraryController.php, app/Traits/CallsBucketsTrait.php, app/Transformers/V2/LibraryVolumeTransformer.php
It has added the feature to fetch a library/volume by dam_id without the language_code filter.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-218
- The next postman url should return the fileset according to given dam_id
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-a456764c-7135-4405-bba8-ac5d3e7d6908
=> FCBHDBP-218 v2_backward_compat: library/volume should process dam_id as input and return only that damid

app/Http/Controllers/Bible/LibraryController.php, app/Transformers/V2/LibraryVolumeTransformer.php
Added the secondary_file_path property again to populate the audio_zip_path property to the final response.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-225
- Use the next postman URL and the audio_zip_path should be populated.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-cf5eea29-4a3f-423d-9148-bc172079d86d
=> FCBHDBP-225 v2_compate: add audio_zip_path property to library/volume

app/Models/User/Study/Highlight.php, app/Transformers/UserHighlightsTransformer.php
Error - Undefined variable $verse_text'
It has fixed Highlight model to avoid the 500 error when dbp tries to pull the FilesetInfo property. Overall, the problem is related when dbp is trying to pull a highlights that belongs to a bible and the bible does not have filesets of text_plain type. Then in the Highlight model assumes that the bible has filesets of text_plain type as you can see in the next line:
https://github.com/faithcomesbyhearing/dbp/blob/d54139d8aefb88783c89e009d48f6c698d81682f/app/Models/User/Study/Highlight.php#L183
We can also see the issue when we try to create a Highlight for the bible: ENGNKJV
https://fullstacklabs.atlassian.net/browse/FCBHDBP-227
Try to create a Highlight for ENGNKJV bible
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06 …
=> FCBHDBP-227 500 error - Undefined variable $verse_text'

app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Wiki/CountriesController.php, app/Http/Controllers/Wiki/LanguagesController.php
Languages / search doesn't decode encoded characters, resulting in lock timeout
It has added the feature to remove the control characters for the languages, bibles and countries search endpoint when they set the cache parameters.
It also fixed the ticket 230:
- https://fullstacklabs.atlassian.net/browse/FCBHDBP-230
https://fullstacklabs.atlassian.net/browse/FCBHDBP-229
- Languages search with encoded characters
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-ba22c1e3-162c-4ad5-b06e-cd0bb279bd11
- Bibles search with encoded characters
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-79e19524-4896-4922-8dc8-6b68a88e5c47
- Countries search with encoded …
=> FCBHDBP-229 languages / search doesn't decode encoded characters, resulting in lock timeout

app/Http/Controllers/Wiki/LanguagesController.php, app/Models/Language/Language.php
hardening: shave response time off the tests in Example Workflow that occasionally fail due to excessive response time
It has updated a fix because the language_translations is not filtering the records according to the  highest priority so, it was searching by language_translations records with low priority and high priority. I have tested it with the language endpoint for one letter and for each page.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-219
- Language search (one letter)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-323c258d-e452-4737-a05e-98dd3940b6ea
=> FCBHDBP-219 hotfix - hardening: shave response time off the tests in Example Workflow that occasionally fail due to excessive response time

app/Helpers/Helpers.php, app/Http/Controllers/Bible/BooksControllerV2.php
It has refactored the getTestamentString method to extract the correct pivot word from the Testament id.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-234
- Test the next postman URL and the tests should not fail
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-45091908-694d-4e1e-8404-b5233e6964c8
=> FCBHDBP-234 v2_compat: library book does not account for seven character DAMID

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Traits/CallsBucketsTrait.php
Improve performance for endpoints that use signedUrl method
It is a child of the ticket FCBHDBP-219 and it has been created to improve the performance for the signedUrl method because the AWS authorization is likely the bottleneck. It has created a new method to sign an url but the cloudFrontClient is passed by parameter to avoid the external call to AWS for each signing request.
@bradflood Check this PR to validate if it is ok related with the last email that you sent me.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-219
https://fullstacklabs.atlassian.net/browse/FCBHDBP-232
- I have tested the change with the next endpoint and the response time is around 1.3 seg as you can see in the next screenshot.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d …
=> FCBHDBP-232 Improve performance for endpoints that use signedUrl method

app/Helpers/Helpers.php, app/Http/Controllers/Bible/TextControllerV2.php, app/Models/Bible/BibleFileset.php, routes/apiV2.php
It has created the search action to TextControllerV2. Also, It has added the feature to filter by testament according to the dam_id parameter.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-235
- The tests for this postman url should not fail.
[](https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-0622b741-a38d-4c9f-814a-0ae2375f1b4e)
=> FCBHDBP-235 v2_compat: text search does not account for seven character DAMID

app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Wiki/CountriesController.php, app/Http/Controllers/Wiki/LanguagesController.php
Hotfix to avoid that the fulltext searching run the query with an empty text because the search text is a special character e.g. '+'.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-237
- Language search
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-8286dc90-99b6-4710-b3d3-c36b5fd97331
- Bibles search
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-018294a1-9804-4d1d-bcd7-4eb2db8e76f8
- Country search
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-6b8d827d-3bf3-48ee-a2eb-e027ab0b9218
=> FCBHDBP-237 Avoid that languages search endpoint run query if search text is only + character

app/Http/Controllers/User/UsersController.php, app/Transformers/BibleTransformer.php
It has fixed two error displayed in NewRelic. The first is related with the endpoint to log in and the second is defensive code for the BibleTransformer class.
- First error
```bash
/v4_bible.one
ErrorExceptionException 'ErrorException' with message 'Trying to access array offset on value of type null' in /var/app/current/app/Transformers/BibleTransformer.php:254
```
- Second error
```bash
/v4_internal_user.login
ErrorExceptionException 'ErrorException' with message 'Undefined variable $user' in /var/app/current/app/Http/Controllers/User/UsersController.php:206
```
https://fullstacklabs.atlassian.net/browse/FCBHDBP-238
- The next postman should render the testament parameter for each book.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d …
=> FCBHDBP-238 Solve two error that newrelic is displaying

app/Traits/AccessControlAPI.php
the `bulkAccessControl` method has been updated to improve the AccessGroupKey query. It has switched join order and it has set the `access_group_api_keys` as first join and after it has added the join that to `access_group_filesets`.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-202
Run the group: [M] Bulk requests
=> FCBHDBP-202 optimize bulk access control

app/Http/Controllers/Bible/TextControllerV2.php, app/Models/Bible/BibleVerse.php
It has added the testament filter to `VernacularMetaData` method that belongs to `BibleVerse` model. The goal is to make sure that the books belong to specific testament when the filter is set.
The next is a example about the updated query.
```sql
SELECT count(*) AS aggregate
FROM `bible_verses` INNER JOIN `dbp`.`numeral_system_glyphs` AS `glyph_chapter`
ON `bible_verses`.`chapter` = `glyph_chapter`.`VALUE` and `glyph_chapter`.`numeral_system_id` = 'western-arabic' 
INNER JOIN `dbp`.`numeral_system_glyphs` AS `glyph_start`
ON `bible_verses`.`verse_start` = `glyph_start`.`VALUE` and `glyph_start`.`numeral_system_id` = 'western-arabic'
INNER JOIN `dbp`.`numeral_system_glyphs` AS `glyph_end`
ON `bible_verses`.`verse_end` = `glyph_end`.`VALUE` and `glyph_end`.`numeral_system_id` = …
```
=> FCBHDBP-242 v2_backward_compat: text search does not filter on testament

app/Http/Controllers/Bible/LibraryController.php
It has fixed the version action for the Library Controller. It has added the feature to clean the special character to set the cache keys.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-243
- The next postman URL should not return error.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-546d2f44-9c45-4a8b-8ef1-327578b79302
=> FCBHDBP-243 v2_compat: 500 error on v2_library_version

app/Http/Controllers/Wiki/LanguageControllerV2.php
It has fixed the countryLang action for the Language Controller V2. It has added the feature to clean the special characters to set the cache keys
https://fullstacklabs.atlassian.net/browse/FCBHDBP-245
- The next postman URL should not return error.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-65b6830a-f413-4e57-802e-ff8373a9c4ee
=> FCBHDBP-245 v2_compat: 500 error in countrylang

app/Http/Controllers/Bible/BiblesController.php
The method to know if the chapter action should be compatible with bible.is or gideons has changed. For now on, it will validate if the key belongs to bible.is or gideons to have access to this action. If the user key doesn't allow to bible.is or gideons it will return a 404 message.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-246
- The next postman URL should return 404
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-05258ed5-7797-4cea-ad5e-fcfbf77e9147
- Bible.is success endpoint
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-89017364-bf03-4664-a314-a311bad52269
- Gideons success endpoint …
=> FCBHDBP-246 Adjust check for backward compatibility mode on chapter detail

app/Http/Controllers/Bible/BooksControllerV2.php, app/Models/Bible/Book.php
It has updated the book action and added the testament to the damid parameter when it is only a six characters.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-247
- The postman test for this endpoint should not return error
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-44183544-5641-4252-ae54-1d89b3343d21
=> FCBHDBP-247 v2_compat: library book should return testament in damid when input damid is six characters

app/Http/Controllers/Bible/LibraryController.php
It has modified the `volume` and `version` actions for the `LibraryController`. The goal is to update the filter by code and version_code to make sure that it includes the '%' wildcards on each side of the given code value.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-248
- library version doesn't recognize version code
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-0a80fa31-6342-401e-bcf2-b0d50c78f6bc
- library volume doesn't recognize version code
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-acae1b0b-9acc-484e-bab5-2cac5b4553b4
=> FCBHDBP-248 v2_compat: library version and library volume do not recognize all versions

app/Http/Controllers/Bible/LibraryController.php, app/Models/Bible/BibleFileset.php, app/Transformers/V2/LibraryVolumeTransformer.php
The volume action was updated to support to fetch all records for the dbp version 2. The main goal was to increase the queries to improve the action.
This PR also included the solution for the ticket FCBHDBP-218.
- FCBHDBP-215
https://fullstacklabs.atlassian.net/browse/FCBHDBP-215
- FCBHDBP-218
https://fullstacklabs.atlassian.net/browse/FCBHDBP-218
- Postman endpoint to test to fetch all records
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-a456764c-7135-4405-bba8-ac5d3e7d6908
- Postman endpoint to test to fetch a only record by dam_id
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-cf5eea29-4a3f-423d-9148-bc172079d86d
- Postman endpoint to test …
=> FCBHDBP-215 v2_compat: library/volume should return everything if language_code is not provided

app/Http/Controllers/Bible/LibraryController.php, app/Transformers/V2/LibraryVolumeTransformer.php
It has fixed a issues: I had a rebase conflict and the audio_zip_path had the old pattern. And I had not considered the case for the volume action where the language_id parameter is a value similar to ZZZZ so, it is not a language but the query was returning all records similar when there not filters.
Run [M] v2_compat / Priority Group 1 / library volume
=> FCBHDBP  [M] v2_compat / Priority Group 1 / library volume - hotfix

app/Http/Controllers/Bible/TextControllerV2.php, app/Transformers/TextTransformer.php
* Add validation needed for testament in text transformer v2
* All the data was already getting collected by the sql query, but the dam_id was incorrect
[FCBHDBP-235](https://fullstacklabs.atlassian.net/browse/FCBHDBP-235) 
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-61308e9a-4854-4178-b991-89a1b62433ba
=> FCBHDBP-235 add support for text search on 6 char dam id

app/Http/Controllers/Bible/BibleFilesetsDownloadController.php, app/Traits/AccessControlAPI.php, app/Transformers/BibleFileSetsDownloadTransFormer.php
It has change the index action response and It has renamed the filesetid column to fileset_id. It has included the key into the cache parameters for the index action.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-191
- Execute download endpoint using runner
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-b17ae5d8-bb92-471c-8f72-9dabc5896fad
=> FCBHDBP-191-v2 Add download endpoint for access to 18x and 19x content

app/Http/Controllers/Bible/LibraryController.php
It has fixed the endpoint version and the filter by name.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-261
- The next postman URL should not return 500 code error
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-97570fc1-c810-45b4-b18d-2354a7fe76fa
=> FCBHDBP-261 v2_compat: library version with no filter should return all versions

app/Http/Controllers/Bible/LibraryController.php, app/Http/Controllers/Wiki/LanguageControllerV2.php, app/Http/Controllers/Wiki/NumbersController.php, app/Models/Language/Alphabet.php, app/Models/Language/AlphabetNumeralSystem.php, app/Models/Language/Language.php, app/Transformers/V2/LibraryCatalog/LanguageListingTransformer.php
It has added the support to include the old languages and current languages for the next endpoints:
- library/language 
- library/volume
- library/volumelanguage
- library/volumelanguagefamily
- country/countrylang
- library/numbers
https://fullstacklabs.atlassian.net/browse/FCBHDBP-253
Execute the support dbp2 language codes group of test
=> FCBHDBP-253 v2_compat: recognize v2 language codes not in DBP4

app/Http/Controllers/ApiKey/DashboardController.php, app/Http/Controllers/Bible/BooksControllerV2.php, app/Http/Controllers/User/HighlightsController.php, app/Http/Controllers/User/PasswordsController.php, app/Http/Controllers/User/UsersController.php, app/Transformers/V2/CountryLanguageTransformer.php
It has added fixes for 5 newrelic issues reported for dbp v4.
The next issues was handling in this ticket:
- `Exception 'InvalidArgumentException' with message 'Order direction must be "asc" or "desc".' in /var/app/current/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1984`
- `Exception 'ErrorException' with message 'Undefined array key "language_v2"' in /var/app/current/app/Transformers/V2/CountryLanguageTransformer.php:44`
- `Exception 'ErrorException' with message 'Attempt to read property "id" on null' in /var/app/current/app/Http/Controllers/ApiKey/DashboardController.php:230`
- `Exception 'ErrorException' with message 'Undefined array key "GEN"' in /var/app/current/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1595`
- `Exception 'Error' with …
=> FCBHDBP-260 fix batch of errors found in NewRelic

app/Http/Controllers/Bible/LibraryController.php, app/Models/Bible/Version.php, app/Transformers/V2/LibraryVolumeTransformer.php, database/migrations/2021_12_20_170429_create_version_v2.php, database/migrations/2021_12_20_173946_create_version_v2_fulltext_index.php
It has created a new entity called version. This new entity will be used into the version action for the Library Controller. The current implementation is wrong.
We need to create a full text index for the columns name and english_name. We need to execute the next migration into the server (prod and dev).
```bash
php artisan migrate --path=/database/migrations/2021_12_20_173946_create_version_v2_fulltext_index.php
```
https://fullstacklabs.atlassian.net/browse/FCBHDBP-263
- The next postman test should not return error.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-f9e0b9da-bd56-47f2-a225-ee729e5c79c4
=> FCBHDBP-263 v2_compat: library / version returns incorrect results

app/Http/Controllers/Wiki/LanguageControllerV2.php
It has added the user_key to the cache parameters to the `volumeLanguageFamily` endpoint. You can re-create this issue in prod.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-257
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-da0f2aac-99bd-4700-9066-00c07e098571
=> FCBHDBP-257 v2_compat: library / volumelanguagefamily returns nothing

app/Http/Controllers/Wiki/LanguagesController.php, app/Models/Language/Language.php
added the media and set_type_code filter to the languages search endpoint. It has added the media filter to the language search endpoint. Also, **It has replaced some raw queries to use the query builder.**
https://fullstacklabs.atlassian.net/browse/FCBHDBP-266
- Execute the next postman URL: languages search with filter set_type_code video_drama by name
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-b063e093-a95c-493a-b3b5-20ea298bb49d
- Execute the next postman URL: languages search with filter media video
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-ed2f8c3a-d557-4ad2-b268-2615fd313a9c
- Execute the next postman URL: languages search with …
=> FCBHDBP-266 Add feature to filter languages search by  bible_fileset media type (audio/video)

app/Http/Controllers/Bible/AudioControllerV2.php, config/services.php
It has updated the audio/location endpoint. It will return CDN locations instead of S3 locations.
We need to update the .env file with the next value:
```env
.
.
CDN_SERVER_V2=cloud.faithcomesbyhearing.com
.
``` 
https://fullstacklabs.atlassian.net/browse/FCBHDBP-269
- The next postman URL should pass the tests:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-222b1fb0-9d1a-42bc-897c-f9c814be4e17
=> FCBHDBP-269 v2_compat: modify /audio/location to return CDN reference instead of S3 reference

app/Http/Controllers/Bible/StreamController.php, app/Traits/CallsBucketsTrait.php
It has improved the `transportStream` action that belongs to the `StreamController`. It has rearranged the logic to find the `fileset`. Also, It has removed the `signedUrl` method from the loop and It added the `signedUrlUsingClient` method which is called with the authenticated client as parameter.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-256
- Execute the next postman URL and the time response should be around 1 second.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-e7b7585d-d483-4523-bdc1-a0d8c8ba0f4e
=> FCBHDBP-256 shave response time on v4_media_stream_ts

app/Http/Controllers/Wiki/LanguagesController.php
It added a fix to the language search endpoint. The new query parameter to filter the languages records by media type (video or audio) should be part of the cache to avoid conflict when the parameter is not used.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-266
- Return an empty result - languages search with filter media video
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-32408a48-643e-4150-aa43-b601d49dbf26
- Return one result - languages search **without** filter media video
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-23bf10b0-e094-417d-b20b-144e6d323bb6
=> FCBHDBP-266 Add feature to filter languages search by  bible_fileset media type (audio/video) hotfix

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Plan/Plan.php, app/Models/Plan/PlanDay.php, app/Models/Plan/PlanDayComplete.php, app/Models/Plan/UserPlan.php, app/Models/Playlist/PlaylistItemsComplete.php, app/Transformers/PlanTransformer.php
The reset action from `PlansController` has been refactored It has added two queries to remove the plan days completed and playlist completed records and it has improved the performance. It has also changed the response of endpoint and it won't return the entire plan object.
Furthermore,  It has done a refactor for the `getPlan` method from `PlansController` and It has added the logic into the `planDay` model to avoid to do a query to compute the completed attribute if the value is set before
https://fullstacklabs.atlassian.net/browse/FCBHDBP-291
- You can execute the next postman folder to simulate the flow to complete an entire plan and after to reset it.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-b8f88bba-bf61-44 …
=> FCBHDBP-291 optimize plans/reset

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Bible/Book.php, app/Models/Plan/Plan.php, app/Models/Plan/PlanDay.php, app/Models/Plan/UserPlan.php, app/Models/Playlist/Playlist.php, app/Models/Playlist/PlaylistItems.php, app/Transformers/PlanDayPlaylistItemsTransformer.php
It has done a refactor to the query to fetch the entire plan object. It has added the feature to fetch each relation a single query to avoid to do a query for each record. It has added the feature to know with a single query if a playlist item has been completed.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-272
- Create a plan
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-2b2dc760-9124-43c8-b904-77d02df1d013
- Start a plan
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-30ac0b9d-13fb-4f4f-9f5a-22f8d8fc869f
- Stop a plan and it should take more than 2 seg
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0- …
=> FCBHDBP-272 optimize v4_internal_plans.stop

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Plan/PlanDay.php, app/Models/Playlist/Playlist.php, app/Models/Playlist/PlaylistItems.php, app/Models/Playlist/PlaylistItemsComplete.php
It has done a refactor to improve the `completeDay` action. It has changed the methods: complete and `uncomplete` to avoid executing a insert query for each playlist item that belongs to a Plan Day. So, it will execute a single insert query to complete all playlist items for a specific day.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-292
- Execute the folder fixture for plan setup and the last test about the fixture.7 should pass.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-b7212767-bd07-47d2-9c36-528fb2e3fa55
- After execute the above postman URL should execute the next URL to uncomplete the Plan Day.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request …
=> FCBHDBP-292 optimize plan days complete

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php, app/Transformers/PlanDayPlaylistItemsTransformer.php
Fix an issue related to method to getVerses by playlist.
You can see the issue into newrelic board or with the next link:
https://one.newrelic.com/launcher/nr1-core.launcher?platform[accountId]=2670226&platform[timeRange][duration]=10800000&pane=eyJuZXJkbGV0SWQiOiJlcnJvcnMtdWkub3ZlcnZpZXciLCJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJzaG93IiwicHJpbWFyeUZhY2V0IjoiZXJyb3IuY2xhc3MiLCJ0cmFjZUlkIjoiNzI4ODYzMDMtN2Q1YS0xMWVjLThjMjAtMDI0MmFjMTEwMDA5XzBfODAzOSIsImVudGl0eUd1aWQiOiJNalkzTURJeU5ueEJVRTE4UVZCUVRFbERRVlJKVDA1OE5qa3dNVE14TkRrMCJ9&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5R3VpZCI6Ik1qWTNNREl5Tm54QlVFMThRVkJRVEVsRFFWUkpUMDU4Tmprd01UTXhORGswIiwic2VsZWN0ZWROZXJkbGV0Ijp7Im5lcmRsZXRJZCI6ImVycm9ycy11aS5vdmVydmlldyJ9fQ==&state=e6e50fb7-c …
=> FCBHDBP-293 Fix an issue related to method to get Verses

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Plan/Plan.php, app/Models/Playlist/Playlist.php, app/Models/Playlist/PlaylistItems.php, app/Transformers/PlanDayPlaylistItemsTransformer.php, app/Transformers/PlanTransformerBase.php, app/Transformers/PlanTranslateTransformer.php, app/Transformers/PlaylistTransformer.php, database/migrations/2022_01_26_054449_add_index_plan_id_user_playlists.php
It has added a refactor for the endpoint to translate a plan. Also, Fix the PlaylistItems when the fileset is empty. Added the feature to insert a batch of playlist records and playlist items records.
I recommend to create a index for the `plan_id` column of the `user_playlists` entity. This PR has a migration to create the index. 
https://fullstacklabs.atlassian.net/browse/FCBHDBP-149
- Translate a the plan: Bible in a year to BENBBS 
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-1b0c03bd-7477-46f9-b28d-e56b4395a4ea
- Translate a the plan: Bible in a year to SPNSEV 
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-fea3c2d5-a970-4774-8cd5-0940ad49e1 …
=> FCBHDBP-149 optimize plan.translate

app/Http/Controllers/Plan/PlansController.php, app/Transformers/PlanBasicTransformer.php
It has changed the response for the plans.stop endpoint. For now on, It will only return the basic data of the plan that has been unlinked from user.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-305
- Execute the next postman URL
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-282d5a2e-b28d-4e4b-b34d-b962ee7bdd1c
=> FCBHDBP-305 Update response for endpoint to stop a plan

app/Http/Controllers/Playlist/PlaylistsController.php
It has fixed the playlists.show action to avoid to do aditional sql queries to pull the bible_filesets records.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-149
- Execute the next postman URL
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-24035c11-fdb7-4c83-a652-b8de3c8a7ab3
- Execute the folder: bibleis with user session
=> FCBHDBP-149 fixed the playlists.show action

app/Console/Commands/TranslatePlan.php, app/Models/Playlist/PlaylistItems.php
It has removed the method to calculate the Duration value for each playlist item for the Translate Plan command. The above because there is no need to do more than is done in the web transaction to translate a plan.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-278
```bash
php artisan translate:plan 209 BENBBS
```
=> FCBHDBP-278 fix artisan command translate:plan

app/Http/Controllers/Plan/PlansController.php, app/Models/Plan/Plan.php, app/Models/Playlist/Playlist.php
Hotfix. It has added the feature to accept a null value as response for the methods to get a plan or playlist when the ID does not exist or the plan/playlist has been removed.
- Execute the postman folder: bibleis with user session
=> FCBHDBP Hotfix. Error to return a null method to get a plan/playlist

app/Console/Commands/TranslatePlan.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Services/Plans/PlanService.php, app/Services/Plans/PlaylistService.php
It has added a refactor to improve the methods to calculate the duration and the amount of verses for each playlist item. It has created a single sql query to avoid running a sql query for each playlist item.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-313
- Execute the translate method from sever through shell command
```bash
php artisan translate:plan 209 BENBBS
```
- I have tested it from local environment and the next was the result. It is taking around 1 second to translate the plan 209 to BENBBS
```bash
**************************************************************************
*     Translating plan Bible in a Year starting: 2022-02-11 21:19:59     *
**************************************************************************
Translating plan to bible BENBBS started 2022-02-11 …
```
=> FCBHDBP-313 Improve performance for the methods to calculate the duration and verses for playlistItems

app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Bible/Bible.php
It has decrease the sql query response time to pull the bibles that have a bible_file_timestamps record attached.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-297
- Execute the next postman URL
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-2d51eef3-8ae8-47e5-adf2-d00fde945f62
- The old sql queries are taking around 870ms in my local environment as you can see in the next screenshot
- Now, sql queries are taking around 570ms in my local environment and it has decreased around 300ms as you can see in the next screenshot
=> FCBHDBP-297 optimize bibles filter on audio_timing by shaving 20% off response time

app/Http/Controllers/Wiki/LanguagesController.php, app/Models/Language/Language.php
It has added to the languages endpoint the feature to sort by default by the country_population field descending.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-325
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-93d594d1-39af-4d49-8ed7-b1781f52ed2a
=> FCBHDBP-325 Update languages endpoint to sort by default by country_population virtual field

app/Http/Controllers/Bible/BibleFilesetsDownloadController.php
It has added the parameters: type and limit as cache keys for the endpoint to download a fileset by ID.
Currently, the download endpoint is not considering the parameters: type and limit as cache keys. So, it is not working well when we need to filter by type or we need to change the limit value.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-334
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-49822901-3c33-40e1-b4b4-1200c7c35f2d
=> FCBHDBP-334 Add the type and limit parameters as cache keys for the download endpoint

app/Models/Bible/BibleFileset.php, app/Traits/BibleFileSetsTrait.php
It has added the constraint to handle the `TEXT_USX` type when user tries to download a fileset and it has fixed the issue related with the endpoint to download the fileset and the `usx` type.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-335
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-8c747e11-8ae5-4014-afaf-284e37d24861
The above postman test has been updated because the book name for the MAT book id is: "SAN MATEO" as you can see in the next block
```javascript
pm.test("Matthew 1 properties", function () {
const target = jsonData.find (m => m.book_id === "MAT");
pm.expect(target.book_id).to.eql("MAT");
pm.expect(target.book_name).to.eql("SAN MATEO"); …
```
=> FCBHDBP-335 download of usx fileset returns a playlist, which is incorrect

app/Models/User/AccessGroupKey.php, app/Traits/AccessControlAPI.php
It added a feature to skip only for the bible.is key the constraint that validates the access groups 19x for the API key.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-353
- Run all postman URL in the folder (bible is API key)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-dd4eb082-6467-4b3f-83d7-00316604c6b9
- Run all postman URL in the folder (other API key)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-1ff774f6-86d7-480b-a672-539b30beb6e6
=> FCBHDBP-353 modify download endpoint for bibleis key - use access groups for key instead of for 19x

app/Http/Controllers/APIController.php
It has added the feature to remove the special character: `%` from the search text parameter. The search text parameter is used by the endpoints to search languages, countries and bibles.
This change should also fix the tickets [DBP-355](https://fullstacklabs.atlassian.net/browse/FCBHDBP-355) and [DBP-356](https://fullstacklabs.atlassian.net/browse/FCBHDBP-356)
https://fullstacklabs.atlassian.net/browse/FCBHDBP-354
- Run each one postman URL in the `Miscellaneous / Sentinels` dev folder and they should pass
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-2369df70-b9a7-41c5-baa1-98b8ffe10969
- Run [M] Miscellaneous / Sentinels folder
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0- …
=> FCBHDBP-354 500 error - languages search with special character

app/Http/Controllers/Bible/BibleFilesetsDownloadController.php, app/Models/Bible/BibleFilesetCopyrightRole.php, app/Models/Bible/BibleFilesetLookup.php, app/Models/Language/Language.php, app/Models/User/Key.php
It has done a refactor to improve the performance the list download endpoint. It has replaced the `bible_fileset_lookup` view with the entities themselves. Also, it has removed the `orderBy` clause because it affects the performance.
About the performance, in my local environment the response time is around 400ms with these changes. Before these changes the response time was about around 800ms.
The `orderBy` clause has been removed because it is affecting the performance. 
https://fullstacklabs.atlassian.net/browse/FCBHDBP-342
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-c8406567-7b03-4070-91a6-46c645c82377
- Time response related with the sql query with NEW changes.
- Time response …
=> FCBHDBP-342 hardening: optimize /v4_bible_filesets_download.list

app/Transformers/PlanTransformerBase.php, app/Transformers/PlanTranslateTransformer.php
It has done a refactor to removed the metadata property from plan payload when a plan is translateFCBHDBP-340 It has removed the sub-property: metadata from the `TranslationData` property. The `TranslationData` property is in the response that is returned the endpoint to translate a plan. The above is related to decrease the processing for this endpoint and the size of payload.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-340
We should run the next postman tests and they should passed:
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-23e94960-5e98-4689-af89-a38870a0e102
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-4ced5b59-53b1-442b-9161- …
=> FCBHDBP-340 Remove the metada property from the playlist item for the plan translate response

app/Models/Bible/BibleFileTag.php, app/Traits/BibleFileSetsTrait.php
It has updated the BibleFilesetsTraits.php to serve the video thumbnails according to bible_file_tags entity. But, If the bible_file_tag thumbnail is not found, it should use the old way.
This PR is related with ETL PR: 
- https://github.com/faithcomesbyhearing/dbp-etl/pull/47
https://fullstacklabs.atlassian.net/browse/FCBHDBP-375
- You should run the next postman test and it should pass.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-84bb4206-a7d1-46c7-9d34-edade69cedf6
- Also, you can see an example if you paste the next URL on you browser:
https://content.cdn.dbp-prod.dbp4.org/video/thumbnails/gf_jhn_01_02.jpg?x-amz-transaction=2264263&Expires=1652892730&Signature=f7gOt7WtDNPs2StfWmJjSVrblpfVn1JXoxRCf~0J26beVpuX0cML …
=> FCBHDBP-375 serve video thumbnails based on bible_file_tags

app/Http/Controllers/Bible/BiblesController.php, app/Models/Bible/BibleBook.php
It has changed the way to sort the book records. For now on, If the book_seq field is populated it will sort by book_seq field but if it does not, the book records will sort by <versification>_order column. The sorting process will be performed from database.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-377
- You can run the next 2 postman test and they should pass:
1. ENGESV bible and the bible_books records have populated the field book_seq.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-79eef8c9-3e44-471e-a614-40da8783d368
1. AA1WBT bible and the bible_books records DOES NOT have populated the field book_seq.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/ …
=> FCBHDBP-377 return books in order dictated by bible, not necessarily protestant

app/Traits/BibleFileSetsTrait.php
It has fixed the `v4_filesets` bulk endpoint. When we try to use the limit value we need to validate that it will use the collection object rather a `LengthAwarePaginator` instance.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-414
- I have created a postman test to re-create the issue.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-13abc396-05e1-43e1-be19-644366fded85
=> FCBHDBP-414 DBP: 500 error in bulk endpoint

renovate.json
It has replaced the comment property by the description property to avoid warning messages of renovate.
- You can see in the renovate log that we are not able to use the comment property:
=> FCBHDBP renovate fix

app/Http/Controllers/Plan/PlansController.php, app/Models/Plan/Plan.php, app/Transformers/PlanDayPlaylistItemsTransformer.php
It has added the new property: total_users to the endpoint to pull the plan detail (`v4_internal_plans.show`). It will count all users that have started a specific plan and the sum will be returned in the property: total_users
https://fullstacklabs.atlassian.net/browse/FCBHDBP-420
- You can test this new feature if you run the following postman test:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-b64f3025-141d-4017-bf57-e5bf62128022
=> FCBHDBP-420 Plan 2.0 (Function): Follower Count (API)

app/Models/Language/Language.php, docker-compose.yml
It has updated the endpoint:`/languages/search/` to be able to search by alternative names as well. We have removed the constraint that was avoiding to search by the alternate name or language translations. We had the following constraint: 
```php
->whereRaw('lang_trans.language_source_id = lang_trans.language_translation_id') 
```
the above when we were trying to match the search text with the language translations records.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-427
- All of tests inside following folder should pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-f7f37344-fb08-4c92-8bb9-1e1413ccb9a7
=> FCBHDBP-427 alternate name search functionality for Bible.is

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Services/Plans/PlaylistService.php
It has fixed an issue where it wasn't handling the case where the `fileset_id` is empty when an user was trying to store a plyalist item. Also, It has update the playlistController to use the SymfonyResponse constants.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-440
- You should run the next steps:
1. Login with a user
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-041aa795-75e3-4fb8-bb3b-2c1acfbdd22c
2. Create a new plan
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-49b34ca7-e2c0-4e6f-b37e-6c0a85b5e495
3. Add playlist items
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/1251937 …
=> FCHDBP-440 Check issue related to endpoint to store a playlist item

app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php, app/Models/User/Study/Bookmark.php, app/Models/User/Study/Highlight.php, app/Models/User/Study/Note.php, app/Models/User/Study/UserAnnotationTrait.php, app/Transformers/BibleVerseTransformer.php, app/Transformers/PlaylistBookmarksTransformer.php, app/Transformers/PlaylistHighlightsTransformer.php, app/Transformers/PlaylistNotesTransformer.php, app/Transformers/UserBookmarksTransformer.php, app/Transformers/UserHighlightsTransformer.php, app/Transformers/UserNotesTransformer.php, composer.json, composer.lock, routes/api.php
It has created 3 new endpoints to get the user bookmarks, highlights and notes filtering by playlist ID and Book ID.
- `/playlists/:playlist_id/:book_id/notes`
- `/playlists/:playlist_id/:book_id/highlights`
- `/playlists/:playlist_id/:book_id/bookmarks`
I have downgraded `zircote/swagger-php` to the version 3.3.6 because the task to generate the openapi.json file is not working with the last version of  `zircote/swagger-php`.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-454
- We should run all test of the following postman folder and they should pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-3cc08c6e-6640-45c3-bc82-96d2d51162d3
=> FCBHDBP-454 Add user annotations  to the playlist endpoint response.

app/Models/Bible/Bible.php, app/Models/Bible/BibleVerse.php, app/Transformers/BibleVerseTransformer.php, public/openapi.json
It has added a new parameter to the response called: `bible_filesets.` This new parameter will be the filesets records related to the verse filtered by book, chapter and verse number.
It will attach all filesets related to the verse record filter by chapter, book and verse.
The new parameter won't affect the response timing. The endpoints are keeping the respond timing less than 100ms.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-437
- It should pass the following postman test folder:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-47ae182e-c9fa-4fac-a11b-3dfa13519d7c
=> FCBHDBP-437 DBP - Enable "Discover search" and "search My Bible" to find scripture references such as "Romans 2:4"

app/Http/Controllers/Bible/BibleFilesetsDownloadController.php, app/Models/Bible/BibleFileset.php, app/Models/Bible/BibleFilesetLookup.php
I was checking the following issue is related with the to way to lock and block the cache key.
```shell
Exception 'Exception' with message 'Exception when the cache value is null for key 
```
The above has been recreated, I have pushed a fix to solve it and you can see more detail in the PR: #812 .
Furthermore, It has done a refactor to improve the main query for the v4_download_list endpoint. This refactor improved the performance as you can see in the screenshots.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-461
- You should run the following postman test and it should pass.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-5b9e68bd-e763-499b-a7e3-aa969b685f46
- You should execute the [M] Download requests tests …
=> FCBHDBP-461 DBP - cache issue with Gideon bible-download-list

app/Models/Plan/PlanDay.php, app/Models/Plan/UserPlan.php, app/Models/Playlist/PlaylistItemsComplete.php, app/Services/Plans/PlaylistService.php
1. It has fixed an issue related to the endpoint to stop a plan. The stop endpoint was not resetting the plan when it had an only one item completed but, if the Plan had a day completed, all items were reset correctly. 
2. Also, it has fixed an issue related to avoid return a 500 error when user tries to create a playlist with an empty playlist item.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-473
1. You should run the following two postman folders and they should pass. The following postman folders are related to the endpoint to stop a plan.
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-d68ccda0-18f3-44a6-904c-a7250e51860b
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-9 …
=> FCHDBP-473 Endpoint to stop a plan is not resetting plan when it has an only one item completed

app/Helpers/Helpers.php
It has added stock_no attribute to the fileset object temporarily to support older versions of 5fish applications.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-508
- Chapter detail
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-89017364-bf03-4664-a314-a311bad52269
- translate plan 209 SPNSEV
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-fea3c2d5-a970-4774-8cd5-0940ad49e106
- translate playlist BENBBS
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-9c1f544c-37f4-40f5-b467-02e59e685a90
Also, it should pass all postman test of [M] bible.is mobile requests:
- …
=> FCBHDBP-508 Temporarily add stocknum attribute, with no value

app/Http/Controllers/Bible/BiblesController.php, app/Models/Bible/Bible.php, app/Models/Bible/BibleFileset.php
It has added a feature to avoid returning information about the old six character fileset. It has changed `BiblesController@index` and `BiblesController@show` endpoints. This will stop returning information on six character text_plain filesets when the ten character text_plain fileset is available but when there is only six character text_plain it should return it.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-513
- The following postman test should pass. The bible AKEBSS has both six and ten character filesets and the following test should only return the fileset: `AKEBSSN_ET`. BiblesController@index
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-4808bd5b-3d9e-40f5-a5cf-fe50c0f9574a
- Using language ID and …
=> FCBHDBP-513 when two text_plain filesets exist, do not return any information for the six character fileset

app/Http/Controllers/Bible/StreamController.php, app/Traits/BibleFileSetsTrait.php
It has added a constraint to handle the case when the verse_end value is empty into the chapter detail endpoint.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-515
- You should execute the following postman test and it should pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-daa3fa8c-be9a-4ed0-91a1-671e0b6ae6a2
=> FCBHDBP-hotfix enable non-integer verse identifier

app/Traits/BibleFileSetsTrait.php
hotfix it has removed the param: `verse_start_alt` from the method to generate the `v4_media_stream` route.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-518
- We should runt the two following postman tests and they should pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-daa3fa8c-be9a-4ed0-91a1-671e0b6ae6a2
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-85c07444-8f4d-4598-a9bd-eb61ca030a4b
=> FCBHDBP-515 hotfix - enable non-integer verse identifier

app/Models/Playlist/PlaylistItems.php
It has added the explicit method to order by verse_sequence when a playlist_item fetches the verse_text records.
- We should execute the following postman folder and it should pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-c03d49d4-8b41-4b33-ade4-3774de944c09
=> FCBHDBP enable non-integer verse identifier

app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Playlist/PlaylistItems.php, app/Models/User/Study/Note.php
Fixed issue related to the endpoint to get a playlist  and a specific logic in  DBP where it is comparing two verse_start values as if they were integers values. So, For some cases the verse_text value is not being returned but the audio does.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-530
- We should run the following 2 postman test and they have passed:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-9ee78ea0-d603-49cb-a21f-38b28ef824d5
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-0ed7d9a7-40dc-4188-a20a-11cde7760b87
- Also, we should run [M] bible.is mobile request and it should pass
=> FCBHDBP-530 Issue - verse playback for playlist content 

app/Http/Controllers/Bible/Traits/TextControllerTrait.php, app/Http/Controllers/User/HighlightsController.php, app/Models/User/Study/Highlight.php, app/Traits/BibleFileSetsTrait.php
It has fixed the queries that were comparing the verse_start and verse_end columns as string values.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-532
@bradflood if the postman tests: `v2 get verses` and `v4 get verses` pass, I think that we could add them to the [M] postman test.
We should execute the following 3 postman tests and they should pass:
- v2 get verses
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-b99dfe85-f2fa-4314-a61a-e669f9d7ced2
- v4 get verses
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-5877742e-e8a9-4e34-8aee-64cdb7894e86
- anotations - This a folder and so, we need to use a runner …
=> FCBHDBP-532 Hotfix. API - fix bug in v2 API regarding verse ordering

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Traits/BibleFileSetsTrait.php
The endpoint for fetching verses by book and chapter now requires the chapter parameters to be an integer value, with a validation added to enforce this.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-526
We should execute the following postman tests and they should pass:
- Case 1: chapter value as a string value
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-2d6ce1d5-774a-4333-9e8c-e140072f1125
- Case 2: chapter value as a integer value but cache key with special characters
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-02791711-f08d-433a-88c0-45232fb3ad56
- Case 3: chapter value, verse_start and verse_end as a string values …
=> FCBHDBP-526 DBP: filter out bad character in bible_fileset_show request

app/Http/Controllers/Playlist/PlaylistsController.php
The logic for processing HLS audio has been improved by adding a mechanism to handle cases where a verse does not have a corresponding record in the `bible_file_timestamps` and `bible_file_stream_bytes` tables. Previously, the assumption was that all verses had a related record stored in these tables, resulting in the DBP fetching all records about the stream bytes and retrieving the stream record associated with the verse based on its position in the array. However, this logic could fail when the stream record is not stored in the database, potentially returning an incorrect record due to reliance on the array position alone.
To solve completely this issue we need to do the following changes into database:
1. Create a `bible_file_timestamps` record related `verse_start=13` and the …
=> FCBHDBP-535 Issue with fileset ENGGIDN2SA book= 2TI chapter=2 verse=12

app/Http/Controllers/Playlist/PlaylistsController.php
We need to ensure that no computations are performed when the verse_end is null for normal case.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-535
- The following all test should pass when we update the bible_file_timestamps record id=3350395. But, 3 postman test should failed if we have not update the database.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-ac478133-4472-4554-8949-f0a68733d19f
=> FCBHDBP-535 Hotfix - Issue with fileset ENGGIDN2SA book= 2TI chapter=2 verse=12

app/Http/Controllers/Playlist/PlaylistsController.php
It has added a constraint to validate the stream object as it may be an empty object that has been included to imitate a transport stream related to timestamp with verse_start = 0.
I discovered that the timestamp record with ID 3350836 references to a range of verse audios from verse 1 to verse 5, however, the values are currently incorrect. Based on this finding, we should update the timestamp record executing the following sql statement:
```sql
UPDATE dbp_2022_03_18.bible_file_timestamps
SET verse_start='1',verse_end='5' -- prior: verse_start='5', verse_end=NULL
WHERE id=3350836;
```
https://fullstacklabs.atlassian.net/browse/FCBHDBP-542
- We should execute all postman test of the following folder and they should pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a28 …
=> FCBHDBP-542 Error 500 related to the HLS playlist endpoint

app/Http/Controllers/Bible/BibleFileSetsController.php
Add constraint to validate that book_id query parameter must be alphanumeric without accent characters.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-537
- We should run all postman test of the following folder and they should pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-a34a808f-1ee8-4e9b-a80d-1790d76077af
=> FCBHDBP-537 Require book_id in bible-filesets-show

app/Helpers/Helpers.php, app/Traits/AccessControlAPI.php
Add constraint that if the API key belongs to bible.is but the user is not currently logged in, the API will utilize the generic access group list instead.
@bradflood , we have an edge case where: `non-bibleis user but user logged in`,  currently, the API is adding entry into `user_downloads` with userid and fileset, is it ok?
You can test the case using the following postman test:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-eda75d1f-08b4-4426-9447-a6d6e45806bd
https://fullstacklabs.atlassian.net/browse/FCBHDBP-541
We should run the following test and they have to pass.
-  non-bibleis user, content cannot be downloaded
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18b …
=> FCBHDBP-541 Extend the logic to store the user_downloads records to the new download endpoints

app/Http/Controllers/Bible/BibleFilesetsDownloadController.php, app/Traits/AccessControlAPI.php
Add a flag to the cache parameters that indicates whether the user has logged in the above because the access group list can change depending on whether the user is logged in or he is not.
I think that we need to clean cache.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-549
- The all postman test: Tack downloads have to pass
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-4a071b78-47ce-409d-815c-4e7bfeb61cbf
- fileset SPNTLAN2DA - it should return 200 when the api_token (user has logged in) is used.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-1aafaccc-3a6e-440a-8281-96a0a74e28a2
=> FCBHDBP-549 Hotfix - download endpoint and cache using user session

app/Traits/AccessControlAPI.php
Disable the latest change in which we validate whether the API key belongs to bible.is and the user is not currently logged in. Instead of returning the generic access group list, the API would return the bible.is access group list as it did before.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-541
-All the following postman test have to pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-fb2b1824-5f60-4d96-83bd-2648c7bd00c2
=> FCBHDBP-541-hotfix Extend the logic to store the user_downloads records to the new download endpoints

app/Http/Controllers/Wiki/LanguagesController.php
rollback `LanguageController` the feature to validate that bibles have filesets attached. @bradflood It was my bad because the method Language::isContentAvailable validates that a language has at least one bible with filesets attached and so we have found a language with 3 bibles attached but just one bible has filesets attached. So, when DBO should return the bibles we need to make sure that DBP will only return the bibles with  filesets attached.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-548
- We should run the all test of the following folder and they must pass.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-f4001f93-3bac-4831-918c-29e8a7c518ea
=> FCBHDBP-548 hotfix add AccessControl middleware to the countries endpoints

app/Helpers/Helpers.php, app/Http/Controllers/Bible/BibleVersesController.php, app/Http/Controllers/Bible/BiblesController.php, app/Http/Controllers/Bible/LibraryController.php, app/Http/Controllers/Wiki/CountriesController.php, app/Http/Controllers/Wiki/LanguageControllerV2.php, app/Http/Controllers/Wiki/LanguagesController.php, app/Models/User/AccessGroup.php, app/Models/User/AccessGroupKey.php, app/Support/AccessGroupsCollection.php, app/Traits/AccessControlAPI.php
To increase cache hits, we have removed the API key from all DBP cache keys. We now use the access_groups as a single string delimited by commas in the cache parameters. This approach will be effective because many API keys share the same access groups.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-553
We should run the postman tests of the following folder and they have to pass.
- Access control tests:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-7b281e90-36a9-464d-aab0-feac43793bee
=> FCBHDBP-553 remove the api key from from all DBP cache keys.

app/Helpers/Helpers.php, app/Http/Controllers/ApiMetadataController.php, app/Models/Bible/BibleFilesetSize.php, app/Models/Bible/Book.php, routes/api.php
Return only the books associated with the column set_size_code of the fileset. We have added a constraint to validate that the `set_size_code` value in the `bible_fileset` column must be either equal to `C` (COMPLETE) or have the `book_testament` value from the `book` column contained within it. For example, if the `book_testament` value is `NT` and the `set_size_code` value is `NTP`.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-570
- We should execute the following postman test and it have to pass
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-cb709edf-b129-4d3e-83ba-9c29b5eeecf6
=> FCBHDBP-570 Check and Validate endpoint to return the books and chapters for a specific fileset

app/Models/Playlist/PlaylistItems.php
Fix type parameter of method processVersesOnTransportStream.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-577
We should run the following postman test and it have to pass
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-057468b4-8a06-4747-aa91-55261f9d7fe0
=> FCBHDBP-577 Check the method to translate a plan because the value of playlist item duration is not being filled

app/Http/Controllers/Bible/VideoStreamController.php, app/Services/Arclight/ArclightService.php, package-lock.json
Improve the handling of exceptions in concurrent requests when retrieving Jesus films from the Arclight API.
1. Implemented the `stream()` method from HTTP, as it is recommended for [Multiplexing Responses](https://symfony.com/doc/6.0/http_client.html#multiplexing-responses) according to the Symfony documentation.
2. To handle 300-599 status codes on our side when we are using multiplexing responses, we are now passing 'false' as an optional argument to all calls of methods like `getHeaders` and `getContent`.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-569
We should execute the following 3 postman tests and they have to pass.
1. jesus-film LUK/7: https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-775def18-7408-401f- …
=> FCBHDBP-569 Update v4_video_jesus_film_chapters and v4_video_jesus_film_chapter endpoints to catch all http errors from arclight API

app/Http/Controllers/Bible/StreamController.php, app/Http/Controllers/Organization/FilmsController.php, config/services.php
Update CDN url to replace the old `content.cdn.dbp-prod.dbp4.org` and `content.cdn.dbp-vid.dbp4.org` values.
This PR is related with the dbp-web PR:
- https://github.com/faithcomesbyhearing/dbp-web/pull/72
https://fullstacklabs.atlassian.net/browse/FCBHDBP-580
We will need to update some postman test to replace the new CDN URL: `d1gd73roq7kqw6.cloudfront.net`
Run all [M] postman tests and they have to pass.
=> FCBHDBP-579 bibleis-web: invalid CDN request

app/Exceptions/MySQLErrorCode.php, app/Http/Controllers/Plan/PlansController.php, app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Plan/PlanDay.php, app/Models/Plan/UserPlan.php, app/Models/Playlist/PlaylistItems.php, app/Services/Plans/PlanService.php
Prevent continuous storage of duplicate completed days in the `plan_days_completed` and `playlist_items_completed` tables. To accomplish this, we have taken the following steps:
1. Developed an SQL script to clean up data and thereafter, created unique key constraints on `plan_days_completed(user_id, plan_day_id)` and `playlist_items_completed(user_id, playlist_item_id) `:
```sql
-- playlist_items_completed
START TRANSACTION;
DROP TEMPORARY TABLE IF EXISTS playlist_items_completed_temp;
CREATE TEMPORARY TABLE playlist_items_completed_temp AS
SELECT pic.user_id, pic.playlist_item_id, COUNT(pic.user_id)
FROM playlist_items_completed pic
GROUP BY pic.user_id, pic.playlist_item_id 
HAVING COUNT(pic.user_id) > 1;
DELETE playlist_items_completed
FROM playlist_items_completed
INNER JOIN …
```
=> FCBHDBP-589 Plans - Avoid that duplicated records when a day is Completed

app/Http/Controllers/User/UsersController.php, app/Models/Country/Country.php, app/Models/User/Profile.php
The SQL issue about Integrity constraint violation won't happen again because the foreign has been removed. Also, currently, the API DBP has a method to validate if the  country ID is validate when a user profile must be created but I have done a refactor to improve the way it has been implemented.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-494
- Run the following postman test and they have to pass:
1. https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-ed0fe392-9d9e-4a74-9313-61af904a21f8
2. https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-9958d6ad-a89d-4b0a-a769-40f85408e344
=> FCBHDBP-494 API bug: update user country

app/Http/Controllers/Bible/TextController.php, app/Models/User/Annotations.php, app/Models/User/Study/Highlight.php, app/Models/User/Study/UserAnnotationTrait.php, app/Transformers/UserBookmarksTransformer.php
I have fixed the logic to retrieve highlight records, ensuring that the verse text is taken into account when retrieving highlights. Additionally, I have optimized the queries to retrieve bookmarks, highlights, and notes records, reducing the number of queries being invoked.
- Example with the current logic
- Example with the changes of this PR
https://fullstacklabs.atlassian.net/browse/FCBHDBP-590
We can execute the following postman tests and they have to pass:
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-fa5533f5-0559-4712-ab83-b1bbfdd4875e
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-5da2cc82-7248-4fdb-a65a-fc69ceaef9ad
=> FCBHDBP-590 Fix search/library endpoint related to the User Highlights

app/Http/Controllers/Plan/PlansController.php, app/Models/Playlist/Playlist.php, app/Services/Plans/PlanService.php, app/Transformers/PlanDayPlaylistItemsTransformer.php
Update The `GET /plans/:id` endpoint to Add a flag to each plan day within a specific plan to indicate if its associated playlist has any items.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-596
- You should run the following postman test and it has to pass
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-05e22cf4-7a58-4f4e-93d7-541cdeb6e8d3
=> FCBHDBP-596 GET Plan by ID - Update days array to include an empty key

app/Models/Bible/BibleFileset.php, app/Services/Plans/PlanService.php
Refine the plan translation logic to better validate the availability of a specific Bible file for a given book and chapter in a target audio fileset. This enhancement addresses a scenario where a user attempts to translate the 'Psalm a Day' plan into the "Spanish Languaje Actual" Bible (Bible ID: SPNTLA). Although the target Bible has an associated audio fileset (SPNTLAP2DA), this fileset is missing the Bible file for the book "PSA". Interestingly, a relationship does exist between the Bible and the book in the database, but it is only to the plain text fileset.
@bradflood, can you confirm if there's an index created for the `plan_id` column in the `user_playlists` table of the `dbp_users` database? I ask because having this index significantly enhances the performance of the translate …
=> FCBHDBP-591 Specific issue to translate plan from "Psalm a Day" plan to "Spanish Languaje Actual" bible

app/Services/Plans/PlaylistItemService.php
It must ensure that the 'verse_start' and 'verse_end' are not empty in order to accurately calculate the verse count using the start and end limits.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-605
We need to run the following two postman test and they have to pass:
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-5efdb481-2849-4dc9-bc44-0c44fd5f56d6?active-environment=810fd94b-9392-43e2-9f13-943e8d323135
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-e3ffd74c-9afe-47be-a116-2af7b20d832a?active-environment=810fd94b-9392-43e2-9f13-943e8d323135
=> FCBHDBP-605 HotFix - Fix values for verse_start and verses parameter in the translate endpoint

.platform/hooks/prebuild/install_newrelic.sh
Manually install the newrelic php agent from a tarball.  The automated install does not yet work with AL 2023
=> manually install newrelic from tarball

.platform/hooks/prebuild/install_newrelic.sh
Fix for Bug 2018
This change simply changes the newrelic.loglevel from "debug" to "info".
The "debug" level is producing an immense amount of logs, that don't appear to be useful beyhond debugging the php agent itself.
[Bug 2018](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2018)
Once deployed, look at connect to a beanstalk ec2 instance, and tail the /var/log/newrelic/php_agent.log.  You should only see info level and up.
=> Limit newrelic/php_agent.log

.platform/hooks/prebuild/install_php_zip.sh, app/Http/Controllers/Bible/TextController.php, composer.json, composer.lock, public/openapi.json
Add a feature to sort results from the search verses endpoint according to book order. A new query parameter called `sort_by` with the value `book_order` has been added to allow sorting of results based on the book to which each verse belongs. 
Additionally, I have added a script to install the `zip` extension in the build process.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-603
You should run the following postman request and it have to pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-43ee9388-2897-4455-9263-c328b431430f?active-environment=2465063f-c35d-430f-839c-7cbb993d3a47
=> FCBHDBP-603 Add feature to sort the verses according to the books in search endpoint

app/Http/Controllers/Bible/TextController.php
Add the feature to sort the results of the endpoint to search verses by verse_sequence. This feature will only be enabled when the query parameter 'sort_by=book_order'.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-608
You should run the following postman request and it has to pass:
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-43ee9388-2897-4455-9263-c328b431430f?active-environment=810fd94b-9392-43e2-9f13-943e8d323135
=> FCBHDBP-608 Extend the sort feature of the endpoint to search the verse

app/Models/Bible/BibleFileset.php
In production, for text_plain, there is only the six character ENGKJV
in NEWDATA, there is now a ten character ENGKJVN_ET, which is not loaded.
The logic to prefer the ten character text fileset did not consider the possibility that the ten character fileset was not loaded
=> 2136-text-plain-content-loaded-flag

app/Models/Bible/BibleFileset.php
It has added feature to support the new columns: content_loaded and archived.
I can recreate the issue when I create a new record with id = ENGKJVN_ET and content_loaded=true. The problem come about because the current logic does not filter by the content_loaded and archived flags, and it retrieves the first row returned by the database. However, I think the old logic can be removed because it could return incorrect data in the future when the database has content loaded for both types of filesets: six characters and 10 characters. This method is specific and should return the attached information to the given fileset ID, it should not attempt to return a 10-character fileset when the given fileset ID is a six-character fileset. Based on this, I think we can remove this code:
```php …
```
=> Task-2136 API: ENGKJV text plain not returning data

app/Http/Controllers/Playlist/PlaylistsController.php, app/Models/Bible/BibleFileset.php, app/Models/Playlist/PlaylistItems.php, app/Services/Bibles/BibleFilesetService.php, app/Services/Plans/PlaylistService.php
It has improved the logic for retrieving the fileset of the plain text type when the playlist item needs to return the text associated with the audio fileset.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-609
- You should run the postman tests in the following folder and they have to pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-98d4bf15-9922-4a23-a876-2ec50fdd0f77?active-environment=2465063f-c35d-430f-839c-7cbb993d3a47
- You should run the following postman test in dev and it have to pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-b52b3ec5-88b5-40a4-8e32-db43e79cbfe1?active-environment=2465063f-c35d-430f-839c-7cbb993d3a47
=> FCBHDBP-609, The playlist endpoint is not returning the verse text when both the new (10-character) and old (6-character) plain text filesets exist

app/Models/Bible/BibleFileset.php
Fixed the method filesetTypeTextPlainAssociated to reuse the common query when retrieving the plain text fileset associated with an audio fileset.
Run the following postman test
1. Bible ID BULBOB: Return fileset BULBOB (6 character) and BULBOBN_ET (10 character)
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-7d50c3c3-2522-4816-bbd5-054931d4497d?active-environment=810fd94b-9392-43e2-9f13-943e8d323135
2. Bible ID ENGWEB: Don't return ENGWEBN  (6 character)  and Return new filesets: ENGWEBN_ET and ENGWEBO_ET
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-ee20de37-90e3-488a-b68b-412cb6a81f13?active-environment=810fd94b-9392-43e2-9f13-943e8d323135 …
=> FCBHDBP-609 The playlist endpoint is not returning the verse text when both the new (10-character) and old (6-character) plain text filesets exist

composer.json, composer.lock, config/settings.php
updated the 'download_access_group_list' and 'apiKeyAccessGroups' values in settings to support the new access groups created for Blimp.
To update the parameter: `API_KEY_ACCESS_GROUPS` we need to update in the .env file that we have stored in the S3 bucket. The above because in the deploy process dbp pulls env.config from S3. You can see in the following code the instruction that is executed in the build process to copy the .env file from the S3 bucket:
https://github.com/faithcomesbyhearing/dbp/blob/develop/.ebextensions/00_copy_from_s3.config
However, I think that we could remove this parameter (`API_KEY_ACCESS_GROUPS`) from the .env file stored in the S3 bucket and handle it from the default value that we have in the settings file, in a similar way to how we handle the parameters: …
=> Task-2210 Public API: change references to access groups for Blimp

app/Models/Bible/BibleFileset.php, app/Traits/AccessControlAPI.php, composer.json, composer.lock, package-lock.json, package.json
Added logic to include in the access control for a specific fileset and, for a general search, the constraint to validate the mode_id between the fileset and the access group record.
[User Story 2775](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2775): Public API: access control is mode specific
I created the following three Postman tests to check the access group by mode-specific functionality. We need to update the access group for the AKABSG bible in Blimp before running the tests.
- Bibles show ID AKABSG – Exclude the text_plain fileset – Access control for general searching
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-ac228744-e5d8-4a31-a42c-f24584fb78b5?action=share&source=copy …
=> Task-2775 Public API: access control is mode specific

app/Http/Controllers/Bible/BibleFileSetsController.php, app/Http/Controllers/Bible/BiblesController.php
Fixed a cache serialization issue where cached data contains references to the obsolete BibleFilesetCopyright model. The cache key bible_fileset_copyright in BibleFileSetsController.php has been renamed to force regeneration with the current LicenseGrlup model.
[User Story 2938](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2938): Public API: use consolidated license tables
You should run the following 2 postman test and they have to pass:
- Bible copyright
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-af4b3074-1a66-4e07-a6f2-b5fe3b1789d3?action=share&source=copy-link&creator=17122915&active-environment=810fd94b-9392-43e2-9f13-943e8d323135
- Bible Fileset copyright …
=> Task-2920 Hotfix - fix a cache serialization issue
