faithcomesbyhearing/dbp

- app/Http/Controllers/Bible/AudioController.php
- app/Http/Controllers/Bible/BibleEquivalentsController.php
- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Bible/BooksController.php
- app/Http/Controllers/HomeController.php
- app/Http/Controllers/User/Dashboard/BibleFilesetsManagementController.php
- app/Http/Controllers/User/SwaggerDocsController.php
- app/Models/Bible/BibleFileset.php
- app/Models/Organization/Organization.php
- app/Transformers/FileSetTransformer.php
- routes/api.php
- Updated API documentation on Bible endpoints
- /timestamps
- Changed return type to array
- /timestamps/search
- Added audio_fileset_id, audio_asset_id, text_fileset_id, text_asset_id, book_id query parameters
- /bible/equivalents
- Fixed statement when the result count is 0
- /bibles/filesets/{fileset_id} GET
- Removed unused versification parameter
- Added required=true to type parameter
- /bibles/filesets/{fileset_id} PUT
- Added api route
- Added RequestBody
- Updated description and summary
- Updated validateUser function
- /bibles/filesets/{fileset_id}/download
- Added fileset_type parameter
- TODO: Add download functionality
- /bibles/filesets/{fileset_id}/copyright
- Added iso query parameter
- /bibles/filesets/media/types
- /bibles/filesets/{fileset_id}/podcast
- Fixed …
> FCBH-289 API Completeness: Bibles

- app/Http/Controllers/Organization/OAuthProvidersController.php
- app/Http/Controllers/Organization/ProjectsController.php
- app/Http/Controllers/User/AccountsController.php
- app/Http/Controllers/User/PasswordsController.php
- app/Http/Controllers/User/SwaggerDocsController.php
- app/Http/Controllers/User/UsersController.php
- app/Models/User/Account.php
- resources/lang/eng/api.php
- routes/api.php
- Updated API documentation on Users endpoints
- /projects​/{project_id}​/oauth​
- Fixed endpoint path
- Added provider_id parameter
- /projects GET
- /projects POST
- ​Fixed typo
- /projects​/{project_id} GET
- ​/projects​/{project_id} PUT
- ​Added RequestBody
- /projects​/{project_id} DELETE
- /accounts GET
- ​Added api route
- /accounts POST
- ​Added api route
- /accounts​ PUT
- ​Added api route​
- Added setKeysForSaveQuery to Account model in order to delete or update a record
- Removed account_id parameter
- Added provider_id and provider_user_id query parameters
- Updated invalidAccount function
- /accounts​ DELETE
- ​Added api route
- Added setKeysForSaveQuery to Account model in order to delete or update a record
- Removed account_id parameter
- Added provider_id and …
> FCBH-292 API Completeness: Users

- app/Http/Controllers/User/BookmarksController.php
- app/Http/Controllers/User/HighlightsController.php
- app/Http/Controllers/User/NotesController.php
- app/Http/Controllers/User/SwaggerDocsController.php
- app/Models/User/Study/Bookmark.php
- app/Models/User/Study/Highlight.php
- resources/lang/eng/api.php
- Updated API documentation on Annotations endpoints
- /users/{user_id}/bookmarks GET
- Added bible_id, book_id, chapter_id, limit, page query parameters
- Changed wrong filter (from $book_id to $bible_id)
- /users​/{user_id}​/bookmarks​ POST
- Added RequestBody
- /users​/{user_id}​/bookmarks​/{bookmark_id} PUT
- Added RequestBody 
- /users​/{user_id}​/bookmarks​/{bookmark_id} DELETE
- Changed return type to string
- /users​/{user_id}​/highlights GET
- Updated default limit to 25
- Added page parameter
- /users​/{user_id}​/highlights POST
- Removed unused parameters
- Removed reference property
- Added database name to unique_random color generation
- /users​/{user_id}​/highlights​/{highlight_id} PUT
- Added RequestBody
- /users​/{user_id}​/highlights​/{highlight_id} DELETE
- Added …
> FCBH-293 API Completeness: Annotations

- app/Http/Controllers/User/UsersController.php
- Now the user can delete an account with the `user_id/password` or `user_id/social_provider_id/social_provider_user_id`
- If the user deletes an account all the personal information will be overwritten and the account will be soft deleted
- The personal information that is overwritten on this process is:
- Name
- FirstName
- LastName
- Email
- Password (even if it is encrypted is replaced by a random string)
- Notes
- As a user, I want to be able to request the deletion of my account and all my personal information
[FCBH-376](https://fullstacklabs.atlassian.net/browse/FCBH-376) 
- On your local environment run `http://dbp.test/open-api-v4.json` and verify that the delete `users/{id}` documentation is updated
- Do the request as mentioned on the documentation and …
> FCBH-376 Add delete user endpoint

- app/Http/Controllers/Bible/TextController.php
- Added relevance_order as an optional parameter to `search` endpoint
- Added canonical order as the default order of the query
- As a user who is familiar with the Bible, when I do a word/phrase search within my Bible, I want to see results listed in Bible-canonical order (google books of Bible for listing), eg first by book, then chapter, then verse.
[FCBH-395](https://fullstacklabs.atlassian.net/browse/FCBH-395) 
- On your local environment run `https://api.dbp.test/search?fileset_id=SPNWTC&dam_id=SPNWTC&key={KEY}&v=4&query=maria`.
- On another tab run `https://api.v4.dbt.io/search?fileset_id=SPNWTC&dam_id=SPNWTC&key={KEY}&v=4&query=maria`
- Verify that now the results are in canonical order
- Add the parameter `relevance_order=1` and verify that the order has the previous  behaviour
> FCBH-395 Bible search results in canonical order

- app/Http/Controllers/Bible/BooksControllerV2.php
- Fixed `getTestamentString` function on BooksControllerV2 that wasn't retrieving the testaments array
- Used `BibleBook` Model to get the names of the books
Original Story: [FCBH-439](https://fullstacklabs.atlassian.net/browse/FCBH-439) 
Review Story: [FCBH-541](https://fullstacklabs.atlassian.net/browse/FCBH-541) 
- On your local environment open https://api.dbp.test/library/book?dam_id=HBRHMTN2&key={key}&v=2
- And open https://dbt.io/library/book?dam_id=HBRHMTN2&key={key}&v=2
- Verify that now the books are filtered by the correct testament and the names are on the language
> FCBH-439/541 Hebrew: DBP2 and DBP4 are returning different data

- app/Http/Controllers/APIController.php
- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Plan/Plan.php
- app/Models/Plan/PlanDay.php
- app/Models/Plan/UserPlan.php
- app/Models/Playlist/Playlist.php
- composer.json
- composer.lock
- database/migrations/2019_07_12_045144_create_plans_table.php
- database/migrations/2019_08_01_063709_playlist_external_content.php
- routes/api.php
- Created PlansController for CRUD endpoints
- Created start plan endpoint
- Updated PlaylistController to show the author
- Added `external_content` column to playlist
- Created Plan/PlanDay/UserPlan Models
- Installed `spatie/eloquent-sortable` to add the ability to sort tables
- Installed migrations
Original Story: [FCBH-407](https://fullstacklabs.atlassian.net/browse/FCBH-407) 
Original Story: [FCBH-408](https://fullstacklabs.atlassian.net/browse/FCBH-408) 
Review Story: [FCBH-562](https://fullstacklabs.atlassian.net/browse/FCBH-562) 
Review Story: [FCBH-563](https://fullstacklabs.atlassian.net/browse/FCBH-563) 
- On your local environment run `php artisan migrate --database="dbp_users"` to generate the database tables
- On your local environment run `composer …
> FCBH-407/408 Backend: Plans Support

- app/Http/Controllers/APIController.php
- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Plan/Plan.php
- app/Models/Plan/PlanDay.php
- app/Models/Plan/UserPlan.php
- app/Models/Playlist/Playlist.php
- composer.json
- composer.lock
- database/migrations/2019_07_12_045144_create_plans_table.php
- database/migrations/2019_08_01_063709_playlist_external_content.php
- routes/api.php
- Created PlansController for CRUD endpoints
- Created start plan endpoint
- Updated PlaylistController to show the author
- Added `external_content` column to playlist
- Created Plan/PlanDay/UserPlan Models
- Installed `spatie/eloquent-sortable` to add the ability to sort tables
- Installed migrations
Original Story: [FCBH-409](https://fullstacklabs.atlassian.net/browse/FCBH-409) 
Review Story: [FCBH-564](https://fullstacklabs.atlassian.net/browse/FCBH-564) 
- Test that the read endpoint have pagination
- Test that you can now update a plan and plan days
> FCBH-409 Backend: Featured Plans 🗣

- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Playlist/Playlist.php
- app/Models/Playlist/PlaylistFollower.php
- database/migrations/2019_08_06_210133_follow_playlists.php
- routes/api.php
- Added the ability to follow/unfollow a playlist
- Added pagination to playlists
- Added followed playlists to GET endpoint
- Added PUT endpoint to playlists to edit name, external_content url
- Created PlaylistFollower Model
- Installed migrations
Original Story: [FCBH-406](https://fullstacklabs.atlassian.net/browse/FCBH-406) 
Review Story: [FCBH-567](https://fullstacklabs.atlassian.net/browse/FCBH-567) 
- On your local environment run `php artisan migrate --database="dbp_users"` to generate the database tables
- Test `/playlists/{playlist_id}/follow` POST endpoint and check that now you can follow/unfollow playlists
- Test `/playlists` GET endpoint and check that now …
>  FCBH-406 Backend: Featured Playlists

- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Plan/PlanDay.php
- app/Models/Playlist/Playlist.php
- app/Models/Playlist/PlaylistItems.php
- database/migrations/2019_07_12_045144_create_plans_table.php
- routes/api.php
- Added PlayListItems Model
- Added the ability to reorder and delete playlist items
- Added `playlists/{playlist_id}` GET endpoint with the detail of the items
- Added `playlists/{playlist_id}/item` POST endpoint in order to add an item
Original Story: [FCBH-454](https://fullstacklabs.atlassian.net/browse/FCBH-454) 
Review Story: [FCBH-568](https://fullstacklabs.atlassian.net/browse/FCBH-568) 
- Test `/playlists/{playlist_id}/item` POST endpoint and check that now you can add playlist items
- Test `/playlists/{playlist_id}` GET endpoint and check that now the playlist response have the items 
- Test `/playlists/{playlist_id}` PUT endpoint and check that now you can reorder and delete playlist …
> FCBH-454 Backend: Playlist Support - Playlist Items

- app/Http/Controllers/Plan/PlansController.php
- app/Models/Plan/PlanDay.php
- routes/api.php
- Created `/plans/{plan_id}/day` POST endpoint in order to add days to a plan
- Updated Documentation
Original Story: [FCBH-665](https://fullstacklabs.atlassian.net/browse/FCBH-665) 
Review Story: [FCBH-706](https://fullstacklabs.atlassian.net/browse/FCBH-706) 
- Test `/plans/{plan_id}/day` POST endpoint and check that now you can add days to a plan
> FCBH-665 Add day endpoint for Plans

- app/Http/Controllers/APIController.php
- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Plan/Plan.php
- app/Models/Plan/PlanDay.php
- app/Models/Plan/UserPlan.php
- app/Models/Playlist/Playlist.php
- app/Models/Playlist/PlaylistItems.php
- Fixed ambiguous query on `/plans` GET endpoint
- Updated all playlist and plan documentation responses in order to match the result of the endpoints
Original Story: [FCBH-653](https://fullstacklabs.atlassian.net/browse/FCBH-653) 
Review Story: [FCBH-736](https://fullstacklabs.atlassian.net/browse/FCBH-736) 
- Test all playlist and plans endpoints and verify that the documentation match the results
`/plans` GET endpoint example:
Result: 
```javascript
{
"current_page": 1,
"data": [
{
"id": 47,
"name": "Complete day",
"featured": false,
"suggested_start_date": "2019-10-10",
"created_at": "2019-08-23 02:24:12",
"updated_at": "2019-08-23 02:24:12",
"start_date": null,
"percentage_completed": 100, …
```
>  FCBH-653 Update docs response example objects

- app/Http/Controllers/User/BookmarksController.php
- app/Http/Controllers/User/HighlightsController.php
- app/Http/Controllers/User/NotesController.php
- routes/api.php
- Added token to the annotations (Notes / Bookmarks / Highlights)
- Updated the documentation
Original Story: [FCBH-670](https://fullstacklabs.atlassian.net/browse/FCBH-670) 
Review Story: [FCBH-797](https://fullstacklabs.atlassian.net/browse/FCBH-797) 
-  Whit the `api_token` parameter test (GET, POST, PUT, DELETE) endpoints of:
- `bookmarks`
- `notes`
- `highlights`
> FCBH-670 Add tokens for all endpoints that are user specific

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Bible/TextController.php
- app/Http/Controllers/Wiki/LanguagesController.php
- Added pagination to `/search`, `/bibles`, and `/languages`
Original Story: [FCBH-654](https://fullstacklabs.atlassian.net/browse/FCBH-654) 
Review Story: [FCBH-846](https://fullstacklabs.atlassian.net/browse/FCBH-846) 
- Add `page` and `limit`  parameters to `/languages`, `/bibles` and `/search` endpoints and verify that the content is paginated
> FCBH-654 Add pagination to the endpoints that don't have it

- app/Http/Controllers/Bible/TextController.php
- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- Added the ability to download all the bible and to show all the plan details in order to avoid multiple calls on the client
> FCBH-588 Download Plan/Playlist

- composer.json
- composer.lock
- Changed `sentry/sentry-laravel` version to `1.2` in order to support php 7.2
> Add support to PHP 7.2

- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Transformers/FileSetTransformer.php
Added a thumbnail prop to filesets that are videos.  This will give us the Gospel Films thumbnails from the API.
> FCBH-776 Add thumbnails to videos

- app/Models/User/Study/Bookmark.php
- app/Models/User/Study/Note.php
- app/Transformers/UserBookmarksTransformer.php
- app/Transformers/UserNotesTransformer.php
Mymicing Highlights, Bookmarks and Notes now return their respective bible's book name.
> FCBH-995 Bookmarks/Notes Book name in current bible langauge

- app/Http/Controllers/User/PushTokensController.php
- app/Models/User/PushToken.php
- database/migrations/2019_10_22_022248_create_user_push_tokens_table.php
- routes/api.php
- Added `GET`, `POST` and `DELETE` endpoints for push tokens.
Original Story: [FCBH-675](https://fullstacklabs.atlassian.net/browse/FCBH-675) 
Review Story: [FCBH-1013](https://fullstacklabs.atlassian.net/browse/FCBH-1013) 
- Test `/push_notifications` `GET, POST` and `DELETE` endpoints
**(*)Note:** If you want to reverse the migration run `php artisan migrate:rollback --database="dbp_users"`
> FCBH-675 Push Notification Token Registration

- app/Http/Controllers/User/UsersController.php
- Added 422 error code to user validation on Users Controller on POST and PUT endpoints.
- Fixed 500 error on Social provider login.
Original Story: [FCBH-1079](https://fullstacklabs.atlassian.net/browse/FCBH-1079) 
Review Story: [FCBH-1094](https://fullstacklabs.atlassian.net/browse/FCBH-1094) 
- Try to update (`/users/{user_id} PUT`) or create (`/users` POST) a user with invalid fields and verify that a 422 response is retrieved
- Verify that you can create a user with social provider fields (facebook, google)
> FCBH-1079 User verification should return errors

- app/Http/Controllers/Bible/TextController.php
- Added limit to My Library search
Original Story: [FCBH-1041](https://fullstacklabs.atlassian.net/browse/FCBH-1041) 
Review Story: [FCBH-1122](https://fullstacklabs.atlassian.net/browse/FCBH-1122) 
- On your local environment change the value of one of the notes to `NULL`
- Call `http://dev.v4.dbt.io/api/search/library?query=a` and verify you don't get an error
> FCBH-1041 Searching using "My Library" fails

- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/User/Dashboard/KeysController.php
Added the path to all plan days such that the audio can be played for the day's playlist.
> FCBH-605 Add path to plan days

- app/Http/Controllers/User/AccountsController.php
- Added updateOrCreate to social account creation
Original Story: [FCBH-1105](https://fullstacklabs.atlassian.net/browse/FCBH-1105) 
Review Story: [FCBH-1144](https://fullstacklabs.atlassian.net/browse/FCBH-1144) 
- Test `accounts/` POST endpoint with an existing social account number and verify that the endpoint returns instead of a 500 error the social account
> FCBH-1105 Return error on duplicate social account creation

- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Http/Controllers/Bible/TextController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/User/Study/Highlight.php
- app/Transformers/TextTransformer.php
- app/Transformers/UserHighlightsTransformer.php
- app/Transformers/V2/Annotations/HighlightTransformer.php
Added audio filesets to the payload of both the highlights and the bible text search results with minimal additions to querying.  We are not assured to have audio but we are following this up with an endpoint to check if audio is avaialble for a specific verse level location in the bible.
> FCBH-1175 Temp playlist support

- app/Http/Controllers/Playlist/PlaylistsController.php
Fixed and issue where suddenly trying to access a non existent prop on an object caused a 500 error.
> Hotfix 11-26-19-1

- app/Http/Controllers/Bible/TextController.php
- app/Http/Controllers/Bible/VideoStreamController.php
The cache string was not resetting the cache per language somehow.  Then again, I ran into issues where it seems some php/laravel syntax is not working anymore when accessing members of a collection.
> Jesus Films Issues

- app/Http/Controllers/Playlist/PlaylistsController.php
- Added full chapter functionality when verse_start or verse_end are not present on an HLS playlist item.
- Verify that the Psalms Featured Plan works
> Add full chapter when verses are not present on an HLS playlist item

- app/Http/Controllers/Playlist/PlaylistsController.php
- Added bible_id to playlist items
- Added download parameter to playlist hls endpoint
[FCBH-1016](https://fullstacklabs.atlassian.net/browse/FCBH-1016) 
- Test `http://dbp.test/api/playlists/13883?asset_id=dbp-prod&api_token={API_TOKEN}&v=4&&key={API_KEY}`GET` endpoint to get a playlist
- Test the hls endpoint of the playlist with the param `download=true` and verify you get a local hls file and the URLs of the mp3 files
> FCBH-1016 Audio Downloads

- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- Fixed null object error on Playlist Controller and BibleFilesetController
[FCBH-1211](https://fullstacklabs.atlassian.net/browse/FCBH-1211)
> FCBH-1211 Whole Chapter in temp playlists

- app/Http/Controllers/Bible/BibleFileSetsController.php
Ordered Gospel films by bible book order (Matthew/Mark/Luke/John) and then by chapter start and verse start.
- Get Gospel films (video filesets) for any bible: `http://dbp.test/api/bibles/filesets/ENGESHP2DV?asset_id=dbp-vid&type=video_stream&v=4&key=52e62d4c-f7c8-4a8b-9008-8634d0fbddb0`
- Observe that the ordering for Book/Chapter/Verse is present.
> FCBH-1239 Gospel Film Ordering

- app/Http/Controllers/Bible/VideoStreamController.php
- Added `show_detail` and `metadata_tag` parameters to the `jesusFilmsLanguages` endpoint in order to show all the languages available with details in the `metadata_tag` language selected
Original Story: [FCBH-1267](https://fullstacklabs.atlassian.net/browse/FCBH-1267) 
- Test `http://dbp.test/api/arclight/jesus-film/languages?v=4&key={API_KEY}&show_detail=true&metadata_tag=en`GET endpoint and verify that you get all the jesus film languages with detail
> FCBH-1267 Add all Jesus Film languages to selector

- app/Http/Controllers/Plan/PlansController.php
- routes/api.php
- Added endpoint to stop a plan `/plans/{plan_id}/stop`
[FCBH-1270](https://fullstacklabs.atlassian.net/browse/FCBH-1270) 
- Test `http://dbp.test/api/plans/{PLAN_ID}/stop?asset_id=dbp-prod&api_token={API_TOKEN}&key={API_KEY}&v=4` DELETE endpoint to stop a plan
> FCBH-1270 Remove a featured plan

- app/Http/Controllers/User/HighlightsController.php
- Added verse text filter to highlights GET endpoint
Original Story: [FCBH-1198](https://fullstacklabs.atlassian.net/browse/FCBH-1198) 
Review Story: [FCBH-1365](https://fullstacklabs.atlassian.net/browse/FCBH-1365) 
- Test `/users/{USER_ID}/highlights?v=4&key={API_KEY}&page=1&query=jesus` `GET` endpoint and verify that the results are filtered
> FCBH-1198 Highlights infinitely trying to fetch more results after searching

- app/Http/Controllers/User/UsersController.php
- Updated logic of the user validation when the user changes the email
Original Story - [FCBH-1192](https://fullstacklabs.atlassian.net/browse/FCBH-1192) 
Review Story - [FCBH-1364](https://fullstacklabs.atlassian.net/browse/FCBH-1364) 
- Test `/users/{USER_ID}?v=4&key={API_KEY}` `PUT` with the following body endpoint and verify the email is updated 
```json
{
"project_id": "{USER_ID}",
"email": "{NEW_EMAIL}",
"first_name": "TEST",
"last_name": "TEST",
"name": "TEST TEST",
"profile": {
"address1": "",
"birthday": null,
"city": "",
"country_id": "",
"state": "",
"zip": ""
}
}
```
> FCBH-1192 updateUser always errors if email is passed in

- app/Console/Commands/syncV2Bookmarks.php
- app/Console/Commands/syncV2Highlights.php
- app/Console/Commands/syncV2Notes.php
- app/Console/Commands/syncV2Profiles.php
- app/Console/Commands/syncV2Users.php
- app/Helpers/Helpers.php
- config/settings.php
- Updated kernel functions in order to improve the  v2 syncing efficiency
- Users 
- Profiles
- Bookmarks 
- Notes
- Highlights
[FCBH-1384](https://fullstacklabs.atlassian.net/browse/FCBH-1384) 
- If you want can add `V2_V4_SYNC_CHUNK_SIZE` to the `.env` on your local environment to change the default sync chunk size of `5000`
- Run the commands
1. `php artisan syncV2:users`
2. `php artisan syncV2:profiles`
3. `php artisan syncV2:bookmarks`
4. `php artisan syncV2:highlights`
5. `php artisan syncV2:notes`
- Verify that now the v2 data synchronization is working faster
> FCBH-1384 Improve v2 syncing efficiency

- app/Traits/CallsBucketsTrait.php
- Changed expiration time on cloud front from 1 hour to 24 hours
> Change expiration time on cloud front

- app/Http/Controllers/User/PasswordsController.php
- Added project registration on `/users/password/email` POST endpoint
[FCBH-1454](https://fullstacklabs.atlassian.net/browse/FCBH-1454) 
- Test `/users/password/email` POST endpoint with a user that doesn't belong to a `project_id` and verify it works
> FCBH-1454 Failing to Send Password Reset Email (iOS & Android)

- app/Http/Controllers/Organization/ProjectsController.php
- resources/views/docs/sdk.blade.php
This PR fixes the json generated docs in order to generate the SDK by `swagger-codegen`
> FCBH-699 fix DBP4 SDK generation

- .php_cs.dist
- app/Http/Controllers/Bible/BibleFileSetsController.php
Set mem cache for the filesets to 12 hrs. URL signing was already at 24 hrs.
> FCBH-1440 Ensure all cache values set correctly

- app/Http/Controllers/Playlist/PlaylistsController.php
This PR adds in a `total_duration` key to featured and user playlists
> FCBH-1601 Add total_duration to playlists

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/AudioController.php
- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Bible/VideoStreamController.php
- app/Http/Middleware/Cors.php
- app/Models/Bible/BibleFilesetCopyright.php
- app/Transformers/FileSetTransformer.php
- routes/api.php
- routes/web.php
- Added bibles/{bible_id}/copyright copyrigth endpoint
- Added bibles/{bible_id}/chapter chapter endpoint
- Fixed api_status web endpoint
Story: [FCBH-1676](https://fullstacklabs.atlassian.net/browse/FCBH-1676)  
- Run `http://dbp.test/api/bibles/ENGESV/chapter?api_token={API_TOKEN}&v=4&key={API_KEY}&book_id={BOOK_ID}&chapter={CHAPTER}&copyrights={TRUE/FALSE}&drama={TRUE/FALSE/NULL}&zip={TRUE/FALSE}` and verify that the endpoint work as expected
> FCBH-1676 Create new Chapter Detail Endpoint

- app/Http/Controllers/Bible/BiblesController.php
This hotfix PR handles the errors when trying to fetch an HTML file or a Jesus film API error
> FCBH-1676 Hotfix - handle html and jesus film errors

- app/Models/User/Study/Highlight.php
- Fixed Call toArray() on string on highlights index [sentry]
- [Link](https://sentry.io/organizations/fullstack-labs/issues/1451325974)
> Fix Call toArray() on string on highlights index [sentry]

- app/Exceptions/Handler.php
- Improved Error handler error response by refactoring `customApiResponse` function
- Added validation to avoid sentry report if `SENTRY_DSN` is not configured
Original Story: [FCBH-1731](https://fullstacklabs.atlassian.net/browse/FCBH-1731)  
Review Story: [FCBH-1736](https://fullstacklabs.atlassian.net/browse/FCBH-1736)
> FCBH-1731 Improve PHP Error Response

- app/Http/Controllers/User/HighlightsController.php
- Ordered the highlights by book by default
Original Story: [FCBH-1510](https://fullstacklabs.atlassian.net/browse/FCBH-1510)  
Review Story: [FCBH-1738](https://fullstacklabs.atlassian.net/browse/FCBH-1738)  
- Run `/api/users/{USER_ID}/highlights?v=4&key={API_KEY}` and verify that the highlights are now ordered by book
> FCBH-1510 Highlights Task - Should appear in order

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/User/NotesController.php
- app/Models/Playlist/PlaylistItems.php
- app/Transformers/BibleTransformer.php
This PR adds in the `bible_name` field to the return from the show note service
> FCBH-1677 Add bible_name to show note service

- app/Http/Controllers/Bible/BiblesController.php
- Added defensive programming when for some reason we don't get results from the database. For example a bible fileset is missing one file on a chapter
> FCBH-1756 Add empty results to New Chapter Endpoint

- app/Http/Controllers/Bible/BiblesController.php
- Added comparation with all the fields of the fileset. To be sure we get the correct hash_id
> FCBH-1756 Fix fileset comparation

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/User/NotesController.php
- app/Models/User/Study/Highlight.php
- app/Models/User/Study/Note.php
- app/Transformers/UserNotesTransformer.php
- Added bible_name to the Note Model instead of the show controller
-  We removed non available filesets from the highlights endpoint
> FCBH-1744 Refactor: Temp Playlists

- app/Http/Controllers/Bible/BiblesController.php
- Added a cast to object on the `getFileset` response. This way we always have an object response
> Mauricio 3.1.0 Hotfixes

- app/Models/User/Study/Note.php
- Added the verse_text append to Note Model
> FCBH-1742 Add verse_text to notes detail endpoint

- app/Http/Controllers/Playlist/PlaylistsController.php
- By setting the `#EXT-X-TARGETDURATION` for the total duration of the playlist the playback error disappear at the end of the audio
- Also added `#EXT-X-DISCONTINUITY` only when is necessary
> FCBH-1733 Plan items randomly pausing near the end of the audio

- app/Console/Commands/reSyncV2Notes.php
- Added the case when the user changed the v2 note after the syncronization on v4
> FCBH-1845 Re sync newer v2 updated notes

- app/Console/Commands/reSyncV2Notes.php
- Forced a v2 -> v4 resync if a note_id is retrieved in the command `php artisan reSyncV2:notes {note_id}`
- Do not change the `update_at` date if the note wasn't resynced
- Fixed empty query error and the end of the script
> FCBH-1845 Final PR Comments

- .ebextensions/cron-artisan-scheduler.config
- app/Console/Kernel.php
(instead of also in the shell)
> move all artisan scheduler cron logic into laravel

- app/Http/Controllers/Bible/VideoStreamController.php
- Handeling all jesus film API errors, now we retrieve empty responses if there is any error with the Jesus Film API
> FCBH-1954 Handle new Jesus Film errors

- app/Http/Controllers/Bible/StreamController.php
- Added 12 hours cache to hls master playlist and Bandwith hls files
[FCBH-2059](https://fullstacklabs.atlassian.net/browse/FCBH-2059) 
- Run `http://dbp.test/api/bible/filesets/ENGESVN1SA/MAT-13-1-/playlist.m3u8?key={KEY}&v=4&asset_id=dbp-prod` and verify is working
> FCBH-2059 Add API cache to hls generation

- app/Http/Controllers/Bible/BiblesController.php
- doc/STARTING.md
- Added How to use video_stream documentation to the getting started doc
Original Story: [FCBH-1990](https://fullstacklabs.atlassian.net/browse/FCBH-1990) 
- Navigate to `https://github.com/faithcomesbyhearing/dbp/blob/FCBH-1990/doc/STARTING.md` and verify the content of the section `Common workflow #2: Displays video stream Bibles`
> FCBH-1990 add video_stream to API getting started doc

- app/Http/Controllers/User/UsersController.php
- Updated `/users/{id}` PUT endpoint to update users profile data
Original Story: [FCBH-2552](https://fullstacklabs.atlassian.net/browse/FCBH-2552) 
- Open the app with the FCBH-2552 backend branch selected.
- Navigate to My Account -> Edit Account
- Edit City/State/Zip/Birthday and verify are being updated
> FCBH-2552 update PUT users endpoint to save profile data

- app/Http/Controllers/User/UsersController.php
- Added profile data to login and token validation endpoints
Original Story: [FCBH-2552](https://fullstacklabs.atlassian.net/browse/FCBH-2552) 
- Call `http://dbp.test/api/login?v=4&key={APP_KEY}` POST endpoint and verify you get the profile data with the login
- Call `http://dbp.test/api/token/validate?v=4&key={APP_KEY}&api_token={API_TOKEN}&user_details=true` POST endpoint and verify you get the profile data with the login
> FCBH-2552 Add profile data to login and token validation endpoints 

- app/Http/Controllers/User/UsersController.php
- Retrieve the valid api_token when asked for user_details
Original Story: [FCBH-2486](https://fullstacklabs.atlassian.net/browse/FCBH-2486) 
- Call `http://dbp.test/api/token/validate?v=4&key={APP_KEY}&api_token={API_TOKEN}&user_details=true` POST endpoint and verify you get the user data with the api_token
> FCBH-2486 Retrieve api_token on user token/validate endpoint

- .ebextensions/artisan.config
- app/Http/Controllers/APIController.php
- routes/api.php
- Added a different way to verify on the APIController if a call is an API call, this is achieved  by parsing the route name
> Hot fix health check

- app/Http/Controllers/Bible/BiblesController.php
- Filter files by access control on bible chapters 
Original Story: [FCBH-2540](https://fullstacklabs.atlassian.net/browse/FCBH-2540) 
- Call `http://dbp.test/api/bibles/{bible_id}/chapter?v=4&key={APP_KEY}&book_id={book_id}&chapter={chapter_id}`
check that the filesets with permissions are getting correctly returned (try with MWWHDV bible)
> FCBH-2540 filter bible chapters with access control

- app/Models/User/UserDownload.php
- Fix user download documentation
- verify it works by hitting this endpoint: <host>/docs/swagger/v4
> Hot Fix documentation

- app/Models/Playlist/PlaylistItems.php
- Fix database connection when calling timestamps by adding the connection name
> FCBH-2535 update DB connection

- app/Http/Controllers/Playlist/PlaylistsController.php
check text_filesets before return on playlists
[FCBH-2698](https://fullstacklabs.atlassian.net/browse/FCBH-2698)
* Go to a featured plan/playlist
* Translate to a language bible without text
* should translate succesfully
> FCBH-2698 Fix error on playlist show text

- composer.lock
- package-lock.json
- Updated composer dependencies
- Updated npm dependencies
Original Story: [FCBH-2584](https://fullstacklabs.atlassian.net/browse/FCBH-2584) 
- run `composer install`
- run `npm install`
- Test some endpoints and verify that are working correctly
> FCBH-2584 update composer dependencies

- app/Console/Commands/translatePlaylist.php
- app/Console/Kernel.php
* Create route for artisan command
* translate playlist using playlistController
* Sync duration and verses
Original Story: [FCBH-2599](https://fullstacklabs.atlassian.net/browse/FCBH-2599) 
- Create playlist or plan and add playlist_items
- run console command:php artisan translate:playlist {playlist_id} {bibles_ids}
- Check that the duration, verses and translation of the related playlist_items where created as expected
> FCBH-2599 Create translate playlist artisan command

- app/Http/Controllers/User/UsersController.php
- Updated user login endpoint query
[FCBH-1913](https://fullstacklabs.atlassian.net/browse/FCBH-1913)
- Login with facebook or google and verify is working
> FCBH-1913 Improve users endpoints

- app/Http/Controllers/Plan/PlansController.php
- Change draft status to children playlists on plan draft change
> FCBH-2727 Hot fix 500 error on fetching a plan

- app/Http/Controllers/Playlist/PlaylistsController.php
* Replace playlistId for the generated translated playlist id
[FCBH-2704](https://fullstacklabs.atlassian.net/browse/FCBH-2704)
* Translate a playlist to a verse based bible like KJV and show_details = true
https://dev.dbt.io/api/playlists/{playlist_id}/translate
> FCBH-2704 return text for translations

- app/Http/Kernel.php
* Increment throttle request limit 
[FCBH-2714](https://fullstacklabs.atlassian.net/browse/FCBH-2714)
> FCBH-2714 Change throttle request limit to 2000 per min

- app/Transformers/AudioTransformer.php
- Fix chapter detail endpoint by updating the name of the endpoint on the AudioTransformer
> Hot fix chapter detail endpoint

- app/Http/Controllers/User/UsersController.php
Link social account on login
Create and link social account on login
> FCBH-2882 Social provider link account on login

- app/Http/Controllers/Api_key/KeysController.php
- app/Models/User/KeyRequest.php
- database/migrations/2020_11_14_160506_key_request.php
- public/css/app_api_key.css
- resources/views/api-key/request_key.blade.php
* Create views for dbp admin login
[FCBH-2606](https://fullstacklabs.atlassian.net/browse/FCBH-2606)
* visit {dbp-local}/key/request
* create a request
* Check that the database created the record
> FCBH-2606 Set up DB to support API Key Request form fields

- app/Http/Controllers/Playlist/PlaylistsController.php
- routes/api.php
Added the ability to retrieve an hls response by url parameters to the playlists/{playlist_item_id}/item-hls endpoint, we do this also on the filesets endpoint. Now we can get an hls of a playlist item by the playlist_id or a bible_location
> [Gideons branch] HLS playlist item by url

- app/Http/Controllers/User/UsersController.php
* use updateOrCreate to check social provider account
[FCBH-2892](https://fullstacklabs.atlassian.net/browse/FCBH-2892)
> FCBH-2892 avoid creating account if exists

- app/Http/Controllers/Bible/TextController.php
* Instead of joining user_playlist and followed_playlists create two different queries 
and join the playlists
* sort merged playlists by name
https://fullstacklabs.atlassian.net/browse/FCBH-2888
> FCBH-2888 improve library queries for playlists

- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Bible/StreamController.php
- app/Transformers/FileSetTransformer.php
* Create parent_hls url on bibleFileset
* Set duration, audio_type, verses to non-chapter files
* Check multi_mp3 chapter and add data to hls
[FCBH-2366](https://fullstacklabs.atlassian.net/browse/FCBH-2366)
retrieve chapter fileset with:
* bible_id = IWKWYP
* v = 4
* assign a key, api token, book_id = LUK and a chapter
* http://dbp.test/api/bibles/{bible_id}/chapter
* Should return the audio with a hls file with the mp3 chapters
> FCBH-2366 support non-chapter audio files

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Bible/StreamController.php
- Added the filename extension of a multiple mp3 hls file
- Added an isset verification on the mp3 statement
> FCBH-2366 missing commits

- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- Modified translation of plans, now the PlansController has he's own translatePlaylist function that works more performant
[FCBH-2873](https://fullstacklabs.atlassian.net/browse/FCBH-2873) 
- Run `http://dbp.test/api/plans/{PLAN_ID}/translate?v=4&key={KEY}&api_token={API_TOKEN}&bible_id=ENGESV` using a large plan and verify is not timing out
> FCBH-2873 Timeout error when translating a large plan/creating a playlist from large list of search results

- app/Http/Controllers/Playlist/PlaylistsController.php
* If verses of the stream starts on 1, add an emptyObject on 0
[FCBH-3037](https://fullstacklabs.atlassian.net/browse/FCBH-3037)
* Create a playlist
* Add ENGKJV Psalms 30 (any verse) to the playlist
* Check the audio matches with the text
> FCBH-3037 Fix playlist verse missed verse

- app/Http/Controllers/Bible/TextController.php
- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Transformers/TextTransformer.php
- routes/api.php
- routes/apiV2.php
merge develop into earlyaccess
> Earlyaccess merge develop

- app/Http/Controllers/Playlist/PlaylistsController.php
- routes/api.php
- Reordered `item-hls` API entries
- Used endpoint location parameters 
- Run `http://dbp.test/api/playlists/{FILESET_ID}-{BOOK_ID}-{CHAPTER}-{VERSE_START}-{VERSE_END}/item-hls?v=4&key={API_KEY}` and verify you get an hls file
- Run `http://dbp.test/api/playlists/{PLAYLIST_ITEM_ID}/item-hls?v=4&key={API_KEY}` and verify you get an hls file
> [GIDEONS] Fix Gideons integration Plan translation

- app/Http/Controllers/Playlist/PlaylistsController.php
- Fixed case when the timestamp count is the same that the bytes entries and the verse_start is not 0
> FCBH-3037 add missing statement calculaling bytes

- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Transformers/UserTransformer.php
- routes/api.php
- UserTransform fix: the name of the endpoint wasn't updated on the UserTransform response
- Rebase from develop
- Added metadata endpoint: receives a fileset location instead of a `playlist_id` and retrieves that playlist item metadata
> [GIDEONS] Gideon integration playlist

- app/Http/Controllers/User/UsersController.php
> FCBH-3126 fix api social login 500 error

- app/Http/Controllers/User/UsersController.php
> FCBH-3126 validate email onn login

- app/Http/Controllers/User/UsersController.php
> FCBH-3126 Fix logging error on user login

- .ebextensions/logging.config
- .vscode/launch.json
add laravel  to beanstalk bundlelogs
> Develop laravel bundlelogs

- app/Http/Controllers/User/UsersController.php
> FCBH-3126 login validator remove and add log with request data

- app/Http/Controllers/Playlist/PlaylistsController.php
* Check if the bible and filesets used exists befre calling other properties
[FCBH-3140](https://fullstacklabs.atlassian.net/browse/FCBH-3140)
> FCBH-3140 500 error /playlists (processMp3Audio)

- app/Http/Controllers/User/UsersController.php
> FCBH-3126 login validator remove and add log with full request

- app/Http/Controllers/User/UsersController.php
> FCBH-3126 account log fix

- app/Http/Controllers/ApiKey/DashboardController.php
- app/Http/Controllers/Bible/TextController.php
- app/Http/Controllers/Wiki/CountriesController.php
- app/Http/Controllers/Wiki/LanguagesController.php
- config/settings.php
- database/migrations/2020_11_14_160506_key_request.php
- resources/views/api_key/dashboard.blade.php
- resources/views/layouts/app.blade.php
- routes/api.php
- routes/web.php
* when option approve is picked the request
creates the user if it does not exist
then creates the key and assigns permissions to it
from the env variable API_KEY_ACCESS_GROUPS
[FCBH-3034](https://fullstacklabs.atlassian.net/browse/FCBH-3034)
* create a request on https://api.dbp.test/api_key/request
* approve the request on  https://api.dbp.test/api_key/dashboard
* check that the key was correctly created and its permissions were assigned on the DB
> FCBH-3034 Admin approval process

- app/Http/Controllers/ApiKey/DashboardController.php
- database/migrations/2020_11_14_160506_key_request.php
- public/css/app_api_key.css
- resources/views/api_key/dashboard.blade.php
- routes/web.php
* when option approve is picked the request
creates the user if it does not exist
then creates the key and assigns permissions to it
from the env variable API_KEY_ACCESS_GROUPS
* show details on button click
* remove key from table
* format date
[FCBH-3123](https://fullstacklabs.atlassian.net/browse/FCBH-3123)
Run the key_request migration with: php artisan migrate --path=/database/migrations/2020_11_14_160506_key_request.php
set API_KEY_ACCESS_GROUPS=121,123,125 on your .env file
key request creation:
Go to dbp_url/api_key/request
submit a request
There should be a new row created on the table user_key_requests
Admin dashboard:
Go to dbp_url/api_key/dashboard
check That email and notes functionalities work
Check That you can approva a request
if the request is approved:
a user with the …
> FCBH-3123 fix ui and data retrieval on key dashboard

- app/Http/Controllers/User/HighlightsController.php
- app/Models/User/Study/Highlight.php
* Return empty collection if does not find bible/fileset on highlight transformer
* join bible first to check if it exists
[FCBH-3271](https://fullstacklabs.atlassian.net/browse/FCBH-3271)
> FCBH-3271 check bibles on highlights query

- app/Http/Kernel.php
Reverts faithcomesbyhearing/dbp#293
> Revert "increase throttle to 5000 per five mins"

- app/Http/Controllers/ApiMetadataController.php
- app/Http/Controllers/Bible/AudioController.php
- app/Http/Controllers/Bible/AudioControllerV2.php
- config/services.php
* Create config variable on services file, to point to CDN_SERVER variable on the envfile
* default variable to content.cdn.dbp-prod.dbp4.org
[FCBH-3302](https://fullstacklabs.atlassian.net/browse/FCBH-3302)
> FCBH-3302 use env file to point cdn server on v2 and assets endpoint

- app/Http/Controllers/ApiKey/DashboardController.php
- app/Http/Controllers/Bible/BibleFileSetsController.php
- routes/api.php
* Create helper methods to handle query for text and non_text filesets
* Create showChapter to handle all type of filesets with book and chapter
* repoint  v4_filesets.chapter to showChapter method
[FCBH-3314](https://fullstacklabs.atlassian.net/browse/FCBH-3314)
[FCBH-3328](https://fullstacklabs.atlassian.net/browse/FCBH-3328)
[FCBH-3320](https://fullstacklabs.atlassian.net/browse/FCBH-3320)
[FCBH-3321](https://fullstacklabs.atlassian.net/browse/FCBH-3321)
{basePath}/bibles/filesets/ENGESV/MAT/1 – should return text 
{basePath}/bibles/filesets/ENGESVN1DA/MAT/1 – should return signed url for mp3 
{basePath}/bibles/filesets/ENGESVN1SA/MAT/1 – should return HLS stream 
{basePath}/bibles/filesets/ENGESVP2DV/MAT/1 – should return Gospel Film
To see detail of the responses go to …
> FCBH-3314 v4_filesets.chapter handles all filesets

- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Traits/AccessControlAPI.php
- config/settings.php
- routes/api.php
* THIS PR IS ONLY FOR AUTH of the key, the return of the desired bulk response will be addressed on another pr
* Create showBatch to return bulk request
* Create blockedByBulkAccessControl to check fileset permissions and if. the current key allows the bulk request
[FCBH-3319](https://fullstacklabs.atlassian.net/browse/FCBH-3319)
* Set env variable KEYS_FILESET_BULK_ACCESS={a key with filesets access in your local, or a group separated by commas}
* {basePath}/bibles/filesets/ENGESVP2DV/batch – should return 404 if key does not have permissions, return a fileset if it does
> FCBH-3319 auth for keys on fileset bulk requests

- app/Http/Controllers/Bible/BibleFileSetsController.php
- routes/api.php
* Add book to url params on bulk endpoint
* rename endpoint to bibles/filesets/bulk/{fileset_id}/{book?}
* filter by book if book exists
[FCBH-3335](https://fullstacklabs.atlassian.net/browse/FCBH-3335)
* Set env variable KEYS_FILESET_BULK_ACCESS={a key with filesets access in your local, or a group separated by commas}
* {basePath}/bibles/filesets/bulk/ENGESVP2DV – should return 404 if key does not have permissions, return a fileset if it does
* {basePath}/bibles/filesets/bulk/ENGESVP2DV/MAT – should return 404 if key does not have permissions, return a fileset if it does
* {basePath}/bibles/filesets/bulk/ENGESV/MAT - return all text for MAT chapter (works for the books available)
* {basePath}/bibles/filesets/bulk/ENGESVN2DA/MAT - return mp3 files for MAT chapter of the bible for DA …
> FCBH-3335 add book filter on bulk endpoint

- app/Http/Controllers/Bible/AudioController.php
- app/Http/Controllers/Bible/AudioControllerV2.php
- app/Http/Controllers/Bible/BibleFileSetsController.php
* Add limit query parameter to set the pagination. size (defaulted to 5000)
* paginate bulk requests (both audio and text) to have the same response layout and metadata
[FCBH-3340](https://fullstacklabs.atlassian.net/browse/FCBH-3340)
* NOTE: All bulk calls should be paginated
* Set env variable KEYS_FILESET_BULK_ACCESS={a key with filesets access in your local, or a group separated by commas}
* {basePath}/bibles/filesets/bulk/ENGESVP2DV – should return 404 if key does not have permissions, return a fileset if it does
* {basePath}/bibles/filesets/bulk/ENGESVP2DV/MAT – should return 404 if key does not have permissions, return a fileset if it does
* {basePath}/bibles/filesets/bulk/ENGESV/MAT - return all text for MAT chapter (works for the books available)
* …
> FCBH-3340 add pagination to bulk responses

- app/Http/Controllers/Bible/BibleFileSetsController.php
* Add limit query parameter to set the pagination. size (defaulted to 5000)
* paginate bulk requests (both audio and text) to have the same response layout and metadata
[FCBH-3340](https://fullstacklabs.atlassian.net/browse/FCBH-3340)
* NOTE: All bulk calls should be paginated
* Set env variable KEYS_FILESET_BULK_ACCESS={a key with filesets access in your local, or a group separated by commas}
* {basePath}/bibles/filesets/bulk/ENGESVP2DV – should return 404 if key does not have permissions, return a fileset if it does
* {basePath}/bibles/filesets/bulk/ENGESVP2DV/MAT – should return 404 if key does not have permissions, return a fileset if it does
* {basePath}/bibles/filesets/bulk/ENGESV/MAT - return all text for MAT chapter (works for the books available)
* …
> FCBH-3340 add limit to requests

- app/Http/Controllers/Bible/AudioController.php
- app/Http/Controllers/Bible/AudioControllerV2.php
* Remove unused index on v4 audiocontroller
* add timestampsByReference to both v2 and v4 audiocontroller
[FCBH-3340](https://fullstacklabs.atlassian.net/browse/FCBH-3340)
> FCBH-3340 audioController fix methods on v2 and v4

- app/Http/Controllers/Bible/AudioControllerV2.php
* Remove unused index on v4 audiocontroller
* add timestampsByReference to both v2 and v4 audiocontroller
[FCBH-3340](https://fullstacklabs.atlassian.net/browse/FCBH-3340)
> FCBH-3340 update operationId for v4 audioController

- app/Console/Commands/syncV2Bookmarks.php
- app/Console/Commands/syncV2Highlights.php
- app/Console/Commands/syncV2Notes.php
- app/Console/Commands/syncV4Annotations.php
- app/Console/Kernel.php
- app/Helpers/Helpers.php
- app/Http/Controllers/Organization/ResourcesController.php
- app/Http/Controllers/User/BookmarksController.php
- app/Http/Controllers/User/HighlightsController.php
- app/Http/Controllers/User/NotesController.php
- config/settings.php
- database/seeds/SeedBibleText.php
* create artisan commant to sync annotation on dbp v4
* sync bibles on create annotations 
[FCBH-3290](https://fullstacklabs.atlassian.net/browse/FCBH-3290)
* create a csv file with this data (first row are the titles, second row the values): 
* dbp2-damid,dbp4-damid
SPNBDA,SPABDA
* set an env variable with the full path of the csv file you created as follows: BIBLE_SYNC_FILE_PATH=/full/path/to/file/file.csv
##To test highlights:
* {{baseUrl}}/api/users/:userid/highlights?asset_id=dbp-prod
* This is a json with a v2 bible SPNBDA, use it as the body of the request:
{
"bible_id": "SPNBDA",
"book_id": "MAT",
"book_name": "Matthew",
"chapter": 1,
"verse_start": 5,
"verse_end": 5,
"highlight_start": 1,
"highlighted_words": 22,
"highlighted_color": "#1780ef",
"user_id": {{userid}}
}
##To test …
> FCBH-3290 Recognize DBP2 bible_ids that are not in DBP4

- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
* validate playlist items on plans
* validate playlist items on playlists
[FCBH-3337](https://fullstacklabs.atlassian.net/browse/FCBH-3337)
> FCBH-3337 check playlist items before call on plans/playlist

- app/Http/Controllers/Bible/TextController.php
* add defensive code on filter for annotations on search
[FCBH-3316](https://fullstacklabs.atlassian.net/browse/FCBH-3316)
Login to the api using (remember to set v and. key values):
POST {{basePath}}/login, set this two parameters with a valid login on the body:
{ 
”email”: “your email“,
”password”: “your password“
}
The response will contain an “api_token“ value, use it for the next step
Go to GET {{basePath}}/search/library?v=4&key={{key}}&query={{query}}&api_token={{api_token}}
> FCBH-3316 defensive code on textcontroller

- app/Http/Controllers/Bible/BibleFileSetsController.php
* Create. validator for post calls on biblesetController, avoiding calling null objects
[FCBH-3317](https://fullstacklabs.atlassian.net/browse/FCBH-3317)
How to qa this?
Go to POST {{basePath}}/bibles/filesets/check/types (remember to use v, and key parameters)
Set the request body to:
[
{
"book_id":"MAT",
"chapter_start":1,
"chapter_end":1,
"completed":false,
"fileset_id":"ENGESVN2SA",
"has_audio":true,
"verse_start":1,
"verse_end":1
},
{
"book_id":"MAT",
"chapter_start":1,
"chapter_end":1,
"completed":false,
"fileset_id":"ENGESVN2SA",
"has_audio":true,
"verse_start":16,
"verse_end":16,
"verses":1,
"duration":0
}
]
If you remove the fileset_id from one or the two objects, you should get an error response with the validationmissing, and not an exception like: Exception 'ErrorException' …
> FCBH-3317 add defensive code to bibleFilesetsController

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
* add defensive code playlist and bibleController on the internal function getFileset
[FCBH-3318](https://fullstacklabs.atlassian.net/browse/FCBH-3318)
> FCBH-3318 validate getFileset on bible and playlist

- app/Http/Controllers/ApiKey/KeysController.php
- public/css/app_api_key.css
- resources/views/api_key/request_key.blade.php
- resources/views/api_key/requested_key.blade.php
- resources/views/layouts/app.blade.php
- resources/views/redirect.blade.php
- resources/views/welcome.blade.php
* Match style with webflw pages
* Re link everything to faithcomesByhearing.com/bible-brain
[FCBH-3357](https://fullstacklabs.atlassian.net/browse/FCBH-3357)
* On your browser, go to {{basePath}}/api_key/request, the design should match the webflow page: https://www.faithcomesbyhearing.com/api-key-request-bible-brain
* On your browser, go to {{basePath}}/api_key/requested, the design should match the webflow page: https://www.faithcomesbyhearing.com/api-key-request-success-bible-brain
> FCBH-3357 styled api key requests to match webflow

- app/Http/Controllers/Bible/AudioController.php
- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Bible/LibraryController.php
- app/Http/Controllers/Bible/TextController.php
- app/Transformers/BibleTransformer.php
- app/Transformers/V2/LibraryVolumeTransformer.php
- routes/api.php
- routes/apiV2.php
- routes/web.php
* Update transformers for biblesController, textController and libraryController
* Modify query on textController info
* Update data on text and library controller returns
[FCBH-2788](https://fullstacklabs.atlassian.net/browse/FCBH-2788)
* GET {{baseUrl}}/text/verseinfo?v=2&key={{key}}&dam_id={{bible_id}}&book_id={{book_id}}
* GET {{baseUrl}}/text/volume?v=2&key={{key}}&dam_id={{bible_id}}
* GET {{baseUrl}}/library/version?v=2&key={{key}}&code={{code}} (code is the bible_id without the language prefix IE: ESV)
* GET {{baseUrl}}/library/verseinfo?v=2&key={{key}}&dam_id={{bible_id}}&book_id={{book_id}}
Note:  baseUrl won't have the /api at the. end, because this is for v=2 versions
* On your browser, go to {{basePath}}/api_key/requested, the design should match the webflow page: …
> FCBH-2788 Implement Backward compatibility for Priority Group 4

- app/Console/Commands/syncV4Annotations.php
- app/Helpers/Helpers.php
- app/Http/Controllers/APIController.php
- app/Http/Controllers/Bible/AudioController.php
- app/Http/Controllers/Bible/TextController.php
- app/Http/Controllers/Organization/FilmsController.php
- app/Http/Controllers/User/NotesController.php
- app/Http/Controllers/User/SwaggerDocsController.php
- app/Http/Controllers/User/UsersController.php
- app/Http/Controllers/WelcomeController.php
- app/Http/Controllers/Wiki/LanguagesController.php
- app/Http/Controllers/Wiki/NumbersController.php
- app/Models/Bible/Bible.php
- app/Models/Language/Alphabet.php
- app/Models/Language/Language.php
- app/Models/Organization/Organization.php
- app/Transformers/TextTransformer.php
- app/Transformers/V2/LibraryCatalog/LanguageListingTransformer.php
- config/services.php
- routes/api.php
- routes/apiV2.php
- routes/web.php
* fix types and transformers on textController for v2
* fix searches for both v2 and v4 on dbp
* fix numbers endpoint for v2
[FCBH-2788](https://fullstacklabs.atlassian.net/browse/FCBH-2788)
* GET {{{baseUrl}}/video/videolocation?dam_id={{bible_id}}&v=2&key={{key}}
* GET {{baseUrl}}/library/language?v=2&key={{key}}
* GET {{baseUrl}}/library/organization?v={{version}}&key={{key}}
* GET {{baseUrl}}/video/jesusfilm?dam_id=ENGJFVS2DV&encoding=mp4&resolution=med&key=809db3bd83c66f3bc41be0cbd6bd1e3f&v=2
* {{baseUrl}}/text/searchgroup?dam_id={{bible_id}}&query=Saul&v={{version}}&key={{key}}
* {{baseUrl}}/library/numbers?v={{version}}&key={{key}}&language_code=HBR&start=0&end=10&script=bengali
Note:  baseUrl won't have the /api at the. end, because this is for v=2 versions
> FCBH-2789 backward compatibility for group 5

- app/Console/Commands/syncV4Annotations.php
- app/Helpers/Helpers.php
* create artisan commant to sync annotation on dbp v4
* sync bibles on create annotations 
[FCBH-3290](https://fullstacklabs.atlassian.net/browse/FCBH-3290)
* create a csv file with this data (first row are the titles, second row the values): 
* dbp2-damid,dbp4-damid
SPNBDA,SPABDA
* set an env variable with the full path of the csv file you created as follows: BIBLE_SYNC_FILE_PATH=/full/path/to/file/file.csv
##To test highlights:
* {{baseUrl}}/api/users/:userid/highlights?asset_id=dbp-prod
* This is a json with a v2 bible SPNBDA, use it as the body of the request:
{
"bible_id": "SPNBDA",
"book_id": "MAT",
"book_name": "Matthew",
"chapter": 1,
"verse_start": 5,
"verse_end": 5,
"highlight_start": 1,
"highlighted_words": 22,
"highlighted_color": "#1780ef",
"user_id": {{userid}}
}
##To test …
> FCBH-3290 add helpers to read csv to array

- resources/views/api_key/request_key.blade.php
* Match style with webflw pages
* Re link everything to faithcomesByhearing.com/bible-brain
[FCBH-3357](https://fullstacklabs.atlassian.net/browse/FCBH-3357)
* On your browser, go to {{basePath}}/api_key/request, the design should match the webflow page: https://www.faithcomesbyhearing.com/api-key-request-bible-brain
* On your browser, go to {{basePath}}/api_key/requested, the design should match the webflow page: https://www.faithcomesbyhearing.com/api-key-request-success-bible-brain
> FCBH-3357 make checkbox to be unnchecked by default

- app/Http/Controllers/User/BookmarksController.php
- app/Http/Controllers/User/HighlightsController.php
- app/Http/Controllers/User/NotesController.php
* Check bible and user data only for post calls on annotations validators
> Fix annotations validation for crud calls

- app/Http/Controllers/User/BookmarksController.php
- app/Http/Controllers/User/HighlightsController.php
- app/Http/Controllers/User/NotesController.php
This is the PR to Fix DBP4 annotations failing on update.
Notable:
Only check the bible and user validations for notes, highlights, and bookmarks on POST calls
> Hotfix for annotations CRUD validations

- app/Http/Controllers/Playlist/PlaylistsController.php
* add defensive code on all hls functionalities for playlistsController
[FCBHDBP-30](https://fullstacklabs.atlassian.net/browse/FCBHDBP-30)
> FCBHDBP-30 Add defensive code to playlist hls logic

- .github/pull_request_template.md
- app/Http/Controllers/Bible/StreamController.php
- app/Http/Controllers/User/UsersControllerV2.php
- app/Models/Bible/BibleFileset.php
- database/seeds/seedFilesetTags.php
- tests/Integration/BiblesRoutesTest.php
check uniqueFileset parameters and defensive code on  bibleFileset model
[FCBHDBP-36](https://fullstacklabs.atlassian.net/browse/FCBHDBP-36)
* go to dev.dbt.io/api/bible/filesets/HINSHVP2DA/LUK-1--/playlist.m3u8
* Data should be returned
* No 500 internal server error should be returned
> FCBHDBP-36 check uniqueFileset parameters 

- app/Http/Controllers/ApiKey/DashboardController.php
- public/css/app_api_key.css
- resources/views/api_key/dashboard.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
* change states in detail modal
* send email from detail modal
* add note from detail modal
* update styles for modals and table on dashboard
* add jquery full version and fix functionalities
* 
[FCBHDBP-4](https://fullstacklabs.atlassian.net/browse/FCBHDBP-4)
[FCBHDBP-5](https://fullstacklabs.atlassian.net/browse/FCBHDBP-5)
> FCBHDBP-4 update key admin process and data flow

- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Traits/AccessControlAPI.php
- config/settings.php
* remove env variable KEYS_FILESET_BULK_ACCESS
* add bulk access control to use filesets and api keys to check the access groups and retrieve a fileset if exists
[FCBHDBP-23](https://fullstacklabs.atlassian.net/browse/FCBHDBP-23)
all postman tests in https://www.getpostman.com/collections/6ab5297243b9f4b0e8ef should pass
> FCBHDBP-23 add new bulk access control to use filesets

- app/Http/Controllers/Bible/BibleFileSetsController.php
* Separate cache for each page on bulk endpoint
[FCBHDBP-48](https://fullstacklabs.atlassian.net/browse/FCBHDBP-48)
* set your params "v" = 4 and "key" = 68746f5c-011f-60fe-850c-a16585ac8ba8
* go to {apiPath}/bibles/filesets/bulk/{filesetId}?v=4 (filesetId for text, e.g ENGKJV) - this one should return the first page of the response (you can see this almost at the end of the response in the "meta" section)
* go to {apiPath}/bibles/filesets/bulk/{filesetId}?v=4&page=3 (filesetId for text, e.g ENGKJV) - this one should return the third page of the response (you can see this almost at the end of the response in the "meta" section)
> FCBHDBP-48 Fix pagination cache on bulk endpoint

- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
* check fileset when translating playlist and plan
[FCBHDBP-39](https://fullstacklabs.atlassian.net/browse/FCBHDBP-39)
* This is a data issue related to plan days items having an unexistent filesetId
* https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-53e3b11e-67bb-473f-8f3b-73af58fbe8a9 (check postman comment)
> FCBHDBP-39 Fix invalid fileset on translate plan and playlist

- app/Http/Controllers/Bible/BiblesController.php
If annotations return null, default to an empty array
[FCBHDBP-35](https://fullstacklabs.atlassian.net/browse/FCBHDBP-35)
I’m not able to reproduce this issue in a postman test, but the defensive code was added to avoid the error (I tested on my code by forcing a null response, but was not able to make it happen with only data)
> FCBHDBP-35 add check on chapter annotations if empty

- app/Http/Controllers/User/UsersController.php
* check if country string is similar to us
* check if a country exists. with the given id
[FCBHDBP-37](https://fullstacklabs.atlassian.net/browse/FCBHDBP-37)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-642eb082-97a7-4a5f-9ac8-ef7080efd7ff
* tests should pass
* If country does not exists, it should not return 500 error, but 400 bad request
> FCBHDBP-37 validate profile country on update

- app/Http/Controllers/User/AccountsController.php
* check properties on verifyProjectUserConnection and the destroy endpoint
[FCBHDBP-22](https://fullstacklabs.atlassian.net/browse/FCBHDBP-22)
> FCBHDBP-22 account controller defensive code for delete account

- app/Http/Controllers/User/UsersController.php
> add additional check if country_id field is not sent

- dbpSetup.md
Add local setup for dbp readme
> Add local setup for dbp readme

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Bible/Bible.php
- app/Transformers/BibleTransformer.php
- doc/STARTING.md
* FCBHDBP-19 remove bitrate from bible logic
* add codec metadata to all bibles responses and plan/playlist translations
* add fileset tags on getFileset and getAudioFileset for bibles (used on chapter endpoints)
[FCBHDBP-19](https://fullstacklabs.atlassian.net/browse/FCBHDBP-19)
* There's postman tests to check the mapped tags for filesets on this endpoints:
* https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-fc65060d-9b9e-462a-8751-b540d8d50231
* https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-f0144522-8f09-4a97-908a-779d8d08f8fc
* https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-f …
> FCBHDBP-19 Add fileset mapped metadata tags to responses with fileset included

- app/Http/Controllers/Playlist/PlaylistsController.php
* avoid using filesets that have audio, but are not usable for translations i.e opus
[FCBHDBP-58](https://fullstacklabs.atlassian.net/browse/FCBHDBP-58)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-e328a277-fc2e-46cb-bcf3-042225ace7a6 Should pass all tests
> FCBHDBP-58 ensure translate do not include opus filesets

- app/Http/Controllers/Bible/BiblesController.php
* Add default limit and page on endpoint params
* return pagination correctly for bibles
[FCBHDBP-26](https://fullstacklabs.atlassian.net/browse/FCBHDBP-26)
Tests should pass on https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-e83ef036-62b0-480a-82a8-414f864cb70b
> FCBHDBP-26 Force pagination on bibles all endpoint

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Kernel.php
- app/Http/Middleware/BibleIsBackwardCompatibility.php
- app/Http/Middleware/BiblesAllApiKeyCompat.php
- app/Models/Bible/Bible.php
- config/auth.php
- routes/api.php
* Create middleware to set limit to max int if the key comes from bibleis or gideons
* Use tag_exclude to exclude opus filesets from fileset call
* Remove hash_ids before query calls to avoid performance decrease
[FCBHDBP-63](https://fullstacklabs.atlassian.net/browse/FCBHDBP-63)
Tests on https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-e83ef036-62b0-480a-82a8-414f864cb70b should pass correctly
> FCBHDBP-63 Remove opus depending on bibleis API key

- public/css/app_api_key.css
- resources/views/api_key/dashboard.blade.php
- resources/views/emails/key_request.blade.php
* add html  formatted message to email format on key request dashboard
[FCBHDBP-54](https://fullstacklabs.atlassian.net/browse/FCBHDBP-54)
> FCBHDBP-54 prepopulate html email on api_key dashboard

- app/Http/Controllers/Bible/BibleFileSetsController.php
* use fileset type for text_plain and text_format on showChapter
* use fileset type for text_plain and text_format on showBulk
[FCBHDBP-57](https://fullstacklabs.atlassian.net/browse/FCBHDBP-57)
> FCBHDBP-57 use fileset type for text filests

- app/Http/Controllers/Bible/BibleFileSetsController.php
[FCBHDBP-57](https://fullstacklabs.atlassian.net/browse/FCBHDBP-57)
> FCBHDBP-57 defaul plain text if no text type is declared

- app/Http/Controllers/Bible/BibleFileSetsController.php
> FCBHDBP-57 add type to cache on biblefilesets

- app/Http/Middleware/BibleIsBackwardCompatibility.php
* use checkparam to check both params and header on biblesAll middleware
> Fix to use checkparam and use headers on middleware

- app/Http/Controllers/Bible/LibraryController.php
* check if language exists for a given iso
* If no iso, or no language, return empty response
[FCBHDBP-65](https://fullstacklabs.atlassian.net/browse/FCBHDBP-65)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-6ebe8f1b-4e45-44be-91d1-e3fc6761cfe5
> FCBHDBP-65 fix 500 error - library / volume

- app/Models/Bible/Bible.php
[FCBHDBP-127](https://fullstacklabs.atlassian.net/browse/FCBHDBP-127)
> FCBHDBP-127 use raw where to improve memory usage biblesall query

- app/Http/Controllers/Bible/LibraryController.php
- app/Http/Middleware/ApiVersion.php
- app/Transformers/V2/LibraryCatalog/LibraryMetadataTransformer.php
add v3 compat library volume with language check
[FCBHDBP-67](https://fullstacklabs.atlassian.net/browse/FCBHDBP-67)
> FCBHDBP-67 add v3 compat library volume with language check

- app/Http/Controllers/Wiki/LanguagesController.php
* force 50 item pagination on languages
* pagination limit mas changes only if bibleis-gideons
[FCBHDBP-21](https://fullstacklabs.atlassian.net/browse/FCBHDBP-21)
* https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-6303ed10-84f0-409e-9fed-1e58e94ccf45
* https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-497973ad-db0a-4758-a9ea-43db813d8f8e
> FCBHDBP-21 add forced pagination to languages (except bibleis)

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Wiki/CountriesController.php
- app/Http/Controllers/Wiki/LanguagesController.php
* Add pagination to countries index
* Create herlper to force endpoint pagination if is bibleis or gideons
[FCBHDBP-27](https://fullstacklabs.atlassian.net/browse/FCBHDBP-27)
* https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-56969ec3-bf58-4e38-b292-e8be89d1cdc2
* https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-a5ad921f-3be8-4b39-b2bc-d7efffbe7eb3
> FCBHDBP-27 add pagination to countries

- app/Console/Commands/syncLiveBibleIsBookmarks.php
- app/Console/Commands/syncLiveBibleIsHighlights.php
- app/Console/Commands/syncLiveBibleIsNotes.php
> FCBHDBP-3 rename live bibleis tables

- app/Console/Commands/syncLiveBibleIsBookmarks.php
- app/Console/Commands/syncLiveBibleIsHighlights.php
- app/Console/Commands/syncLiveBibleIsNotes.php
- app/Console/Commands/syncV2Bookmarks.php
- app/Console/Commands/syncV2Highlights.php
- app/Console/Commands/syncV2Notes.php
- app/Helpers/Helpers.php
> FCBHDBP-3 Fix data on annotations for live bibleis

- app/Console/Commands/syncLiveBibleIsBookmarks.php
- app/Console/Commands/syncLiveBibleIsHighlights.php
- app/Console/Commands/syncLiveBibleIsNotes.php
- app/Helpers/Helpers.php
* Check if annotation exists before inserting
* Check correct bible and fileset exist before insert
> FCBHDBP-3 use correct data on annotations and check annotation exists

- app/Console/Commands/syncLiveBibleIsBookmarks.php
- app/Console/Commands/syncLiveBibleIsHighlights.php
- app/Console/Commands/syncLiveBibleIsNotes.php
- app/Helpers/Helpers.php
* check users for v4
* Check bibles before inserting
* transform bibles that don't exist anymore with the sync file
> FCBHDBP-3 add checks on sync annotations and verify bibles

- app/Console/Commands/syncLiveBibleIsNotes.php
> FCBHDBP-3 add verse_end to note sync

- app/Http/Controllers/Bible/BibleFileSetsController.php
* look in bible>Verse only if it's text plain
* if text_format return signed url with html text
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-27213a5a-06e4-4d10-a83d-fd082a408021
> text_format-fix text_format work correctly  if type is given

- app/Console/Commands/syncLiveBibleIsBookmarks.php
- app/Console/Commands/syncLiveBibleIsHighlights.php
- app/Console/Commands/syncLiveBibleIsNotes.php
- app/Console/Commands/syncLiveBibleIsUsers.php
- app/Console/Kernel.php
- config/settings.php
* Create php artisan syncLiveBibleIs:users 'date' to sync live bibleis users (create if dont exist)
* Validate user for all annotations
> FCBHDBP-3 validate users before creating annotations

- app/Console/Commands/syncLiveBibleIsBookmarks.php
- app/Console/Commands/syncLiveBibleIsHighlights.php
- app/Console/Commands/syncLiveBibleIsNotes.php
- app/Console/Commands/syncLiveBibleIsUsers.php
* use email check for users case insenstivie in all live bibleis sync commands
> FCBHDBP-3 check user email case insensitive

- app/Console/Commands/syncLiveBibleIsBookmarks.php
- app/Console/Commands/syncLiveBibleIsHighlights.php
- app/Console/Commands/syncLiveBibleIsNotes.php
- app/Console/Commands/syncLiveBibleIsUsers.php
> FCBHDBP-3 revert check user email insensitive

- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Models/Bible/BibleFileSecondary.php
- app/Models/Bible/BibleFileset.php
- database/migrations/2021_06_16_165236_create_bible_files_secondary_table.php
* Create models for secondary_file
* Create migration for secondary_file
* Create signed url for fileset's thumbnails
[FCBHDBP-128](https://fullstacklabs.atlassian.net/browse/FCBHDBP-128) 
[FCBHDBP-57](https://fullstacklabs.atlassian.net/browse/FCBHDBP-57)
> FCBHDBP-57 create secondary_file models and add thumbnails to filesets

- app/Http/Controllers/Wiki/LanguagesController.php
- app/Models/Language/Language.php
- app/Transformers/LanguageTransformer.php
* add dbp-vid asset filter if show_bibles and bibleis/gideons to avoid query to grow with the fileset quantity
[FCBHDBP-131](https://fullstacklabs.atlassian.net/browse/FCBHDBP-131)
* https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-8011d3eb-e868-4780-a1ea-0459d232165a
> FCBHDBP-131 improve language endpoint for bibleis videos

- app/Http/Controllers/Plan/PlansController.php
* the cache was only for featured plans and wasn't working correctly, if we really want. to cache a small amount we can add it back correctly and. fix the. bug with cache, but I don't think is worth using cache for featured plans due to the small amount of data that is retrieved
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-e7ecdd56-6982-4163-a88e-0af824780dff
with languages different from english
> plans_hotfix remove unnecessary cache on featured plans

- resources/views/auth/passwords/reset.blade.php
* reorder js code to stay on header of blade
[FCBHDBP-34](https://fullstacklabs.atlassian.net/browse/FCBHDBP-34)
> FCBHDBP-34 fix reset password forms and responses for non api users

- app/Http/Controllers/Wiki/CountriesController.php
* Add page to cache params
[FCBHDBP-133](https://fullstacklabs.atlassian.net/browse/FCBHDBP-133)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-6fb6b207-f50d-43b0-8213-fbdcc4fb66e9?ctx=documentation
> FCBHDBP-133 fix pagination cache for countries

- app/Http/Controllers/Bible/LibraryController.php
- app/Transformers/V2/LibraryVolumeTransformer.php
* Join secondary_files table
* transform zip sedcondary file to audio_zip_path
[FCBHDBP-67](https://fullstacklabs.atlassian.net/browse/FCBHDBP-67)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-8ab77c01-9457-4079-adcb-607b2be4c0b6
> FCBHDBP-67 add secondary files on library volume

- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Transformers/FileSetTransformer.php
* Add thumbnail only on chapter endpoint
* Remove take one from join on secondary_file link
[FCBHDBP-59](https://fullstacklabs.atlassian.net/browse/FCBHDBP-59)
> FCBHDBP-59 add thumbnail to fileset chapter endpoint

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BibleFileSetsController.php
- app/Http/Controllers/Bible/LibraryController.php
- app/Transformers/FileSetTransformer.php
- app/Transformers/V2/LibraryVolumeTransformer.php
* add signed path for zip,  secondary files
* add signedUrl using signedPath
[FCBHDBP-67](https://fullstacklabs.atlassian.net/browse/FCBHDBP-67)
> FCBHDBP-67 add signed url to zip path

- resources/views/auth/passwords/reset.blade.php
- resources/views/layouts/app.blade.php
* Improve styling on password reset view 
[FCBHDBP-34](https://fullstacklabs.atlassian.net/browse/FCBHDBP-34)
> FCBHDBP-34 Fix password reset styles

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/User/BookmarksController.php
- app/Http/Controllers/User/HighlightsController.php
- app/Http/Controllers/User/NotesController.php
* return by default 180 annotations for each annotation on endpoint
[FCBHDBP-52](https://fullstacklabs.atlassian.net/browse/FCBHDBP-52)
> FCBHDBP-52 add verse pagination on chapter annotations

- routes/api.php
Update comments regarding deprecated endpoints
> update comments re: deprecated endpoints

- app/Transformers/FileSetTransformer.php
Add thumbnail for video on chapter lever
[FCBHDBP-67](https://fullstacklabs.atlassian.net/browse/FCBHDBP-67)
> FCBHDBP-67 add chapter level thumbnail on video

- app/Helpers/Helpers.php
> FCBHDBP-137 log deprecation data

- app/Http/Controllers/Bible/BiblesController.php
* Order by priority if is used by bibleis/gideons
> FCBHDBP-148 add backward compat for bible ordering

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BiblesController.php
- config/auth.php
* fix app version for deprecation
* add support for older user agents gid/bibleis
* Env variables to set:
BIBLEIS_KEYS=
GIDEONS_KEYS=
BIBLEIS_DEPRECATE_FROM_VERSION=
GIDEONS_DEPRECATE_FROM_VERSION=
[FCBHDBP-148](https://fullstacklabs.atlassian.net/browse/FCBHDBP-148)
> FCBHDBP-148 Finish deprecation versioning 

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Wiki/CountriesController.php
- app/Http/Controllers/Wiki/LanguagesController.php
Add rememberForHeavyCalls to avoid sql getting hit by multiple calls on the same query and wait for cache to be written
[FCBHDBP-145](https://fullstacklabs.atlassian.net/browse/FCBHDBP-145)
> FCBHDBP-145 add lock for heavy calls to avoid multiple calls

- app/Helpers/Helpers.php
* remove unnecessary app_name checks and updates
* return true on backward compat if it comes from b ibleis gideons app, but the user agent is different from the new one
[FCBHDBP-146](https://fullstacklabs.atlassian.net/browse/FCBHDBP-146)
> FCBHDBP-146 use backward compat for non recognized useragent

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Wiki/CountriesController.php
- app/Http/Controllers/Wiki/LanguagesController.php
> FCBHDBP-146 remove heavyCalls cache and add checks on helpers

- app/Helpers/Helpers.php
> FCBHDBP-146 fix app version checks

- app/Http/Controllers/Wiki/CountriesController.php
> FCBHDBP-145 add cache for heavy calls on contries all

- app/Http/Controllers/Wiki/CountriesController.php
> FCBHDBP-145 add sleep to test cache

- app/Http/Controllers/Wiki/LanguagesController.php
> FCBHDBP-145 add sleep to test cache on languages

- app/Http/Controllers/Bible/BiblesController.php
- resources/lang/eng/api.php
- resources/lang/spa/api.php
> Fcbhdbp 145

- app/Http/Controllers/Bible/BiblesController.php
> FCBHDBP-145 remove orderby from cache params

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Wiki/CountriesController.php
- app/Http/Controllers/Wiki/LanguagesController.php
> FCBHDBP-145 fix orderby on bibles cache

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BiblesController.php
> test cache responses on bibles

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Wiki/CountriesController.php
- app/Http/Controllers/Wiki/LanguagesController.php
> FCBHDBP-145 revert heavycalls cache

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Wiki/CountriesController.php
- app/Http/Controllers/Wiki/LanguagesController.php
Change pagination limit for languages to 150 max
[FCBHDBP-154](https://fullstacklabs.atlassian.net/browse/FCBHDBP-154)
> FCBHDBP-154 change pagination limit for heavy endpoints

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Bible/LibraryController.php
- app/Http/Controllers/Bible/ReaderController.php
- app/Http/Controllers/Wiki/LanguageControllerV2.php
- app/Http/Controllers/Wiki/LanguagesController.php
- app/Models/Bible/Bible.php
- app/Models/Language/Language.php
- app/Traits/AccessControlAPI.php
- tests/Feature/AccessControlTest.php
- tests/Integration/BibleTextTest.php
- tests/Integration/BiblesRoutesTest.php
* Change access control to also check languages and bibles
* Add new capability on languages to handle access control by languages
[FCBHDBP-155](https://fullstacklabs.atlassian.net/browse/FCBHDBP-155)
> FCBHDBP-155 Improve languages slowness using access control

- app/Helpers/Helpers.php
- app/Http/Controllers/Wiki/LanguagesController.php
- app/Traits/AccessControlAPI.php
> pre-deploy add comments to deploy prod

- app/Traits/AccessControlAPI.php
add database names on raw sql for access control
> sql-fix add database names on raw sql for access control

- app/Helpers/Helpers.php
> Fix max php int issue

- app/Http/Controllers/Wiki/CountriesController.php
- routes/api.php
* Generate search endpoint on routes
[FCBHDBP-134](https://fullstacklabs.atlassian.net/browse/FCBHDBP-134)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-16cbd5d5-08a3-4517-870c-617fa5ffae81
> FCBHDBP-134 create search for countries

- app/Http/Controllers/Wiki/LanguagesController.php
- app/Models/Language/Language.php
- app/Transformers/LanguageTransformer.php
- routes/api.php
* Create search endpoint for language
* Add autonym and name search
* remove unnecessary properties and queries
[FCBHDBP-135](https://fullstacklabs.atlassian.net/browse/FCBHDBP-135)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-71f39546-a978-4559-a919-e7a4bf083e41
> FCBHDBP-135 Add language search by name and autonym

- app/Helpers/Helpers.php
Craete lock/block logic to avoid race conditions on mysql and cache calls
> Cache-lock cache remember changed to use lock for race conditions

- app/Helpers/Helpers.php
> add log statements to cache

- app/Helpers/Helpers.php
> cache-lock Add guard error for cache key length

- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/BiblesController.php
> cache-lock make cache key for bibles smaller

- app/Helpers/Helpers.php
> cache-lock generate cache lock key correctly

- app/Helpers/Helpers.php
* Clean cache remember code
* Use lock and block on cache to avoid parallel calls causing a race condition
[FCBHDBP-156](https://fullstacklabs.atlassian.net/browse/FCBHDBP-156)
> cache-lock clean code and get chaceRemember ready

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Wiki/CountriesController.php
- app/Http/Controllers/Wiki/LanguagesController.php
- app/Transformers/BibleTransformer.php
- resources/lang/eng/api.php
- routes/api.php
[FCBHDBP-136](https://fullstacklabs.atlassian.net/browse/FCBHDBP-136)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-71f39546-a978-4559-a919-e7a4bf083e41
> FCBHDBP-136 Create search endpoint for bibles

- composer.json
- composer.lock
It has updated dependencies to support composer version 1.10.22.
It has updated the next dependencies to support the composer v1.10.22.
- `sentry/sentry-laravel`
- `barryvdh/laravel-ide-helper`
https://fullstacklabs.atlassian.net/browse/FCBHDBP-17
The main dependency updated is the framework and we need to check the upgrade guide and check the Impact Changes.
https://laravel.com/docs/6.x/upgrade#belongs-to-update
> It has updated dependencies to support composer version 1.10.22.

- .ebextensions/newrelic.config
Hotfix - restore new relic configuration
> restore newrelic

- app/Http/Controllers/Bible/VideoStreamController.php
- routes/api.php
* Add new endpoint
* Check that book and language exist before calling the endpoint
* add caching to languages and media languages
* retrieve streaming files without caching
[FCBHDBP-162](https://fullstacklabs.atlassian.net/browse/FCBHDBP-162)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-36408baf-44a7-4c63-b28e-e012754aa0e5
> FCBHDBP-162 Add video endpoint to return arclight by chapter

- app/Http/Controllers/Bible/LibraryController.php
- app/Transformers/V2/LibraryVolumeTransformer.php
* add validation on null secondary files
* check coombined name and compare to not return double names on library volumes transformer
> hotfix-volume-dbp2 library/volume no duplication in volumename

- app/Http/Controllers/Bible/LibraryController.php
- app/Transformers/V2/LibraryVolumeTransformer.php
> Hotfix master volume dbp2

- app/Http/Controllers/Bible/VideoStreamController.php
- app/Traits/ArclightConnection.php
- config/services.php
> FCBHDBP-162 add timeout on arclight proxy calls

- app/Console/Commands/BibleEquivalents/UpdateBibleLinkOrganizations.php
- app/Console/Commands/Wiki/OrgDigitalBibleLibraryCompare.php
- composer.json
- composer.lock
develop-php8 It has fixed the organizations parameter, removed comment lines and and it has added the dependency for new relic.
> Develop php8 comment fix

- app/Http/Controllers/Wiki/LanguageControllerV2.php
it has fixed the country/countrylang endpoint to support the order by `lang_code` column.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-182
You should execute the next endpoint and it should not return error.
- Active Development / v2_backward_compatibility / countrylang with lang_code
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-9b3d3c0f-07a9-4fe5-be0b-8820d05bd96f
> FCBHDBP-182 500 error on v2 backward compat - country/countrylang

- app/Http/Controllers/Bible/VideoStreamController.php
This adds a check before returning 404 for arclight, the previous was causing an error catched by a try/catch 
[FCBH-3870](https://fullstacklabs.atlassian.net/browse/FCBH-3870)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-42e62814-f771-424c-8271-ade32a5bfca1
> FCBH-3870 Fix arclight returning empty array

- app/Http/Controllers/Wiki/LanguageControllerV2.php
Added a fix to avoid that the sort column by default is ambiguous.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-195
- You should execute the Postman endpoint:  v2_backward_compat / Priority Group 3 / country/countrylang
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-dedf0d9d-a407-4aa4-82c7-a79a924882f8
> FCBHDBP-195 Fix v2_backward_compat / Priority Group 3 / country/countrylang

- app/Helpers/Helpers.php
> Change the cache string limit to use md5

- app/Http/Controllers/Bible/BibleFileSetsController.php
It has added the supporting to pull the filesets with type: text_usx.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-192
- You should execute the postman endpoint:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-5bf4f9a2-f28a-4820-9bb8-5bbb0dc732e4
> FCBHDBP-192 return usx filesets

- app/Exceptions/Handler.php
- app/Http/Controllers/User/UsersController.php
- resources/lang/eng/auth.php
- resources/lang/spa/auth.php
- resources/views/api_key/login.blade.php
- resources/views/auth/login.blade.php
it has added the feature to handle the session expired case.
We need to check the value of .env parameter: SESSION_LIFETIME, this value should greater than 0 and it is related to the minutes to expire the user session.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-201
You should try to login with a valid user through the action /admin/login.
> FCBHDBP-201 500 error when navigating to web page to approve keys

- app/Exceptions/Handler.php
- app/Helpers/Helpers.php
- app/Http/Controllers/Bible/AudioController.php
- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Wiki/LanguageControllerV2.php
Check and improve the bible_filesets queries to use the new isContentAvailable method. This working branch was created from FCBHDBP-189 branch.
This PR is related with the next PR:
- https://github.com/faithcomesbyhearing/dbp/pull/523
https://fullstacklabs.atlassian.net/browse/FCBHDBP-189
Execute the endpoint inputted into the next PR: 
- https://github.com/faithcomesbyhearing/dbp/pull/523
> FCBHDBP-189 hardening: queries using bible_filesets table should be efficient

- app/Http/Controllers/Bible/TextController.php
- app/Http/Controllers/Bible/Traits/TextControllerTrait.php
It has updated the bulkAccessControl method to optimize - issue
After to execute the "[M] bible.is mobile requests" for the dev environment I saw two errors. So, I have fixed the controllers that invoke the `withVernacularMetaData` method that belongs `BibleVerse` model. Overall, the issue was in the TextController.php because it was trying to select some columns from query that were not included. 
- [M] bible.is mobile requests group
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/run/17122915-5a8a5d41-e9ab-4f85-9f38-926990310420
https://fullstacklabs.atlassian.net/browse/FCBHDBP-202
Execute the next 2 postman URL and they should not return 500 error.
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d …
> FCBHDBP-202 FIX - It has updated the bulkAccessControl method to optimize

- app/Http/Controllers/Wiki/LanguagesController.php
- app/Models/Language/Language.php
- app/Traits/AccessControlAPI.php
- app/Traits/CallsBucketsTrait.php
Then ensure that all tests pass. The ones that currently fail are 
- languages partial last page
- Languages Search (four letters) [why is this slower than a two letter search?]
- languages with translations
- Language Search (verify fulltext)
- bibles last page partial
- bible - filesets - id 
I have done a refactor for the next endpoints and it has improved the response time:
- Languages Search (four letters)
- languages with translations
- Language Search (verify full-text)
The endpoint to search a languages has been refactored and I have improved the response time. Specifically, it has improved the response time for two or more letter search as you can see in the next screenshot:
I have update the next endpoint and it has reduced the amount queries:
- bible - filesets - id 
It has …
> FCBHDBP-219 hardening: shave response time off the tests in Example Workflow that occasionally fail due to excessive response time

- app/Http/Controllers/Bible/TextController.php
Fixed the `TextController` that invonkes the `withVernacularMetaData` method that belongs `BibleVerse` model. We need to know if the bible has the property: numeral_system_id to include the `numeral_system_glyphs` columns into the SELECT clause.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-236
- The next postman URL should be return error.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-a9148994-352f-4e75-bb14-19a88b195bbe
> FCBHDBP-236 500 error - bibleis search using NIV

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Wiki/CountriesController.php
- app/Http/Controllers/Wiki/LanguagesController.php
Merge master-php8 into dev to merge the FCBHDBP-237 hotfix
Merge master-php8 into dev to merge the FCBHDBP-237 hotfix
> FCBHDBP-237 hotfix into dev

- app/Http/Controllers/Wiki/LanguagesController.php
It has added the new parameters to cache key and it has added the method to remove space form cache keys.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-222
- - Languages list with only video filesets by name with space
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-0772685c-d55b-4a98-8e3b-f7e793e98ca6
> FCBHDBP-222 Add feature to filter langauges by  bible_fileset media type (audio/video) - fix

- app/Http/Controllers/Bible/Traits/TextControllerTrait.php
[FCBHDBP-250](https://fullstacklabs.atlassian.net/browse/FCBHDBP-250)
*  Active Development / v2_compat / James Thomas / text verse book
> FCBHDBP-250 order by chapter on text verse endpoint

- app/Transformers/TextTransformer.php
Add paragraph number the same value as verse id
[FCBHDBP-252](https://fullstacklabs.atlassian.net/browse/FCBHDBP-252)
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-7ad98296-d01d-4cce-a6be-9d12ee55cd81
> FCBHDBP-252 add paragraph to text verse endpoint

- app/Http/Controllers/Bible/LibraryController.php
- app/Http/Controllers/Wiki/LanguageControllerV2.php
- app/Models/Language/LanguageCodeV2.php
- app/Transformers/V2/CountryLanguageTransformer.php
- app/Transformers/V2/LibraryCatalog/LanguageListingTransformer.php
- database/migrations/2021_12_05_215145_create_language_codes_v2.php
* Create migration to add language_codes_v2
* Create method to use v2 codes and pass data to transformers
[FCBHDBP-253](https://fullstacklabs.atlassian.net/browse/FCBHDBP-253)
> FCBHDBP-253 add v2 language interface for language endpoints

- app/Http/Controllers/Bible/LibraryController.php
- app/Http/Controllers/Connections/ArclightController.php
* Add translation table from bibles to filesets onn volume library
[FCBHDBP-153](https://fullstacklabs.atlassian.net/browse/FCBHDBP-253)
> FCBHDBP-253 add support to translations on library volume

- app/Http/Controllers/Bible/LibraryController.php
Validate that the name parameter is not empty to use the constraint.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-261
- Execute Priority Group 4 of Postman v2_backward compatibility
> FCBHDBP-261 hotfix v2_compat: library version with no filter should return all versions

- app/Http/Controllers/Bible/LibraryController.php
It has added the user key as a cache parameter for the library volume endpoint.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-aea96a6f-129d-4945-8e9d-6b2d9f69d8a8
> FCBHDBP library volume endpoint and user key

- app/Http/Controllers/Bible/BibleFilesetsDownloadController.php
- app/Http/Controllers/User/UsersDownloadAnnotations.php
- app/Models/User/Annotations.php
- app/Models/User/Study/Highlight.php
- app/Models/User/Study/Note.php
- app/Transformers/UserHighlightsTransformer.php
- app/Transformers/UsersDownloadAnnotationsTransFormer.php
- routes/api.php
FCBHDBP-259 It has created the new endpoint to pull all user annotations. It has added the openapi documentation for the new endpoint to download all user annotations. Removed the tags relationship. Added the new Annotations class to handle the annotations response. It will be a wrapper to handle the notes, bookmarks and highlights.
The new schema will have the next pattern:
```json
{
"data": {
"notes": [
{
"bible_id": "ENGESV",
"book_id": "MAT",
"chapter": 1,
"verse_start": 4,
"verse_end": 4,
"notes": "this is a test note"
},
....
],
"bookmarks": [
{
"bible_id": "ENGESV",
"book_id": "MAT",
"chapter": 1,
"verse": 4
},
....
],
"highlights": [
{
"bible_id": "ENGESV",
"book_id": "MAT",
"chapter": 1,
"verse_start": 4,
"verse_end": 4,
"highlighted_color": "rgba(23,128,239,1)"
},
....
]
}
}
``` …
> FCBHDBP-259 create annotations endpoint to retrieve all annotations for bible/book?/chapter?

- app/Http/Controllers/Plan/PlansController.php
- app/Models/Plan/PlanDay.php
It has added the logic to check if a day has fileset attached to consider it in the calculation to get the translated percentage value when user tries to translate a plan.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-265
- Execute all test for the next postman folder:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-7025c337-9dab-4194-9879-b69e17e584f7
> FCBHDBP-265 The translate plan and playlist should support empty days

- app/Http/Controllers/Bible/BiblesController.php
- app/Models/Bible/Bible.php
Add the filter to return only the bible in the response if the bible has timestamps.
The response time increases when the filter is enabled. The above because the `bible_file_timestamps` table has a lot records around 2M of records. The average response time is around 835 ms. The goal was not to include the bible_file_timestamps in the main query otherwise it included the entity in the query with a small scope.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-241
- Execute the next postman URL tests: 
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-fab6bc96-b732-435b-bde4-30d0e4672b23
> FCBHDBP-241 Modify bibles endpoint to support filtering by availability of audio_timings

- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Plan/PlanDay.php
- app/Models/Plan/UserPlan.php
It has done refactor to the endpoint to complete a item playlist. It has created two queries to know the **percentage completed** value and to know if every plan day that belongs to user plan has all items completed to complete the **plan day**.
So, we have replace the logic that is executing a query for each plan day and for example it could be around 365 queries for a plan with 365 days.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-271
- We need to do login with a user 
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-30ac0b9d-13fb-4f4f-9f5a-22f8d8fc869f
- We need to start a plan
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-30ac0b9d-13fb-4f …
> FCBHDBP-271 Refactor the endpoint to complete a playlist item.

- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Playlist/PlaylistItems.php
- app/Transformers/PlanDayPlaylistItemsTransformer.php
- app/Transformers/PlanTransformer.php
- app/Transformers/PlanTransformerBase.php
- app/Transformers/PlanTranslateTransformer.php
- app/Transformers/PlaylistTransformer.php
It has supported the endpoint to translate a plan because the changes into the playlist translate logic have affected the plan translate plan.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-293
- Postman URL to Translate a Playlist 
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-9c1f544c-37f4-40f5-b467-02e59e685a90
- Postman URL to Translate a Plan
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-af82f28b-33d8-4031-96fc-7c2545fd678b
> FCBHDBP-293 optimize playlist.translate

- app/Console/Commands/TranslatePlan.php
- app/Console/Commands/TranslatePlaylist.php
- app/Console/Kernel.php
- app/Http/Controllers/Plan/PlansController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Plan/Plan.php
- app/Models/Playlist/Playlist.php
- app/Models/Playlist/PlaylistItems.php
- app/Services/Plans/PlanService.php
- app/Services/Plans/PlaylistService.php
- app/Transformers/PlanDayPlaylistItemsTransformer.php
- app/Transformers/PlanTranslateTransformer.php
It has created the Plan services to share business logic between the controllers and the commands. It has the new services: `PlanService` and `PlaylistService`. The above will have the business logic to handle the translate action for the plan and playlist.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-278
- Execute the Postman folder: bibleis with user session
> FCBHDBP-278 fix artisan command translate:plan

- app/Http/Controllers/Bible/StreamController.php
- app/Traits/BibleFileSetsTrait.php
It has fixed the method to get a Multi Mp3 chapter.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-327
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-98621bfc-a49c-497d-8a3b-a3129170ae24
> FCBHDBP-327 Failure on download of usx fileset

- app/Traits/BibleFileSetsTrait.php
- app/Transformers/FileSetTransformer.php
It has added the filesize property to the endpoint response to fetch the audio files.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-333
- The next postman URL should pass the tests.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-9a5aab2f-ded9-4508-94c5-898eda47365e
> FCBHDBP-333 return file_size from bible/filesets endpoint

- app/Http/Controllers/Bible/VideoStreamController.php
- app/Services/Arclight/ArclightService.php
- app/Transformers/JesusFilmChapterTransformer.php
- composer.json
- composer.lock
It has created a refactor to get the jesus films records. It has added a feature to do the request to arclight endpoint async way. The above to improve the performance. So, It has added the symfony/http-client bundle to do the arclight requests.
I have tested it on local environment without cache and it is taking around 3.50 seconds. It was taking around 25 seconds before these changes.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-339
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-38bc2d75-6933-4257-8630-8a10b14a8490
> FCBHDBP-339 optimize endpoint v4_video_jesus_film_chapter (LUK 23)

- composer.json
- composer.lock
Reverts faithcomesbyhearing/dbp#806
> Revert "Update all non-major dependencies"

- composer.json
- composer.lock
It has downgraded the bundles: `symfony/yaml` and `symfony/http-client` because the latest versions for these bundles are requiring php 8.1 and we are not supporting php 8.1 yet.
You should run all [M] postman test and they should pass.
> FCBHDBP-package-hotfix

- app/Helpers/Helpers.php
- app/Models/Bible/BibleFilesetLookup.php
- app/Traits/AccessControlAPI.php
It has created a new method in Helpers to return Download AccessGroup list as an array of integers.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-399
You should execute all [M] Download requests postman tests and they should pass.
> FCBHDBP-399 DBP - changing configuration for DOWNLOAD_ACCESS_GROUP_LIST caused unexplained errors 

- app/Models/Playlist/PlaylistItems.php
- app/Services/Plans/PlaylistService.php
- composer.lock
It has fixed related to endpoint to store a playlist item. The endpoint was not returning the data related with the new item stored rather, it was always returning data related with first item of the playlist.
We have used a transaction to guarantee that we can fetch the last playlist item records inserted.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-418
- You must run the following postman URL:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-041aa795-75e3-4fb8-bb3b-2c1acfbdd22c
- You should run all test for following folder and they should pass.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-4b8e2d55-4e2d-4271-950e-befdd6ffa6cc
> FCBHDBP-418 Issue related the endpoint to store a playlist item

- config/settings.php
Merge with master to resolve conflicts.
> FCBHDBP merge with master to resolve conflicts.

- app/Models/Country/Country.php
FCBHDBP It has created a hotfix to support sql query on mysql 8 and 5.7.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-443
We should execute the following postman test and it should pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-83349e80-9983-4d48-946f-279e38d9dfb9
> FCBHDBP country list hotfix

- app/Models/Bible/BibleFileset.php
- app/Models/Bible/BibleFilesetTag.php
- app/Transformers/BibleTransformer.php
I have updated the BibleTransformer class because it had a similar logic to old method: `formatFilesetMeta`.  Then, the BibleTransformer has moved the logic related to meta tags values to the BibleFileset Model class in order to centralize this logic in a single location.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-508
1. **I have created 4 failing Postman test related to `bibles/:bible_id` and `bibles/` endpoints:**
- Get bible by ID: TCSWYI fileset stocknumber null
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-444770ed-fc0a-4edb-9af7-a4fe8f5eb668
- Get bible by ID: EN1ESV
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-6191ff45-1ddd-4b2e-9 …
> FCBHDBP-508 Temporarily add stocknum attribute, with no value - Hotfix

- app/Models/Playlist/PlaylistItems.php
- app/Traits/BibleFileSetsTrait.php
Merge from Master php8 to develop
We can execute the following postman test:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/folder/12519377-c03d49d4-8b41-4b33-ade4-3774de944c09
> Merge from Master php8 to develop

- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Models/Playlist/PlaylistItems.php
- app/Models/User/Study/Note.php
Merge from Master php8 to development
> Merge from Master php8 to development

- app/Http/Controllers/Playlist/PlaylistsController.php
Reverts faithcomesbyhearing/dbp#883
> Revert "FCBHDBP-535 Issue with fileset ENGGIDN2SA book= 2TI chapter=2 verse=12"

- app/Http/Controllers/Playlist/PlaylistsController.php
> Modify transport stream for verse range in timestamp

- app/Http/Controllers/Bible/BibleFilesetsDownloadController.php
- app/Traits/AccessControlAPI.php
> Merge from Master to Develop

- app/Models/Bible/BibleFileset.php
I have identified two areas where the query could be improved: excluding old DA16Format and determining if the filesets have content available. During testing, I found that the query to verify if BibleFileset records have content available had a performance issue, especially when filtering large numbers of records like in the Postman test, "Bibles are returned in priority order backward compat mode" at https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-c0d1ac98-aa6b-4394-9803-9e23e87d6101.
This endpoint should return all filesets records attached to a specific key. To address this issue, I improved the query by narrowing its scope. So, it will filter first the access groups and after, it will be able to filter the …
> FCBHDBP-531 Hotfix DBP: prefer opus16 fileset over DA16

- routes/apiV2.php
Add the AccessControl middleware to the v2_text_volume endpoint.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-554
- The following postman test have to pass:
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-da96db61-29c6-466b-8fc5-97c9bf5306c3
> FCBHDBP-554 Hotfix - text/volume endpoint failure

- .platform/hooks/prebuild/install_newrelic.sh
> set license key and fix cleanup

- .platform/hooks/prebuild/install_newrelic.sh
- fix cleanup of newrelic php agent - only cleanup the tarball
> fix cleanup of newrelic php agent

- .platform/hooks/prebuild/install_newrelic.sh
use opt dir for newrelic agent
> use opt dir for newrelic agent

- .platform/hooks/prebuild/install_php_zip.sh
Attempted workaround to environment update issue
Modified the install of zip in php to 'upgrade' instead - which will install if not present, or upgrade if needed.
Attempt upgrade of environment in dev
> upgrade zip rather than install

- app/Models/Bible/BibleFileset.php
Update the logic to retrieve filesets by Bible ID based on the existence of filesets with 6 and 10 characters.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-609
Run the following postman test
1. Bible ID BULBOB: Return fileset BULBOB (6 character) and BULBOBN_ET (10 character)
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-7d50c3c3-2522-4816-bbd5-054931d4497d?active-environment=810fd94b-9392-43e2-9f13-943e8d323135
2. Bible ID ENGWEB: Don't return ENGWEBN  (6 character)  and Return new filesets: ENGWEBN_ET and ENGWEBO_ET
- https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-ee20de37-90e3-488a-b68b-412cb6a81f13?active-environment=810fd94b-9392-43e2 …
> FCBHDBP-609 The playlist endpoint is not returning the verse text when both the new (10-character) and old (6-character) plain text filesets exist

- app/Models/Bible/BibleFileset.php
- composer.json
- composer.lock
- config/settings.php
update access groups to include those managed by blimp
> develop to master - update access groups to include those managed by blimp

- app/Http/Controllers/Wiki/LanguagesController.php
- app/Models/Language/Language.php
- app/Transformers/LanguageTransformer.php
- database/migrations/2024_07_02_225455_add_deleted_at_to_languages.php
Added a new column deleted_at to the languages entity in the languages API endpoints.
[User Story 2214](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2214): Blimp: handle language soft deletes
I have added the new column a the following postman test:
- Languages list
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-1112495f-6d34-4d42-8ab4-c4e5e4b46922?action=share&source=copy-link&creator=17122915&active-environment=810fd94b-9392-43e2-9f13-943e8d323135
- Languages by ID
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-aa2e207f-b68b-4753-a6d1-704f4d36702c?action=share&source=copy-link&creator=17122915&active-environment= …
> Task-2214 

- app/Models/User/Study/UserAnnotationTrait.php
- docker/php/Dockerfile
Added logic to ensure that user highlights extract the verse text from a fileset with the content_loaded flag set to true and the archived flag set to false.
https://fullstacklabs.atlassian.net/browse/FCBHDBP-611
- Login test user
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-10dffd1f-2753-4715-adc7-895ea4e6bb49?action=share&source=copy-link&creator=17122915&active-environment=810fd94b-9392-43e2-9f13-943e8d323135
- Create a highlight
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12519377-4ae46003-afc0-4471-a039-36e5a0141706?action=share&source=copy-link&creator=17122915&active-environment=810fd94b-9392-43e2-9f13-943e8d323135
- Check that the highlight …
> FCBHDBP-611 Ensure that highlights select correct verse_text

- app/Models/Bible/Book.php
Updated the logic to support the covenant films. Specifically, I have updated the endpoint to retrieve active books by a specific fileset_id.
> [!IMPORTANT]
This ticket is related to the following dbp-etl and dbp-web PRs:
- https://github.com/faithcomesbyhearing/dbp-etl/pull/178
- https://github.com/faithcomesbyhearing/dbp-web/pull/89
[User Story 2478](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2478): dbp-web: enable display of Covenant Films
[User Story 2021](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2021): uploader needs to recognize Covenant film content
Run the following Postman test and it should pass.
https://digitalbibleplatform.postman.co/workspace/DBP4-workspace~0a283f7f-06d9-467d-97f0-fef92d18bd3d/request/12 …
> Ticket-2021 dbp needs to recognize Covenant film content

- app/Http/Controllers/Bible/LibraryController.php
- app/Http/Controllers/Bible/VideoStreamController.php
- app/Models/Language/Language.php
Fix ambiguous SELECT set_type_code column issue
[Bug 2903](https://dev.azure.com/keyholesoftware/FCBH%20-%20Bible%20Brain/_workitems/edit/2903): Public API: optimize slow query
You should run all [M] postman test and they don't have to return 500 code.
> Task-2903 Fix ambiguous SELECT set_type_code column issue

- app/Http/Controllers/Bible/BiblesController.php
- app/Http/Controllers/Playlist/PlaylistsController.php
- app/Services/Bibles/BibleFilesetService.php
- package-lock.json
This PR includes two significant performance and quality improvements:
- BiblesController Performance Optimization (**app/Http/Controllers/Bible/BiblesController.php:572-635**)
The original implementation was making multiple database queries when fetching verse counts for bible books, where each book triggered individual queries to count verses. Therefore, I have refactored the verse counting logic to use a single optimized database query. It reduces database queries from O(n) to O(1), significantly improving response times for bible book endpoints.
- PlaylistsController Duplicate Prevention (**app/Http/Controllers/Playlist/PlaylistsController.php:1160-1196**)
HLS playlist generation was creating duplicate transport stream entries, leading to redundant content in playlists when we have a …
> Task 2907 fix improve endpoints
